### ISSUE TITLE
@FieldResolver not... working?

### ISSUE THREAD

**Issue by chiefGui** [MichalLytek/type-graphql#1006]
**Describe the Bug**
- I have a type, `Todo`, with a `@Field()` called `text`
- I have a resolver, `TodoResolver`, which has a `@FieldResolver()` that is never called.

**To Reproduce**
```ts
// todo.schema.ts

@ObjectType()
export class Todo {
  @Field()
  _id: string

  @Field()
  text: string
}
```

```ts
// todo.resolver.ts

@Resolver(Todo)
export class TodoResolver implements ResolverInterface<Todo> {
  @Query((returns) => [Todo])
  async todos(): Promise<Todo[]> {
    return await [{ _id: Math.random().toString(), text: "hi!" }]
  }

  @FieldResolver((type) => Number)
  async text(@Root() todo: Todo): Promise<string> {
    console.log(todo) // never logs

    return await "hello world"
  }
}
```

And the query is:

```gql
query todos {
  todos {
    _id
    text
  }
}
```

FWIW, the `tsconfig.json` file is this:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "esnext",
    "lib": ["dom", "dom.iterable", "esnext", "esnext.asynciterable"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}
```

**Expected Behavior**
I'd like to see `text` as `hello world` when querying `todos`; I'm currently seeing `hi!`.

**Logs**
There are no errors.

**Environment:**

- OS: macOS Big Sur 11.5.2
- Node: v15.14.0
- Package version: ^1.1.1
- TypeScript version: ^4.4.2
- *I'm running the code above in a serverless environment; next.js, more precisely.*

**Additional Context**
From all the examples I've seen/read related to `type-graphql`, the code above seems to be correct. This leads me to believe the problem is elsewhere—turns out I have no clue what this "elsewhere" could be.

That said, do you have any ideas on how/where should I be looking to find the culprit for the field resolver not be working? Or rather am I misinterpreting how field resolvers are supposed to work?

Thanks in advance,
Gui.

**Comment by chiefGui** [comment]
I'm not sure it might be something related to CodeSandbox, but I could reproduce the same behavior here: https://codesandbox.io/s/typegraphql-api-forked-1x2z6?file=/src/resolvers/todoResolver.ts

```
mutation createTodo {
  addTodo(todoInput:{ title:"title", description:"desc" }) {
    title
    description
  }
}

query getTodos {
  getTodos {
    title
    description
  }
}
```

**Comment by chiefGui** [comment]
I just created a vanilla project, very minimal & simple, and the issue is still there. [Click here](https://github.com/chiefGui/typegraphql-test) to go to the repo or:

```shell
$ git clone git@github.com:chiefGui/typegraphql-test.git && cd typegraphql-test && yarn && yarn dev
```

Here's the query, once again:

```gql
query todos {
  todos {
    _id
    text
  }
}
```

FWIW, the only relevant folder is [`/pages/api`](https://github.com/chiefGui/typegraphql-test/tree/main/pages/api).

**Comment by chiefGui** [comment]
OK, just tested the same implementation using `express` and `apollo-server-express` instead of `nextjs` + `micro` (stateful server vs. serverless functions) and the exact same code worked as expected perfectly. Yet, I still don't know if this is `micro`, or `nextjs` or even that FieldResolvers are not supposed to work with serverless functions.

**Comment by MichalLytek** [comment]
You can call your queries by code, like:
https://github.com/MichalLytek/type-graphql/blob/master/tests/functional/simple-resolvers.ts#L75-L83

TypeGraphQL builds `GraphQLSchema` object, so if it works via the way mentioned above, it's not TypeGraphQL's fault.

With next or serverless you need to be aware of minifying the bundle which causes issues.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒

**Comment by dgurns** [comment]
@MichalLytek would love to hear more about "With next or serverless you need to be aware of minifying the bundle which causes issues."

I've been using field resolvers with no problem when compiling with Webpack and `ts-loader`, but when I switched to `swc-loader` I started seeing problems. 

Everything else seems to be working fine.

Thanks for a great project btw. 

**.swcrc:**
```
{
	"module": {
		"type": "commonjs"
	},
	"jsc": {
		"baseUrl": ".",
		"parser": {
			"syntax": "typescript",
			"decorators": true
		},
		"target": "es2018",
		"transform": {
			"legacyDecorator": true,
			"decoratorMetadata": true
		}
	}
}

```

**Comment by dgurns** [comment]
An update for anyone who is running into this problem where a `FieldResolver` isn't being run: It was luckily a really stupid error on my part.

I had a redundant `Field()` and `FieldResolver()` defined like this:

```
@ObjectType()
export class MyClass {
  Field(() => String)   <-- Just needed to remove this line!
  myField: string;
}

@Resolver()
export class MyClassResolver {
  @FieldResolver(() => String)
    myField(@Root() myClass: MyClass) {
      return 'sample string';
    }
}
```

And after that everything works great, whether compiling with `swc` or even using `swc-loader` with Webpack.

**Comment by robations** [comment]
I was also wrestling with this issue. If I remove the `@Field` decorator as @dgurns suggested I just get an error that schema metadata is missing.

In my case I solved it by combining separate resolver classes for the FieldResolver/Resolver (existing code was a bit weird but seemed to work):

**From**

```ts
    @Resolver(() => Prediction)
    class PredictionResolver {
        @FieldResolver()
        async geometry(@Root() p: Prediction): Promise<any> {
            return detailsRequest({
                placeId: p.place_id,
                fields: ["geometry"],
            }).then((res) => (res && res.geometry ? res.geometry : null));
        }
    }

    @Resolver()
    class AutocompleteResolver {
        @Query(() => [Prediction], { nullable: true })
        async autocomplete(@Arg("input") input: string): Promise<Prediction> {
            return autocompleteRequest({
                input,
            });
        }
    }
```

**To**

```ts
    @Resolver(() => Prediction)
    class AutocompleteResolver {
        @Authorized(["ROLE_USER"])
        @Query(() => [Prediction], { nullable: true })
        async autocomplete(@Arg("input") input: string): Promise<Prediction> {
            return autocompleteRequest({
                input,
                types,
                radius,
                language,
                offset,
                strictbounds,
            });
        }

        @FieldResolver()
        async geometry(@Root() p: Prediction): Promise<Geometry | null> {
            return detailsRequest({
                placeId: p.place_id,
                fields: ["geometry"],
            }).then((res) => (res && res.geometry ? res.geometry : null));
        }
    }
```

Hope this helps someone.
