### ISSUE TITLE
@Extensions decorator doesn't work in federated services 

### ISSUE THREAD

**Issue by TheFedaikin** [MichalLytek/type-graphql#1046]
**Describe the Bug**
I was planning on using `@Extensions` alongside our setup with Apollo Federation, but wasn't able to get it working. I did a [small reproduction](https://github.com/TheFedaikin/type-graphql-federation-extensions) from the examples in this repo to demonstrate the problem.

**To Reproduce**
[this is very barebones but should be enough](https://github.com/TheFedaikin/type-graphql-federation-extensions)

**Expected Behavior**
This decorator is working well if you use it without federation, so it'll be great if this was working in federated services as well.

**Logs**
Nothing in the repro, extensions object is empty

**Environment (please complete the following information):**

- OS: Was tested on MacOS, Ubuntu and Alpine
- Node: 14
- Package version: 1.1.1
- TypeScript version: 4.3+

**Additional Context**
I was able to make it work with Nest, so I assume this error is not in any downstream package.

**Comment by MichalLytek** [comment]
Apollo federation needs typedefs (string), not a GraphQL schema.

Extensions are purely runtime, `GraphQLSchema` thing, not expressable in SDL.

So I don't think I can do anything about it.

**Comment by TheFedaikin** [comment]
I see, now I wonder how it's done in the Nest... Anyway, thanks for the quick response. I assume this one can be closed, have a nice day!
