### ISSUE TITLE
Resolver inheritance dont show arguments 

### ISSUE THREAD

**Issue by LuisD20** [MichalLytek/type-graphql#1092]
i have an issue whit the typegraphql, I try to do a BaseResolver that can have a base CRUD operations whit typeorm but when i compile the protect whit ts node i don't get the arguments of their resolvers query/mutation, instead, the arguments show and then disappear after a couple of seconds of compile this is my code.

```
export function CreateBaseResolver<X extends ClassType, T extends ClassType>
(
    Suffix: string,
    ReturnEntity: T,
    BaseInput: X,
    Entity: any,
)
{
    @Resolver({ isAbstract: true })
    abstract class BaseResolver
    {
        @Mutation(() => [ReturnEntity], { name: `PostOne${Suffix}` })
        async PostOne(@Arg('Data', () => BaseInput) Data: any) 
        {
             //Make logic
        }

    }

    return BaseResolver;
}
```

This is the resolver

```
@InputType()
export class ProductInput
{
    @Field()
    Id_Product: number;
}


const ProductBaseResolver = CreateBaseResolver('Product', Product, ProductInput, Product);

@Resolver(Product)
export class ProductResolver extends ProductBaseResolver
{

}
```

I compile mi code whit ts node these are my scripts

```
  "scripts": {
    "watch": "tsc -w",
    "dev": "nodemon dist/index.js",
    "start": "node dist/index.js",
    "prestart": "ts-node src/index.ts"
  },

```
**Expected Behavior**
I expect to have in the PostOneProduct mutation the arguments I define in the input type, and there is not arguments at the end, even if i put the arguments directly, keep don't show anything.

**Environment (please complete the following information):**

- OS: Windows 10
- Node 14.15.4
- Package version 1.1.1
- TypeScript version 4.4.2

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒

**Comment by MichalLytek** [comment]
@ryanmargono please open a new issue with a minimal reproducible code example repository
