### ISSUE TITLE
@ArgsType not work correctly in NestJS

### ISSUE THREAD

**Issue by nizulzaim** [MichalLytek/type-graphql#1113]
**Describe the Bug**
If I am using `@ArgsType`, the following error will return:

```
(node:10295) UnhandledPromiseRejectionWarning: Error: Cannot determine a GraphQL input type ("GetUsersArgs") for the "query". Make sure your class is decorated with an appropriate decorator.
```

The issue will resolve if `@ArgsType` change to `@InputType`. Is there any breaking changes to the current implementation as both of NestJs and TypeGraphQL documentations still clearly give an example using `@ArgsType`

**To Reproduce**

```
// user.resolver.ts
import { Args, Query, Resolver } from '@nestjs/graphql';
import { GetUsersArgs } from './dto/user.args';
import { User } from './entities/user.entity';
import { UserService } from './users.service';

@Resolver(() => User)
export class UserResolver {
  constructor(private userService: UserService) {}

  @Query(() => [User])
  async users(
    @Args('query', { nullable: true }) query: GetUsersArgs,
  ): Promise<User[]> {
    try {
      return this.userService.find(query);
    } catch (err) {
      console.log(err);
      throw new Error('There is problem requesting your resource');
    }
  }
}
```

```
// user.args.ts
import { ArgsType, Field } from '@nestjs/graphql';

@ArgsType()
export class GetUsersArgs {
  @Field({ nullable: true })
  FirstName?: string;

  @Field({ nullable: true })
  LastName?: string;
}

```

**Expected Behavior**
ArgsType is clearly used for Query and InputType for Mutation as far as I understand

**Logs**

```
(node:10402) UnhandledPromiseRejectionWarning: Error: Cannot determine a GraphQL input type ("GetUsersArgs") for the "query". Make sure your class is decorated with an appropriate decorator.
```

**Environment (please complete the following information):**

- OS: MacOS
- Node v14.7.0
- Package version: @nestjs/graphql@^9.1.1

**Additional Context**
The issue happens in NestJS. However, if I understand correctly NestJS just encapsulate TypeGraphQL implementation so don't know where should I report this issue.

**Comment by MichalLytek** [comment]
Please report NestJS issues on NestJS repo:
https://github.com/nestjs/graphql

**Comment by luisbar180492** [comment]
I am facing the same error @nizulzaim, did you find a solution?
