### ISSUE TITLE
Module '"graphql/utilities/printSchema"' has no exported member 'Options'

### ISSUE THREAD

**Issue by jcuna** [MichalLytek/type-graphql#1135]
**Describe the Bug**
Upon following the installation guide here: https://typegraphql.com/docs/installation.html and copying/pasting the examples here: https://typegraphql.com/docs/getting-started.html. Yet just adding the following line to a index.ts file will throw this error for me when I run `tsc`

~~~
import {buildSchema} from 'type-graphql'
~~~
or
~~~
import {buildSchemaSync} from 'type-graphql'
~~~
Run tsc
~~~
> tsc

node_modules/type-graphql/dist/utils/emitSchemaDefinitionFile.d.ts:2:10 - error TS2305: Module '"graphql/utilities/printSchema"' has no exported member 'Options'.

2 import { Options as GraphQLPrintSchemaOptions } from "graphql/utilities/printSchema";

~~~

**To Reproduce**
import {buildSchemaSync} from 'type-graphql'

**Expected Behavior**
properly compile file

**Logs**
~~~
> tsc

node_modules/type-graphql/dist/utils/emitSchemaDefinitionFile.d.ts:2:10 - error TS2305: Module '"graphql/utilities/printSchema"' has no exported member 'Options'.

2 import { Options as GraphQLPrintSchemaOptions } from "graphql/utilities/printSchema";
           ~~~~~~~

Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! lucid-apiv2@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the lucid-apiv2@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

~~~
**Environment (please complete the following information):**

- OS: alpine3.14
- Node 14.17.3
- Package version 1.1.1
- TypeScript version 4.5.3

**Additional Context**
Like I said, I started following the examples as described above, yet currently the single line to import buildschema is throwing this error.

See my tsconfig.json below:
~~~
{
  "compilerOptions": {
    "strict": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "module": "CommonJS",
    "target": "ES2020",
    "lib": [
      "ES2020",
      "esnext.asynciterable"
    ],
    "outDir": "out",
    "strictPropertyInitialization": false,
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "tests"
  ]
}

~~~

**Comment by jcuna** [comment]
I understand that `type-graphql` is expecting the `graphql` package to export that module, I will try downgrading `graphql` since I'm using the latest version released 3 days ago.

**Comment by jcuna** [comment]
Downgrading graphql to `graphql@15.8.0` fixed the issue. I guess that this package needs to be updated to support latest graphql, or documentation should be updated to specify the latest supported version.

**Comment by MichalLytek** [comment]
> I'm using the latest version released 3 days ago.

Are you talking about v16?
You've ignored peer dependency warnings on install?

**Comment by jcuna** [comment]
1. yes
2. I did.

I just upgraded to v16 again to verify and there're indeed warnings which I totally ignored before. Is there a guide on how to deal with this as it's not very clear which dependencies specifically are required

**Comment by jcuna** [comment]
looking at the warnings in more details, all are basically indicating that they are not compatible with `graphql@16` so I guess there's still no path to upgrade to `graphql@16`

Thanks for pointing out the warnings.

**Comment by MichalLytek** [comment]
See #1100 🔒
