### ISSUE TITLE
loadResolversFromGlob doesn't return the modules found

### ISSUE THREAD

**Issue by kamikazePT** [MichalLytek/type-graphql#1147]
**Describe the Bug**

`buildSchema` loads every resolver there is even when using glob pattern, which isn't at all what I want when defining multiple schemas.

**To Reproduce**
 - Create 2 schemas in separate folders
 - Use the glob pattern on each buildSchema for the correct folder

**Expected Behaviour**
It should load each schema with its scoped resolvers

**Actual Behaviour**
Both schemas have all the resolvers from both of them

**Note**
Fixed in [#1148](https://github.com/MichalLytek/type-graphql/pull/1148)

**Comment by MichalLytek** [comment]
This is not a bug but a documented design choice:

![image](https://user-images.githubusercontent.com/10618781/147494643-0e888b6e-261f-4960-bf46-baee7a4e6208.png)

"or their dependencies" is the key - we can't change that without introducing breaking change for existing users.

Loading by glob was always cumbersome and will be removed in `v2.x`. 
All we can do for now is to deprecate it and mention in docs some custom solution for using glob with the standard approach of providing an array of resolver classes, like a function that loads modules by glob and returns exported items.
This way old users can still use old version while some advanced ones like you can benefit from the improved design.
