### ISSUE TITLE
"deprecated reason" does not appear in the SDL nor Apollo Studio when using deprecationReason in the @InputType

### ISSUE THREAD

**Issue by ren-suyama** [MichalLytek/type-graphql#1171]
**Describe the Bug**
When writing "deprecationReason" in the @InputType, I expected the word "deprecated reason" and the description to be shown in the SDL or Apollo Studio. On the other hand, "deprecated reason" appears when I use "deprecationReason" in the @ObjectType. Is there any way to show "deprecated reason" when using @InputType?

I hope this bug gets solved soon because we are using "deprecatedReason" when we have to change our schema drastically, and the frontend developers need this description so that the particular part will soon be changed.

**To Reproduce**

- Resolver and the @InputType
```
import { Arg, Field, InputType, Mutation, Resolver } from 'type-graphql';
import { FugaFuga } from '../entity';

@InputType()
class CreateHogeHogeInput {
  @Field({
    deprecationReason: 'testing whether deprecationReason appears',
    description: 'testing whether description appears',
  })
  hogehoge: string;
}

@Resolver()
export class CreateHogeHogeResolver {
  @Mutation(() => FugaFuga)
  async createHogeHoge(@Arg('input') createHogeHogeInput: CreateHogeHogeInput): Promise<FugaFuga> {
    const fugafuga = null;

    return fugafuga;
  }
}
```

- SDL generated using command "ts-node  genSchema.ts"
```
input CreateHogeHogeInput {
  """testing whether description appears"""
  hogehoge: String!
}
```

- Screenshot of Apollo Studio

![スクリーンショット 2022-01-14 16 57 18](https://user-images.githubusercontent.com/72198401/149471755-ba915cc2-bf59-47c5-830f-8f1ec5101580.png)

**Expected Behavior**
As @ObjectType shows deprecated reason like the one below:

```
type FugaFuga @key(fields: "id") {

  """testing whether description appears"""
  hogehoge: string @deprecated(reason: "testing whether description appears")

}
```

![スクリーンショット 2022-01-14 17 09 33](https://user-images.githubusercontent.com/72198401/149473375-1dff7083-87ba-4443-a96a-bc9bf651c3c6.png)

I expect @InputType to behave as followed too:

- SDL generated using command "ts-node  genSchema.ts"
```
input CreateHogeHogeInput {
  """testing whether description appears"""
  hogehoge: String! @deprecated(reason: "testing whether deprecationReason appears")
}
```

**Environment (please complete the following information):**

- OS: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
- Node: v14.16.0
- Package version: type-graphql : "version": "1.1.1"
- TypeScript version:  "typescript": "^4.1.3"

**Comment by MichalLytek** [comment]
Fixed long time ago:
https://github.com/MichalLytek/type-graphql/pull/795

Please upgrade to `v1.2-rc.1`
