### ISSUE TITLE
Injecting a @deprecated with Directive decorator with an object-type doesn't apply the deprecated SDL

### ISSUE THREAD

**Issue by MateusAndrade** [MichalLytek/type-graphql#1178]
**Describe the Bug**
Hi! I've been using type-graphql for a while, and when I started using `Directives` at my application I started facing some issues trying to deprecate specific types of my application.

If I use the `deprecateReason` available through some types, I'm able to generate the proper SDL pointing that the given type is deprecated. However, if I use the `@Directive` decorator applying an `@deprecated` SDL I'm unable to deprecate an ObjectType, Resolver, etc. Also, looking at the docs it says it is supported for ObjectTypes, Fields, and resolvers. 

**To Reproduce**
Giving this object type at an class: 

```ts
@Directive('@deprecated(reason: "Use newField")')
@ObjectType()
class Foo {
  @Field()
  bar: string;
}
```

It was expected to add an `@deprecated(reason: "Use newField")` at the type when looking through the Docs/SDL . However, this is not happening and it looks like the decorator is not injecting anything. Although, I didn't test this with other decorators/directives. 

A quick guide how to reproduce the bug.
You can paste here code snippets or even better, provide a link to the repository with minimal reproducible code example.

**Expected Behavior**
Proper inject the `deprecate` at ObjectTypes, Fields, etc.

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occurred.

**Environment (please complete the following information):**

- OS: Osx
- Node (14.7.3)
- Package version: 1.2.0-rc.1
- TypeScript version: 4.0.3

**Additional Context**

**Comment by MateusAndrade** [comment]
> Why using directives when you can do this natively?
> 
> ```ts
> @ObjectType({ deprecationReason: "Use newField" })
> class Foo {
>   @Field()
>   bar: string;
> }
> ```

It looks like the `deprecationReason` is not supported at `ObjectType`. 

```
No overload matches this call.
  Overload 1 of 3, '(options: ObjectTypeOptions): ClassDecorator', gave the following error.
    Argument of type '{ deprecationReason: string; }' is not assignable to parameter of type 'ObjectTypeOptions'.
      Object literal may only specify known properties, and 'deprecationReason' does not exist in type 'ObjectTypeOptions'.
  Overload 2 of 3, '(name: string, options?: ObjectTypeOptions | undefined): ClassDecorator', gave the following error.
    Argument of type '{ deprecationReason: string; }' is not assignable to parameter of type 'string'.ts(2769)
```

Also, looking at the `Directive` I wasn't able to found it extending the `Deprecate` interface. 

https://github.com/MichalLytek/type-graphql/blob/aeb68a5e684a069f08647ecb2d5ac2c77c7d0a55/src/decorators/ObjectType.ts#L5-L32

**Comment by MichalLytek** [comment]
So you get the answer - GraphQL specification does not allow deprecating types. You can only deprecate some fields of the types 😉

**Comment by MateusAndrade** [comment]
> So you get the answer - GraphQL specification does not allow deprecating types. You can only deprecate some fields of the types 😉

Hmmm...so what do you think about an update on the docs regarding this? Because with the current explanation it looks a little bit confusing since it's using the `@deprecated` as an example of a Directive: 

> Currently, you can use the directives only on object types, input types, interface types, and their fields or fields resolvers, as well as queries, mutations, and subscriptions. Other locations like scalars, enums, unions, or arguments are not yet supported.

Maybe, adding an explanation about the `deprecated` is available only to `Fields` instead of resolvers, etc?

**Comment by MichalLytek** [comment]
> Maybe, adding an explanation about the deprecated is available only to Fields instead of resolvers, etc?

TypeScript is self documenting - you can see there's no valid `deprecationReason` property for those decorators.

> Because with the current explanation it looks a little bit confusing since it's using the @deprecated as an example of a Directive:

Where do you see deprecated directive on top of an object type?
https://typegraphql.com/docs/directives.html

**Comment by MateusAndrade** [comment]
> > Maybe, adding an explanation about the deprecated is available only to Fields instead of resolvers, etc?
> 
> TypeScript is self documenting - you can see there's no valid `deprecationReason` property for those decorators.
> 
> > Because with the current explanation it looks a little bit confusing since it's using the @deprecated as an example of a Directive:
> 
> Where do you see deprecated directive on top of an object type? https://typegraphql.com/docs/directives.html

I agree with that about Typescript. But it can lead to some miss understanding since the docs use an: 

```
@Directive('@deprecated(reason: "Use newField")')
```

As an example showing how to use the directives. Also, when I tested injecting this at a `Field` it didn't work. Only using the `deprecateReason` would mark the given field as deprecated:

```ts
@ObjectType()
class Foo {
  @Directive("@lowercase")
  @Directive('@deprecated(reason: "Use `newField`")')
  @Directive("@hasRole(role: Manager)")
  @Field()
  bar: string;
}
```

Do you think a PR changing this would be a good idea? I think changing the basic example to use a hypothetical decorator instead of `@deprecated` would make things simple to understand looking at the docs. 😄
