### ISSUE TITLE
Support for mutation namespaces

### ISSUE THREAD

**Issue by dan-cooke** [MichalLytek/type-graphql#1219]
**Is your feature request related to a problem? Please describe.**
When developing with `type-graphql` you often notice your class files are growing absolutely enormous. 

**Describe the solution you'd like**
One cool paradigm is the use of mutation namepsaces https://graphql-rules.com/rules/mutation-namespaces.

This alows consumers of your graphql schema to go way beyond REST and instantly see what mutations are available for a given entity. 

**Describe alternatives you've considered**
I have tried to implement something like this within the framework. As follows:

```typescript
@Resolver(() => Portfolio)
class PortfolioResolver {
 @Mutation(() => PortfolioMutationNamespace)
  async mutatePortfolio(
    @Arg(`_id`, () => ObjectIdScalar)
    _id: ObjectId,
    @Ctx() { identity }: GraphQLContext,
  ) {
    const portfolio = await PortfolioModel.findById(_id);

    if (portfolio?.owner.sub !== identity.sub) {
      throw new AuthenticationError(
        `You do not have permission to update this portfolio`,
      );
    }

	// Return the namespace
    return new PortfolioMutationNamespace(_id);
  }
}

```

```ts
@Resolver(() => Portfolio)
export class PortfolioMutationNamespace {
  private _id: ObjectId;

  constructor(portfolioId: ObjectId) {
    this._id = portfolioId;
  }

  @Mutation(() => UpdatePortfolioPayload)
  async setName(@Arg(`name`) name: string) {}
}
```

But I get `Cannot read property 'getObjectType' of undefined` and error when building my schema.

It seems that a `@Mutation()` needs to return an `@ObjectType` and it currently does not support returning another `@Resolver` type.

If the library supported this use case, it would be awesome!

**Comment by MichalLytek** [comment]
Closing as rejected multiple time in #1045 #781 #712 #312 #64 etc. 🔒

**Comment by dan-cooke** [comment]
Apologies @MichalLytek  . 

I just saw a few of the previous issues after I posted this. You make some good points about namespaces... I wonder why it is recommended so highly on that GraphQL rules site.. 

Your point about parallel mutations is a no brainer.
