### ISSUE TITLE
Update Apollo Federation Code Example

### ISSUE THREAD

**Issue by linbudu599** [MichalLytek/type-graphql#1220]
**Describe the issue**
A clear and concise description of what is wrong or what feature is missing.
You may ask here for guides, e.g. "How to run TypeGraphQL on AWS Lamda?" if nobody helped you on Github Discussions or StackOverflow.

Current example about [Apollo Federation](https://github.com/MichalLytek/type-graphql/tree/master/examples/apollo-federation) is outdated, as Apollo team release new package called `@apollo/subgraph` for some specific operations which are included in `@apollo/federation` package.

The most important change is in [buildFederatedSchema](https://github.com/MichalLytek/type-graphql/blob/master/examples/apollo-federation/helpers/buildFederatedSchema.ts), it should be updated as below:

```typescript
import { specifiedDirectives } from 'graphql';
import { gql } from 'apollo-server';
import {
  KeyDirective,
  ExtendsDirective,
  ExternalDirective,
  RequiresDirective,
  ProvidesDirective,
  directivesWhichRequireUserProvidedDefinitions,
  TagDirective,
} from '@apollo/subgraph/dist/directives';
import { printSubgraphSchema } from '@apollo/subgraph/dist/printSubgraphSchema';
import { buildFederatedSchema as buildApolloFederationSchema } from '@apollo/federation';
import { addResolversToSchema, GraphQLResolverMap } from 'apollo-graphql';
import {
  buildSchema,
  BuildSchemaOptions,
  createResolversMap,
} from 'type-graphql';

export async function buildFederatedSchemaForTypeGraphQL(
  options: Omit<BuildSchemaOptions, 'skipCheck'>,
  referenceResolvers?: GraphQLResolverMap<any>
) {
  const schema = await buildSchema({
    ...options,
    directives: [
      ...specifiedDirectives,
      ...[
        KeyDirective,
        ExtendsDirective,
        ExternalDirective,
        RequiresDirective,
        ProvidesDirective,
        TagDirective,
      ],
      ...directivesWhichRequireUserProvidedDefinitions,
      ...(options.directives || []),
    ],
    skipCheck: true,
  });

  const federatedSchema = buildApolloFederationSchema({
    typeDefs: gql(printSubgraphSchema(schema)),
    resolvers: createResolversMap(schema) as any,
  });

  if (referenceResolvers) {
    addResolversToSchema(federatedSchema, referenceResolvers);
  }
  return federatedSchema;
}

``` 

**Are you able to make a PR that fix this?**
If you can, it would be great if you create a pull request that fixes the docs, fills the gap with new chapter or new code example.

Yes, I'd like to use code above as replacement, but please also validate it first.

**Additional context**

**Comment by MichalLytek** [comment]
The work has been done on the `v16` branch:
https://github.com/MichalLytek/type-graphql/blob/v16/examples/apollo-federation/helpers/buildFederatedSchema.ts

However, I cannot test that because apollo federation did not yet support GraphQL v16.

**Comment by MichalLytek** [comment]
Ah, it's done on the branch on my local, not pushed yet, sorry 😅
