### ISSUE TITLE
Authorization and custom Errors

### ISSUE THREAD

**Issue by atoy40** [MichalLytek/type-graphql#1221]
Hi,

It can be very useful to be able to return our own Error instances from the AuthChecker function instead of the harcoded ones.
I can do a PR if you agree vith the idea.

Anthony.

**Comment by MichalLytek** [comment]
You can easily build your own auth checking layer with middleware and a custom method decorator.

There you can throw any error you want.

**Comment by atoy40** [comment]
thanks @MichalLytek
