### ISSUE TITLE
GitHub sponsors missing in the members sections

### ISSUE THREAD

**Issue by itpropro** [MichalLytek/type-graphql#1224]
Currently only OpenCollective sponsors, not GitHub sponsors (https://github.com/TypeGraphQL) are updated in the README. As there are more sponsors on GitHub (at elast for member tier) and there is not much to see in regards to new code (as I understood, you currently develop the next version privately @MichalLytek), I think it would be a nice touch to have all the sponsors listed in the same place.

**Comment by MichalLytek** [comment]
You're right, I was thinking about it but forgot at some time when some contributors on GitHub sponsors appeared.

Do you know if I can somehow automatically display the financial contributors via a generated image, like open collective is able to do?

**Comment by itpropro** [comment]
There is a great toolkit for generating sponsor images by @antfu, which I have seen some people use (https://github.com/antfu/sponsorkit). I hope that helps as I don't have any experience in managing sponsors, only with sponsoring :)

**Comment by itpropro** [comment]
I think it would be best if you as repository and org owner decide which format and highlighting of different levels you prefer for your sponsors, implement that and integrate it into some CI pipeline for all of your projects.
The options seem pretty straight forward to automate that in a very little time.

**Comment by jahead** [comment]
@MichalLytek if no one is working on this, I think it would be a something I could play with on the weekend. #myweekendsarefun

**Comment by MichalLytek** [comment]
To myself: integrate with this tool: https://github.com/antfu/sponsorkit

**Comment by carlocorradini** [comment]
Working on PR #1400

**Comment by MichalLytek** [comment]
@carlocorradini can we extract this into a separate PR? I would like to play with this in a quicker manner than the rest of this 1400 PR 😉

**Comment by carlocorradini** [comment]
@MichalLytek Copy the changes made in another PR and revert them to avoid conflicts.

**Comment by carlocorradini** [comment]
@MichalLytek 
I'm thinking about two options:
1. Single image with all sponsors
2. Multiple images (similar to what we have now) under the corresponding MD title/subtitle

**Comment by MichalLytek** [comment]
@carlocorradini We need multiple images like we have now. We have different sponsor tiers, we can't have all together 😛 

Also sponsors should be clickable with link to ther website. So maybe we should use this tool only to generate image for gihub backers?

**Comment by carlocorradini** [comment]
@MichalLytek It's possible if you check the example on the site.
Unfortunately I can't try to generate the images due to che API keys required :/

**Comment by MichalLytek** [comment]
@itpropro Please check the changes in sponsors section in readme and website 😉
