### ISSUE TITLE
catch incorrect relation name during compilation

### ISSUE THREAD

**Issue by hexdecimal16** [MichalLytek/type-graphql#1228]
Is there a way to catch incorrect relation name during compilation as it's highly inconvinent if it breaks on deployment or testing

eg:
```
DealerVehicleMapping.find({
      where: { dealer: { id: dealerId }, vehicleModel: { id: vehicleId } },
      relations: ["dealer", "vehicleModel"],
    });
```

if there is some typo in dealer or vehicle model entity names it creates problem these kind of bugs should ideally be detected on compilation.

**Comment by MichalLytek** [comment]
Wrong repo?
