### ISSUE TITLE
Instance of custom AuthChecker

### ISSUE THREAD

**Issue by FatsharkGo** [MichalLytek/type-graphql#1253]
**Is your feature request related to a problem? Please describe.**
The mechanism of custom authorization check is awesome for a formal production application, but in the real world the custom `AuthCheck`  usually has its own configurations and status data, however the framework cannot deal with instance of custom autchchecker.

**Describe the solution you'd like**
Option `authChecker` of `buildSchema()` should accept an instance, like this:

```ts
class CustomAuthChecker implements AuthCheckerInterface {
  oaauth: string;
  key: string;

  constructor(oaauth: string, key: string) {
    this.oaauth = oaauth;
    this.key = key;
  }

  check({root, args, context, info}: REsolverData, roles: string[]) {
    // ...
  }
}

const schema = await buildSchema({
  // ...
  authChecker: new CustomAuthChecker(oaauth, key, ...),
  // ...
});
```

**Describe alternatives you've considered**
N/A

**Additional context**
I traced the code of the framework, maybe do some type guard in function `AuthMiddleware()` can fix this.

```ts
function isAuthChecker(object: any): object is AuthChecker {
  return 'check' in object;
}

export function AuthMiddleware(
  authChecker: AuthChecker<any, any>,
  container: IOCContainer,
  authMode: AuthMode,
  roles: any[],
): MiddlewareFn {
  return async (action, next) => {
    let accessGranted: boolean;

    // if(isAuthChecker(authChecker) { ...}

    if (authChecker.prototype) {
      const authCheckerInstance = await container.getInstance(authChecker, action);
      accessGranted = await authCheckerInstance.check(action, roles);
    } else {
      accessGranted = await (authChecker as AuthCheckerFn<any, any>)(action, roles);
    }

}
```

**Comment by MichalLytek** [comment]
Class interface is intended only for working with dependency injection.
Passing custom parameters in constructor is forbidden.
```ts
const customAuthChecker = new CustomAuthChecker(oaauth, key, ...);
const schema = await buildSchema({
  // ...
  authChecker: (...args) => customAuthChecker.check(...args),
  // ...
});
```

**Comment by FatsharkGo** [comment]
Thanks for your detailed reply with code snipppets, it works for my project.
