### ISSUE TITLE
Having same named query and field resolver

### ISSUE THREAD

**Issue by itpropro** [MichalLytek/type-graphql#1272]
I am currently migrating a customers GraphQL schema to TypeGraphQL and they have a lot of classes that have fields with the same name. For example you have a `books` class that also contains a field called `books`. You would then have something like this (simplified):
```
@Resolver(() => Book)
export class BookResolver {
  @Query(() => [Book], { nullable: "items" })
  async books(
    @Ctx() context: Context,
    @Info() info: GraphQLResolveInfo,
    @Arg("name", { nullable: true, defaultValue: "" }) name?: string,
    ...
  ) {
    try {
      return await context.dataSources.booksApi.getBooks(
        { name, isAddOn, isTrial, limit, offset, sort },
        info.cacheControl.cacheHint
      );
    } catch (error) {
      throw new ApolloError(
        "Sorry, we are having problems fetching your books",
        "BOOKS"
      );
    }

  @FieldResolver(() => [Book])
  async books(
    @Ctx() context: Context,
    @Info() info: GraphQLResolveInfo,
    @Root() book: UnresolvedBook,
  ) {
    return await context.dataSources.booksApi.getBookBooks(
      book.books,
      info.cacheControl.cacheHint
    );
  }
}
```

This would not be possible, because of the duplicated function implementation. As it's not possible to change field names in the project, what would be the working way in TypeGraphQL to implement a Query and a FieldResolver with the same name? Inline resolvers are not possible, as there are side effects like the interaction with the `context.dataSources` objects.

**Comment by russell-dot-js** [comment]
@itpropro put them in two different files or classes and you'll be good to go

e.g.
```
export class QueryResolver {
 @Query
 books() {}
} 

@Resolver(() => Book)
export class BooksResolver {
  @Fieldresolver(() => [Book])
  books() {}
}
```

**Comment by MichalLytek** [comment]
```ts
@FieldResolver(() => [Book], { name: "books" })
async getBooksofBook(...)
```

**Comment by itpropro** [comment]
> ```ts
> @FieldResolver(() => [Book], { name: "books" })
> async getBooksOfBook(...)
> ```

Hi @MichalLytek,
thanks for you reply, can you please explain the above lines? If I get it right, it's possible to override the name that gets written in the schema with the `name` field of the `options` object. I tried to find that in the documentation, can you post the explanation or link to the documentation for reference please?
