### ISSUE TITLE
`addResolversToSchema` example no longer functional after Apollo update

### ISSUE THREAD

**Issue by dobrynin** [MichalLytek/type-graphql#1274]
**Describe the issue**
The Apollo Federation example no longer works as written in this file: https://github.com/MichalLytek/type-graphql/blob/master/examples/apollo-federation/helpers/buildFederatedSchema.ts

Apollo has changed how `__resolveReference` works and has improved support for Directives in a federated graph. Issues discussed in https://github.com/MichalLytek/type-graphql/pull/369 can likely be dealt with now.

See here for the discussion in the federation repo about this issue: https://github.com/apollographql/federation/pull/1747

**Are you able to make a PR that fix this?**
I currently don't have enough understanding of type-graphql internals to propose a specific code change for this. At a minimum we can update the sample code to use the workaround discussed in the Federation repo (all this involves is changing where `addResolversToSchema` is imported from).

**Comment by MichalLytek** [comment]
This is part of examples, documentation not a core code. It's highly possible that it might be outdated and does not work with the latest version. I will do my best to update it along with the v16 branch.

**Comment by dobrynin** [comment]
Thanks @MichalLytek! Appreciate your excellent work on this library.

**Comment by MichalLytek** [comment]
Closed by #1331 🔒
