### ISSUE TITLE
Vulnerability in busboy can't be mitigated without TypeGraphQL supporting graphql 16

### ISSUE THREAD

**Issue by ramonsnir** [MichalLytek/type-graphql#1290]
I am aware that there is a general long-term effort to upgrade TypeGraphQL to support graphql 16.

`busboy<1.0` has a vulnerability that's coming from an ancient dependency (dicer). graphql-upload depends on `busboy<1.0` and as of Friday has a version (`graphql-upload=15`) that depends on `busboy>=1.6`. However, graphql-upload now requires `graphql>=16.3`, which isn't supported when using TypeGraphQL.

This leads to a situation, where I understand it, where TypeGraphQL is blocking the resolution of vulnerability.

First, I'm bringing this up in case you weren't aware yet, @MichalLytek .
Second, is there any way we can help with adding support for graphql 16? I see that there were several rejected PRs for this so naturally, I won't try to open yet another one. Is there a different way we can help? Working hands? Sponsorship?

**Comment by MichalLytek** [comment]
I have really busy weeks so that I even barely have time to answer questions on GitHub. But it's only temporary, I will be back in the second half of June and will do my best to releaase v2.0 RC1 with v16 support ASAP. Please stay tuned! 📻 

Closing this as duplicate of #1100 🔒
