### ISSUE TITLE
@oneOf directive

### ISSUE THREAD

**Issue by JamieS1211** [MichalLytek/type-graphql#1302]
I would like to use the @oneOf directive as discussed in issue #698 to effectively let me use a union in an input type but I can't work out how to do this / if it is possible with the decorators.

**Comment by MichalLytek** [comment]
Is this directive a part of the official GraphQL spec yet?

**Comment by JamieS1211** [comment]
Well this is embarrassing, I didn't actually check that. When I saw it discussed 2 years ago made an assumption. My apolagies.
