### ISSUE TITLE
Union types can't be made nullable

### ISSUE THREAD

**Issue by rmagon** [MichalLytek/type-graphql#1344]
**Describe the Bug**
I have a union type that I'm trying to make nullalbe, but even if I make it nullable, it still stays mandatory.

**To Reproduce**
1. Create a union type, like in the docs
```
import { createUnionType } from "type-graphql";

const SearchResultUnion = createUnionType({
  name: "SearchResult", // the name of the GraphQL union
  types: () => [Movie, Actor] as const, // function that returns tuple of object types classes
});
```

2. Use it as a field, and try to make it nullable
```
  @Field((type) => SearchResultUnion || null, { nullable: true })
  result?: typeof SearchResultUnion | null;
```

Result will always be mandatory

**Expected Behavior**
In this case, result should be a nullable field.

**Environment (please complete the following information):**

- OS: MacOS Monterey Version 12.5.1
- Node v16.14.0
- Package version 1.1.1
- TypeScript version 4.3.5

**Comment by MichalLytek** [comment]
Sorry, but I'm unable to reproduce the issue:
```ts
@ObjectType()
class ObjectUnion {
  @Field(type => OneTwoThreeUnion)
  unionField: typeof OneTwoThreeUnion;

  @Field(type => OneTwoThreeUnion, { nullable: true })
  nullableUnionField?: typeof OneTwoThreeUnion | null;
}
```
```ts
console.log(printType(schema.getType("ObjectUnion")!));
```
```
console.log
    type ObjectUnion {
      unionField: OneTwoThreeUnion!
      nullableUnionField: OneTwoThreeUnion
    }
```

**Comment by MichalLytek** [comment]
For future reference:

This is invalid syntax:
`@Field((type) => SearchResultUnion || null, { nullable: true })`

This is correct syntax:
`@Field((type) => SearchResultUnion, { nullable: true })`
