### ISSUE TITLE
Using @Field's option `name` on InputType's field completely removes that field from input object

### ISSUE THREAD

**Issue by Nickolai-developer** [MichalLytek/type-graphql#1346]
**Describe the Bug**
Input object missing renamed fields

**To Reproduce**

Create `InputType`, define property and rename this property with `name` `@Field`'s attribute.

Visual demo:
![image](https://user-images.githubusercontent.com/52446861/188646025-f5772eb3-97c1-4da1-a93d-1bb4e2817195.png)

**Expected Behavior**
Expected to see `someField` property in `input` object at runtime, but as you can see on screenshot, there's only `id` field.

**Environment (please complete the following information):**

- OS: Debian 5.10.136-1 x86_64
- Node 18.1.0
- Package version 1.1.1
- TypeScript version 4.6.3

**Comment by MichalLytek** [comment]
The `name` option is not intended to use with `@InputType`, only with `@ObjectType`.

**Comment by nstylo** [comment]
> The `name` option is not intended to use with `@InputType`, only with `@ObjectType`.

May I ask why that is the case? I'd like to alias InputType Fields...

**Comment by MichalLytek** [comment]
Because mapping input fields require custom logic to do so - output is done by `graphql-js`. Input type fields don't have resolvers to hook on with this efficiently.
