### ISSUE TITLE
Participate in hacktoberfest 2022

### ISSUE THREAD

**Issue by itpropro** [MichalLytek/type-graphql#1356]
To participate in hacktoberfest and get the top 10, maybe 20 issue resolved this month, it would be great if a maintainer can add the `hacktoberfest` topic to the project and review and merge all open PRs until the end of October.
More information here: https://hacktoberfest.com

**Comment by MichalLytek** [comment]
I've added that topic a week ago. Is there anything else I should do? 🤔

**Comment by itpropro** [comment]
Thank you! Now it automatically appears as participant and PRs that are merged during October are counting towards contributors and maintainers points in hacktoberfest 2022.
