### ISSUE TITLE
Installing version 1.1.1 doesn't gives all new features

### ISSUE THREAD

**Issue by ohad-artlist** [MichalLytek/type-graphql#1358]
**Describe the Bug**
I see that `master` code does matches `1.1.1` branch, but when installing `1.1.1` version I get an older code (For instance: `README.md` is not latest.

**To Reproduce**
1. Install the latest version
2. Try to import the new `buildTypeDefsAndResolversSync` exported method
3. `buildTypeDefsAndResolversSync` doesn't exist (even when search it inside `dist` folder.

**Expected Behavior**
Installing the latest version of `1.1.1`.

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occurred.

**Environment (please complete the following information):**

- OS: MacOS Monterey 12.6
- Node 16.x.x
- Package version 1.1.1
- TypeScript version 4.4.2

**Additional Context**
Latest code exists when installing `v1.2.0-rc1`.

**Comment by carlocorradini** [comment]
Take a look at [CHANGELOG.md](https://github.com/MichalLytek/type-graphql/blob/master/CHANGELOG.md).
You can see that the `sync` version of `buildTypeDefsAndResolvers` is in `v1.2.0-rc.1` (on `npm` is tagged as `next` where `v1.1.1` is tagged `latest` which corresponds to the default one when you install it with `npm install type-graphql`).
Therefore, you must install `type-graphql` specifying that you want the `next` version: 
```console
npm install --save type-graphql@next
```

**Comment by carlocorradini** [comment]
@ohad-artlist Can we close this?
