### ISSUE TITLE
Abstract types with mercurius federation

### ISSUE THREAD

**Issue by ramiel** [MichalLytek/type-graphql#1359]
**Describe the Bug**
I'm trying to use type-graphql within the context of a federation done with graphql. I need to create a schema that is compatible with the federation spec and I'm using a custom function to do so. I cannot use any apollo helper, so here my solution (not entirely the real code, just an extract)

```ts
import { printSchemaWithDirectives as printSchema } from '@graphql-tools/utils';
import { specifiedDirectives, GraphQLFieldResolver, GraphQLScalarType, 
  GraphQLString, GraphQLNonNull, GraphQLDirective, DirectiveLocation, GraphQLSchema, 
} from 'graphql';
import {
  buildSchema,
  createResolversMap,
  BuildSchemaOptions,
} from 'type-graphql';

// Specified in the same file, omitted for brevity
const federationDirectives = [
  KeyDirective,
  ExtendsDirective,
  ExternalDirective,
  // RequiresDirective,
  ProvidesDirective,
];

export const patchSchemaExtensions = (schema: GraphQLSchema): string =>
  printSchema(schema)
    .replace('type Query {', 'type Query @extends {')
    .replace('type Mutation {', 'type Mutation @extends {')
    .replace('type Subscription {', 'type Subscription @extends {');

async function buildFederatedSchema(
  options: Omit<BuildSchemaOptions, 'skipCheck'>,
): Promise<FederatedSchemaResult> {
  const schema = await buildSchema({
    ...options,
    skipCheck: true,

    directives: [
      ...specifiedDirectives,
      ...federationDirectives,
      ...(options.directives || []),
    ],
  });

  const federatedSchema = patchSchemaExtensions(schema);

  return {
    schema: federatedSchema,
    resolvers: createResolversMap(schema) as GraphQLResolverMap,
    _graphqlSchema: schema,
  };
}
```

So, I use it like this

```ts
const { schema, resolvers } = await buildFederatedSchema({
    // ... all my resolvers and so on
 });

app.register(async (app) => {
  app.register(mercurius, {
    schema: schema,
    resolvers,
    federationMetadata: true,
    allowBatchedQueries: true,
    // ...other options
  });
});
```

This works and the gateway is able to recognise all my graphql universe. What is not working are my abstract types. The problem is that graphql looks for `resolveType` function but inside resolver that function is named `__resolveType`.
My current solution is to generate a schema good for the federation gateway, but use instead the normal schema into local mercurius. 
I'm not sure what I can provide more to make this issue clear, so I'm happy to collaborate to sort this out.
Also, I'm probably doing some mistake in creating the schema for the federation, in that case I apologize 😄 

**Environment (please complete the following information):**

- OS: MacOS (but not relevant)
- Node 16
- Package version 1.2.0-rc.1
- TypeScript version 4.8.4

**Comment by carlocorradini** [comment]
I suppose you are using Apollo Federation V2. 
Have you seen the [updated version](https://github.com/MichalLytek/type-graphql/blob/new-major-release/examples/apollo-federation/helpers/buildFederatedSchema.ts) on how to build a federated schema? 
Nevertheless, I think not relying on [@apollo/subgraph](https://www.npmjs.com/package/@apollo/subgraph) and obtain a working federation can be really, (really) hard to accomplish

**Comment by ramiel** [comment]
I haven't tried actually. This version looks much efficient than the previous one and doesn't use too much of apollo. I'll have a try next week, thank you

**Comment by ramiel** [comment]
I had some time to try it this morning and the new code is not working, giving me this error

```
TypeError: Cannot read properties of undefined (reading 'QUERY')
    at Object.<anonymous> (/[...]/node_modules/@apollo/federation-internals/src/graphQLJSSchemaToAST.ts:26:50)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module._compile (/[...]/node_modules/source-map-support/source-map-support.js:568:25)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at require.extensions..jsx.require.extensions..js (/private/var/folders/4_/z49903r50q1418nkp5ttcypm0000gn/T/ts-node-dev-hook-05562729762978713.js:114:20)
    at Object.nodeDevHook [as .js] (/[...]/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

Maybe this code works only with graphql v16?

**Comment by carlocorradini** [comment]
@ramiel 
Yes, you are right.

[V2.0](https://github.com/MichalLytek/type-graphql/pull/1331) is on the way.

If you really want to use `Apollo Federation V2` you must have a separate package with `graphql >= 16` and then import it in your main project with `graphql < 16`. If you don't do something crazy, it works flawlessly. Take a look at my example [here](https://github.com/carlocorradini/reCluster/blob/ee1f263dc68311bcc2ebf02e887b1e97ceddd670/backend/packages/helpers/src/buildFederatedSchema.ts).
 \
\
\
*Ciao dall'Italia* 👋

**Comment by ramiel** [comment]
Yep. I need to wait for type-graphql that supports v16. I'm waiting for it in any case for other thousand reasons.

Ciao

**Comment by ramiel** [comment]
ok, now that version 2 is (almost) out I tried the new implementationto build a federated schema. This is not working either, because if I have two services and each build its own federated schema, the error is `GraphQLError: Field "Query._entities" can only be defined once`

**Comment by carlocorradini** [comment]
> ok, now that version 2 is (almost) out I tried the new implementation to build a federated schema. This is not working either, because if I have two services and each build its own federated schema, the error is `GraphQLError: Field "Query._entities" can only be defined once`

Can you share the code?

**Comment by ramiel** [comment]
I use it in another part of the app that prints the schema to a file, but as you can see it does nothing. Also, ?m not using that file at the moment, I just loading the SDL directly from the running service. So you can ignore it

**Comment by ramiel** [comment]
So, the code that you see is copy/pasted from that branch. type-graphql is at version 2.0.0-beta1 and graphql at version 16.6
I'm wondering where those directives are coming from.

**Comment by carlocorradini** [comment]
@ramiel 
You wrote: *It looks these directives create the problem. I have another service that do not print the directives in the schema*
All services **must** have the required directives in the generated schema (see [this](https://www.apollographql.com/docs/federation/federated-types/federated-directives) for more information).
It's the task of the gateway/router to compose them into a single schema.

**Comment by carlocorradini** [comment]
> So, the code that you see is copy/pasted from that branch. type-graphql is at version 2.0.0-beta1 and graphql at version 16.6 I'm wondering where those directives are coming from.

From `import { buildSubgraphSchema } from '@apollo/subgraph'`

**Comment by ramiel** [comment]
I see. I'm using mercurius gateway as gateway. Mercurius is complaining about the presence of `@`.

**Comment by ramiel** [comment]
I also feel it's not the directive itself, but the schema is somehow wrong (from the perspective of mercurius)

**Comment by ramiel** [comment]
What's weird is that this schema is produced by mercurius itself, as you can see by my code!

**Comment by carlocorradini** [comment]
I've never used Mercurius.
It's possible that (currently) doesn't support Apollo Federation v2?

**Comment by ramiel** [comment]
I just asked @mcollina about this: https://github.com/mercurius-js/mercurius/issues/897

**Comment by ramiel** [comment]
Mystery solved, mercurius doesn't support federation v2. Thanks for your help
