### ISSUE TITLE
Should able to use TypeGraphQL with Tsyringe

### ISSUE THREAD

**Issue by leandroluk** [MichalLytek/type-graphql#1398]
**Describe the issue**
I have a project using DI with [tsyringe](https://www.npmjs.com/package/tsyringe) and i should to add graphql using type-graphql, but in documentation is only listed the TypeDI as a dependency injection lib

**Are you able to make a PR that fix this?**
If is possible to use Tsyringe, plesse add some example in doc's

**Additional context**
N/A

**Comment by MichalLytek** [comment]
Tsyringe works well for TypeGraphQL projects. What have you tried and what was not working for you?

**Comment by carlocorradini** [comment]
Yes, it's possible! \
Most IOC containers have the `get` function to retrieve an instance of the given class type. `tsyringe` instead have the `resolve` function. \
Therefore, you have to change the `container` option when building the schema to instruct `type-graphql` how to retrieve (*get*) a class instance from a class type:

```ts
import { container } from 'tsyringe';

const schema = await buildSchema({
  // ...
  container: { get: (cls) => container.resolve(cls) }
});
```

**Comment by carlocorradini** [comment]
@leandroluk Can we close this?

**Comment by fknop** [comment]
> Yes, it's possible! Most IOC containers have the `get` function to retrieve an instance of the given class type. `tsyringe` instead have the `resolve` function. Therefore, you have to change the `container` option when building the schema to instruct `type-graphql` how to retrieve (_get_) a class instance from a class type:
> 
> ```ts
> import { container } from 'tsyringe';
> 
> const schema = await buildSchema({
>   // ...
>   container: { get: (cls) => container.resolve(cls) }
> });
> ```

I can confirm this work, using tsyringe and typegraphql in a large production project :)

**Comment by clayrisser** [comment]
How to register the resolvers with tsringe? I get the following error.

```
TypeInfo not known for "AuthResolver"
```

**Comment by carlocorradini** [comment]
@clayrisser 
See [tsyringe example](https://github.com/MichalLytek/type-graphql/tree/master/examples/tsyringe).

@MichalLytek I think we can close this
