### ISSUE TITLE
AuthChecker receiving undefined in all parameters

### ISSUE THREAD

**Issue by skhaz** [MichalLytek/type-graphql#1403]
**Describe the Bug**
Custom `AuthChecker` is receiving undefined in all parameters.

**To Reproduce**
Create a schema

```javascript
const schema = await buildSchema({
    resolvers: [UserResolver, PostResolver],
    emitSchemaFile: true,
    validate: false,
    authChecker,
  })
```

Create a custom authChecker

```javascript
export const authChecker: AuthChecker<Context> = (root, f) => {
  console.log('>>> root', JSON.stringify(root))
  console.log('>>> f', JSON.stringify(f))
  return true
}
```

Populate the context

```shell
  const { url } = await startStandaloneServer(server, {
    context: async ({ req }) => {
      try {
        const token = req.headers.authorization || ''

        const { id } = jwt.verify(token, JWT_SECRET) as JwtDecoded

        return { user: await UserModel.findById(id) }
      } catch {
        return {}
      }
    },
    listen: { port: 3000 },
  })
```

Observe in the logs the undefined value

```shell
grapqlgram-app-1    | >>> root undefined
grapqlgram-app-1    | >>> f undefined
```

**Expected Behavior**
Have a valid context.

**Environment**

- OS: Linux and macOS
- Node 18
- Package version 2.0.0-beta.1
- TypeScript version 4.9.4

**Additional Context**
It used to work on the latest stable version

**Comment by MichalLytek** [comment]
Can you create a PR with a failing test case? I think there might be an issue in your setup.

**Comment by skhaz** [comment]
@MichalLytek, for sure, I will do that. Thanks

**Comment by skhaz** [comment]
After some further investigation, I think the problem is with Apollo startStandaloneServer. It is not passing the context forward.

**Comment by skhaz** [comment]
I built a minimal-reproducible example[1] and could confirm the issue.

I built a minimal-reproducible example and could confirm the issue.

Now I need to figure out where I can help. I suppose this was an issue with Apollo or with type-graphql. It used worked before upgrading the libraries.

1 - https://github.com/skhaz/graphql-auth

**Comment by MichalLytek** [comment]
Apollo Server v4 has a new way to pass the context. Make sure you follow their docs.

**Comment by skhaz** [comment]
Thank you and have an awesome holidays

**Comment by skhaz** [comment]
@MichalLytek I have found the problem.

It is needed to use target es2018 in compilerOptions.

With this, both libraries work fine.
