### ISSUE TITLE
ERROR Error: Cannot determine a GraphQL output type for the "id". Make sure your class is decorated with an appropriate decorator.

### ISSUE THREAD

**Issue by jithunaico** [MichalLytek/type-graphql#1424]
**Describe the Bug**

**To Reproduce**
A quick guide how to reproduce the bug.
You can paste here code snippets or even better, provide a link to the repository with minimal reproducible code example.

**Expected Behavior**

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occurred.

**Environment (please complete the following information):**

- OS: [e.g. Windows]
- Node (e.g. 10.5.0)
- Package version [e.g. 0.12.2] (please check if the bug still exist in newest release)
- TypeScript version (e.g. 2.8.2)

**Additional Context**

**Comment by carlocorradini** [comment]
What is happening here 😂😅
