### ISSUE TITLE
createParamDecorator accepts async function and awaits before passing resloved by promise value to resolver.

### ISSUE THREAD

**Issue by valerii15298** [MichalLytek/type-graphql#1438]
**Describe the issue**
Currently, as I just tested `createParamDecorator` accepts *async* function like this:
```ts
function SomeResolvedValue(): ParameterDecorator {
  return createParamDecorator(async () => {
    return await Promise.resolve(10);
  });
}
```

And in resolver we can use it like this:
```ts
async updateUserRole(
    @SomeResolvedValue() value: number // note that it is number and not a Promise<number>
) {
  console.log(value) // value is a number 10 here
}
```
It means that `type-graphql` awaits all parameter decorators before passing them to type-graphql resolvers.
It is quite cool feature but it is never mentioned in the docs for [*Parameter decorator*](https://typegraphql.com/docs/custom-decorators.html#parameter-decorators)

**Are you able to make a PR that fix this?**
I am not sure how to describe it in the best way in the docs. But I think it could be helpful for other people.

Also since it is not documented in the docs I have a question: are there any pitfalls when using it like that?

**Comment by MichalLytek** [comment]
> are there any pitfalls when using it like that?

Async makes things always slower 😉 But since the value is awaited anyway, you can use it if you want!

**Comment by valerii15298** [comment]
Thank you! Yes you are right. But I need to await it first always in every resolver before doing anything else like that:
```ts
export function KeycloakAdmin(): ParameterDecorator {
  return createParamDecorator(async () => {
    await refreshKeycloakTokenIfExpired();
    return keycloakAdminClient;
  });
}
```
I need to do it anyway and the approach with the decorator is very useful since I do not need to repeat the same code in every resolver :)

**Comment by MichalLytek** [comment]
Ok so there's no `await` in the TypeGraphQL part, it just injects what your returns - in this case it's a `Promise` 😉 

So I don't think if we should expose such edge cases in the docs, they would be hard to read 😕

**Comment by valerii15298** [comment]
@MichalLytek actually as I tested no. From param decortor I return a Promise(see example above). But type-graphql injects the *result* of the `Promise` NOT the `Promise` itself.

**Comment by MichalLytek** [comment]
Sorry, I was mistaken by your sentence "But I need to await it first always in every resolver before doing anything else" 😵

**Comment by MichalLytek** [comment]
Looks like there was a test case for async `createParamDecorator`. So it was safe to just update the docs, which I did in 158bfe5 🔒
