### ISSUE TITLE
Does not work with class-validator 0.14.0

### ISSUE THREAD

**Issue by Martomate** [MichalLytek/type-graphql#1443]
**Describe the Bug**
When `TypeGraphQL 1.1.1` is used together with `class-validator 0.14.0` the TypqGraphQL validation stops working (it crashes).

This happens in [the validate-args file](https://github.com/MichalLytek/type-graphql/blob/ddfc3ff14d6c11acb39bae15b7967b6c7af71ee2/src/resolvers/validate-arg.ts) and the reason is most likely that there was a breaking change in class-validator 0.14.0 (see [here](https://github.com/typestack/class-validator/blob/develop/CHANGELOG.md)). All my integration tests work with class-validator 0.13.2, but most of them fail with 0.14.0.

**To Reproduce**

Create a resolver with a mutation that takes this input:

```ts
@InputType()
export class SaveCredentialsInput {
  @Field()
  username!: string

  @Field()
  password!: string
}
```

This is what is returned to the API caller:

```json
{
  "message": "Argument Validation Error",
  "locations": [
    {
      "line": 3,
      "column": 9
    }
  ],
  "path": ["saveCredentials"],
  "extensions": {
    "code": "INTERNAL_SERVER_ERROR",
    "exception": {
      "validationErrors": [
        {
          "target": {
            "username": "test",
            "password": "test"
          },
          "children": [],
          "constraints": {
            "unknownValue": "an unknown value was passed to the validate function"
          }
        }
      ],
      "stacktrace": [
        "Error: Argument Validation Error",
        "    at Object.validateArg (/app/node_modules/type-graphql/dist/resolvers/validate-arg.js:29:15)",
        "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "    at async Promise.all (index 1)"
      ]
    }
  }
}
```

For some reason TypeGraphQL uses class-validator without specifying it as a dependency, so I was quite surprised to find this incompatibility.

**Comment by carlocorradini** [comment]
See https://github.com/MichalLytek/type-graphql/issues/1397

**Comment by MichalLytek** [comment]
Closing as duplicate #1396 #1401 🔒

**Comment by mmmeff** [comment]
Is there still a security risk here with class-validator?

**Comment by MichalLytek** [comment]
With GraphQL I guess not, it has own type system, fields validation and you can't put values not present in schema.

**Comment by aikr-trifork** [comment]
> See #1397
> 
> Using `class-validator >=0.14.0`:
> 
> ```ts
> const schema = await buildSchema({
>   // ...
>   validate: { forbidUnknownValues: false } // <--
> });
> ```

Thanks, that that worked for me
