### ISSUE TITLE
Documentation specifies commentDescriptions option that no longer exits

### ISSUE THREAD

**Issue by itay-grudev** [MichalLytek/type-graphql#1457]
The documentation for [`2.0.0-beta.1`][1] specifies an option `commentDescriptions` in the [Emitting the schema SDL][1], that doesn't seem to exist anymore.

As far as I can see it was deleted in this commit: https://github.com/MichalLytek/type-graphql/commit/8a52cbfd29de97adb0c4fc59bcdefb301e6eff7b

Can it be corrected or am I doing something wrong?

[1]: https://github.com/MichalLytek/type-graphql/blob/v2.0.0-beta.2/docs/emit-schema.md

**Comment by MichalLytek** [comment]
Fair point. Fixed in 75f865a 🔒
