### ISSUE TITLE
default value of validate property in buildSchemaOptions is not as same as described in documentation

### ISSUE THREAD

**Issue by Ian-sc-Kang** [MichalLytek/type-graphql#1471]
**Describe the issue**
there is a discrepancy between the documentation and the code. please see the screenshot below

what documentation says below 👇
![image](https://github.com/MichalLytek/type-graphql/assets/87746894/f3f71cd5-5b4a-4da5-a756-f8adfbd41988)

what actual codes look below 👇
![image](https://github.com/MichalLytek/type-graphql/assets/87746894/db25c007-ada0-4d16-9874-bce3be9a2c59)

**Are you able to make a PR that fix this?**
I could create a PR for this but not sure which value you want to start with

**Additional context**
N/A

**Comment by MichalLytek** [comment]
Same reason as #1472 🔒
