### ISSUE TITLE
isAbstract property doesn't not exist in Resolver() decorator option as opposed to what the documentation says

### ISSUE THREAD

**Issue by Ian-sc-Kang** [MichalLytek/type-graphql#1472]
**Describe the issue**
when trying to create a base resolver abstract class following the document, the typescript throws an error that says `isAbstract`  does not exist and actual code also doesn't provide the options for that. so the update on document seems needed. however, the inheritance seems working without `isAbstract` option!

what document says 👇
![image](https://github.com/MichalLytek/type-graphql/assets/87746894/e4f682a5-b11f-4e83-b72c-44e707907ca2)

what actual codes look 👇
![image](https://github.com/MichalLytek/type-graphql/assets/87746894/dc08865c-5dcd-41c5-ac42-ddc1cae07bb0)

**Are you able to make a PR that fix this?**
only document needs to be updated along with the code

**Additional context**
None

**Comment by MichalLytek** [comment]
Website shows docs for the latest release:

![image](https://github.com/MichalLytek/type-graphql/assets/10618781/5a4baadf-f008-487c-807b-e5d74da33c3d)

But you've installed latest beta release (v2.0.0-beta.2).
And haven't checked the release notes of that release.

What can I do more...

**Comment by Ian-sc-Kang** [comment]
Ahh i see! Thanks
