### ISSUE TITLE
Inflight is reported as vulnerability in type-graphql

### ISSUE THREAD

**Issue by Tringapps-Dharshan** [MichalLytek/type-graphql#1473]
Version
1.1.1

Description
vulnerability reported in inflight(last version was release in Oct 2016) package used by type-graphql, kindly let me know if there is a way to resolve this.

type-graphql (parent package)
--------- glob (dependency of type-graphql)
---------------inflight (dependency of glob)

Steps to reproduce
<img width="277" alt="image" src="https://github.com/MichalLytek/type-graphql/assets/102800724/bd8bbd54-abaa-4cfa-8f23-b3550c447282">

Expected behavior
No vulnerability in type-graphql

Actual behavior
Whitesource reported type-graphql 1.1.1 as vulnerable library.

- OS:  Windows
- Node 14.20.1
- TypeScript version 4.0.3

**Comment by MichalLytek** [comment]
By `npm audit fix`? Yarn resolutions?
If you do not use glob paths string for resolvers, the `glob` package is not used.

**Comment by Tringapps-Dharshan** [comment]
> By `npm audit fix`? Yarn resolutions? If you do not use glob paths string for resolvers, the `glob` package is not used.

I listed this tree structure by used the cmd npm list --depth=3, from this result you can able to see the glob deps used by the package type-graphql

**Comment by MichalLytek** [comment]
That's why I say, if you don't use `resolvers: ["./**/*.ts"]` glob string path, then the `glob` package is not called in real time, so it's not making any vunerability.

I don't have any plans for bumping deps of old versions.
So either use `npm audit fix` or `yarn resolutions` solutions or upgrade to `v2.0.0-beta.2` 😉

**Comment by Tringapps-Dharshan** [comment]
> That's why I say, if you don't use `resolvers: ["./**/*.ts"]` glob string path, then the `glob` package is not called in real time, so it's not making any vunerability.
> 
> I don't have any plans for bumping deps of old versions. So either use `npm audit fix` or `yarn resolutions` solutions or upgrade to `v2.0.0-beta.2` 😉

Thanks for your response. Issue resolved.
