### ISSUE TITLE
2.0.0-beta.3 breaks semver

### ISSUE THREAD

**Issue by chrisbruford** [MichalLytek/type-graphql#1495]
**Describe the issue**
The docs tell us that a beta version is the stable version
![image](https://github.com/MichalLytek/type-graphql/assets/19651170/4323f95a-1a65-49e2-b98c-3cb11f9a8307)

But beta.3 had 7 breaking changes out of 9 total changes listed in the release notes.

This immediatly breaks anyone use `^2.0.0-beta.2`

The last non-beta release was almost 3 years ago. Is it time to either release 2.0.0 or to change the docs to not suggest using an unstable beta as the release?

**Comment by carlocorradini** [comment]
@chrisbruford Good catch!

**Comment by MichalLytek** [comment]
Docusaurus does not support prereleases, so we can either hide this version at all so people does not now how to use new beta features or leave it as it is.

The beta is quite stable so i treat is as a default release for newcomers. Everyone should pick from the dropdown the used version to show docs related to that version.

This release does not break any semver and is published under a tag `@next`. So everything good on npm.
