### ISSUE TITLE
Version 2.0.0 emit schema docs example doesn't work

### ISSUE THREAD

**Issue by sclarke-rivian** [MichalLytek/type-graphql#1500]
Given the dist/build changes in the version 2 release candidates, this line does not work anymore. Is there a workaround?

https://github.com/MichalLytek/type-graphql/blob/f50d1d0af5b7b90d3d4b69c873188030f7740f48/website/versioned_docs/version-2.0.0-beta.3/emit-schema.md?plain=1#L49

**Comment by MichalLytek** [comment]
Docs upgraded, closing the issue 😉
