### ISSUE TITLE
Nested objects in queries

### ISSUE THREAD

**Issue by aaaltonen** [MichalLytek/type-graphql#1615]
I have query defined on my resolver like this:

`  @Query(() => User) user(@Arg("id") id: number) { return User.findOne({ where: { id, }, relations: { reservations: { user: true, }, announcements: true, role: true, uploadFiles: { roles: true, }, }, }); }`

And when im querying my api like this:
`query User($userId: Float!) { user(id: $userId) { id firstName lastName email phone role { name } uploadFiles { created_at displayName roles { name } }`

I get error: Cannot return null for non-nullable field Role.name. Im not sure what i'm doing wrong because that object contains "role" objects with data like "name" etc. I would really appreciate some assistance.

**Comment by MichalLytek** [comment]
[You've already asked in gh discussion](https://github.com/MichalLytek/type-graphql/discussions/1609). This is not a bug report and gh issues are not a helpdesk 🔒
