### ISSUE TITLE
Error when compiling with ESbuild (ESModule)

### ISSUE THREAD

**Issue by cjnoname** [MichalLytek/type-graphql#1664]
**Describe the Bug**
Error when compiling with ESbuild (ESModule)

Error details:
"Expected name to be a non-empty string."

We encountered an error while attempting to build the project with ESbuild Typescript (ESModule).

Simply add a basic resolver to the buildSchema function and you'll observe the error. You can reproduce it by following the links below. It's a straightforward setup.

https://eisenbergeffect.medium.com/an-esbuild-setup-for-typescript-3b24852479fe
https://github.com/thomaschaaf/esbuild-plugin-tsc#readme

**Comment by MichalLytek** [comment]
@carlocorradini can you take a look?

**Comment by carlocorradini** [comment]
I've never used ESBuild... I'm reading this:
![IMG_20240328_083211.jpg](https://github.com/MichalLytek/type-graphql/assets/21266147/f375f9ce-1ec0-4712-895d-9ab417640dd1)

**Comment by cjnoname** [comment]
> I've never used ESBuild... I'm reading this:
> 
> ![IMG_20240328_083211.jpg](https://private-user-images.githubusercontent.com/21266147/317636352-f375f9ce-1ec0-4712-895d-9ab417640dd1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMjI2MDQsIm5iZiI6MTcxMjAyMjMwNCwicGF0aCI6Ii8yMTI2NjE0Ny8zMTc2MzYzNTItZjM3NWY5Y2UtMWVjMC00NzEyLTg5NWQtOWFiNDE3NjQwZGQxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDAxNDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NDA2MDE0YmQyMjc5ZGYwMGU2MTYyMWQ4ZDcxMWJjNmFjMjc2MTYyMzE4YzM2NzA4NWZjNTgxY2NkM2M0MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CfKxHI7BmitOYaqvX96yw0oF1KXSLT9iBR7-UVb6pEc)
> 
> **Have you tried with `force: true` ?**

Hey mate, I tried but doesn't work.

**Comment by cjnoname** [comment]
@MichalLytek  Also I tried rollup, and it gives me this error:

The requested module 'type-graphql' does not provide an export named 'default'

I manually fixed this issue in the complied file, then it works, so it seems like type-graphql package does not support ESM properly.

**Comment by cjnoname** [comment]
Sorry my fault, please ignore my previous message

**Comment by carlocorradini** [comment]
@cjnoname Fixed?@@cjnoname Any update?

**Comment by cjnoname** [comment]
> @cjnoname Any update?

Hey man,

esbuild-plugin-tsc is something that I used at the beginning, but it doesn't work.

We also tried Rollup, but still had no luck and encountered a different error with graphql-yoga.

We have given up because it seems like this package supports TypeScript ESM but doesn't support the compiled TypeScript ESM. 

I hope that you guys can take a few minutes to create a TypeScript ESM project with this package and try to compile it with both esbuild and Rollup. Then you'll see the issues.

ESM is the future of NodeJS, and we will wait to move to ESM until your package fully supports it.

**Comment by MichalLytek** [comment]
I think this is not the package fault. It's the fault of 3rd party compilers that have issues with decorator metadata.
It would end up in the same way if you would use cjs and a 3rd party bundler.

**Comment by cjnoname** [comment]
> I think this is not the package fault. It's the fault of 3rd party compilers that have issues with decorator metadata. It would end up in the same way if you would use cjs and a 3rd party bundler.

I don't agree, bro. We've been using webpack for 7 years with CJS without any issues, same as Rollup. If the package uses the old CJS way to import the package or employs the ES5 method of exporting a module, then it won't compile correctly on ESM.

ESBuild might not support decorators properly, but Rollup does support them in a great way, yet it also gets stuck on the graphql-yoga package.

Additionally, I tried both and found that the typegraphql package seems to be the only one that could not be compiled across all the packages I am using. Both compilers throw errors and stop at this point.
