### ISSUE TITLE
Bug when the field and the field resolver has the same name

### ISSUE THREAD

**Issue by mjy9088** [MichalLytek/type-graphql#1699]
**Describe the Bug**

Say we have GraphQL ObjectType `Foo` with field `@Field((type) => Boolean) bar: boolean`, and its field resolver `@FieldResolver((returns) => Boolean, { nullable: true }) bar(): boolean | null { return null; }`.

Then, resulting schema is `type Foo { bar: Boolean! }`, but querying Foo::bar produces an error: `Cannot return null for non-nullable field Foo.bar.`

**To Reproduce**

<https://github.com/my-trash-bin/240531.git>

**Expected Behavior**

- Error should occurred on `buildSchema`
- Foo::bar should be `Boolean` instead of `Boolean!`
- ... or anything intuitive

**Logs**

```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Foo.bar.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "foo",
        "bar"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Cannot return null for non-nullable field Foo.bar.",
          "    at completeValue (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:605:13)",
          "    at executeField (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:500:19)",
          "    at executeFields (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:414:22)",
          "    at completeObjectValue (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:925:10)",
          "    at completeValue (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:646:12)",
          "    at completeValue (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:595:23)",
          "    at executeField (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:500:19)",
          "    at executeFields (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:414:22)",
          "    at executeOperation (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:344:14)",
          "    at execute (/Users/user/workspace/my-trash-bin/240531/node_modules/graphql/execution/execute.js:136:20)"
        ]
      }
    }
  ]
}
```

**Environment (please complete the following information):**

- OS: MacOS
- Node: 18.19.1
- Package version: 2.0.0-rc.1
- TypeScript version: 5.4.5

**Comment by MichalLytek** [comment]
Why do you want to declare the object type field to be non nullable and then overwrite it to make it nullable?

The internals work in a way that the field resolver info is ignored if the field is defined in object type class.
Only if there's no such field declared, it will use the field resolver info to register a new field.

**Comment by mjy9088** [comment]
I'm just now seeing this because it's buried in so many notifications, sorry.

I found this bug by mistake, and while it's not a fix I need, I'm just reporting it because I found it.

If it's not a bug and that's how it's supposed to work, I guess it doesn't matter! Thanks :)

**Comment by MichalLytek** [comment]
I guess I should add this to the list of errors in #12  - to tell user that you can't overwrite the type of field via field resolver.
Thanks for the report!
