### ISSUE TITLE
I hope I can share fields without specify Type

### ISSUE THREAD

**Issue by wenerme** [MichalLytek/type-graphql#1702]
**Is your feature request related to a problem? Please describe.**

I want to share ProfileFieldsMixinObject fields to InputType & ObjectType, I don't know which is the best practiese here, I hope thre is a decorator for middle class like `@ShareType`.

```ts
function detectType(obj: any) {
  return InputType
}

 function withProfileFields<TBase extends Constructor>(Base: TBase) {
  let Type = detectType(Base)
   
   // plan A
  @Type()
   // plan B
    // @InputType()
    // @ObjectType()
  class ProfileFieldsMixinObject extends Base {
    @Field(() => String, { nullable: true })
    fullName?: string;
  }

  return ProfileFieldsMixinObject;
}
```

**Describe the solution you'd like**

Maybe `@ShareType` that can be treat as transparent ?

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalLytek** [comment]
This is the way to go, it's mentioned in the docs:

```
@InputType()
@ObjectType()
```

**Comment by wenerme** [comment]
Thanks
