### ISSUE TITLE
Error "Expected a value of type XXX but received" on emun

### ISSUE THREAD

**Issue by chengjia0807** [MichalLytek/type-graphql#270]
Hi,

I have an issue with the Enum type. 

We are developing a web app and sharing the same develop database during development.

The issue is, if one of us added some testing data or new data into the enum field in database, then others will get the error "Expected a value of type XXX but received" when doing a full query on table for example. Because the testing data will be read by everyone using this database and those whose branch does not have this new data in Enum will get this error.

It's an annoying issue that we try to avoid, and it is getting worse and worse while the product is growing.

Is there a way to solve it or to hide this kind of error?

Thanks

CJ

**Comment by 19majkel94** [comment]
Enum means only a certain range of value is valid. So if you can have any string in DB, you should mark the type as string, not an enum.

**Comment by chengjia0807** [comment]
> Enum means only a certain range of values is valid. So if you can have any string in DB, you should mark the type as string, not an enum.

Sorry mate, maybe my description was not clear.

I'll give you a simple example of this issue.

A and B are two developers, and they are using a string enum to store the access permission.

enum is: 

enum Access = {
    All = "All",
    None = "None
}

All the users has a database filed, which is a string array, to store their own access.

A added a new option in the enum, which is "Some"

The enum become 
{
    All = "All",
    Some = "Some",
    None = "None
}

Then A created a user which has the new field "Some"

MongoDB field is:
access: ["All", "Some", "None"]

B is actually working in another branch and he does not have "Some" in his Access Enum.

When B queries all items in users table, he can pickup data from DB without any issue. 
But when he tried to pass the value back to frontend through type-graphql, he will got this error until he merge A's code in his branch.

In real world situation, we may have many developers working with the same database but different branches of code and working on tons of enums at the same time.  Then this issue become annoying.

Currently if it happens, we have to either merge this bit of enum code to everyone's branches, or we have to clean up the database or force guys to work on their local db which is not ideal...

**Comment by 19majkel94** [comment]
There's nothing I could do about it. The `Expected a value of type` error comes from underlaying `graphql-js` that checks if the returned data match the GraphQL schema contract.

In your case you should just filter the data in the repository/DB layer, so it will convert the additional values to the supported one.

Different branches of code and global shared database means only one: 💣 💥

**Comment by chengjia0807** [comment]
> There's nothing I could do about it. The `Expected a value of type` error comes from underlaying `graphql-js` that checks if the returned data match the GraphQL schema contract.
> 
> In your case you should just filter the data in the repository/DB layer, so it will convert the additional values to the supported one.
> 
> Different branches of code and global shared database means only one: 💣 💥

Thanks for your advise. Close the issue 👍
