### ISSUE TITLE
Proposal: Add observable support

### ISSUE THREAD

**Issue by 4F2E4A2E** [MichalLytek/type-graphql#28]
It woul be great to have observable support for various reasons, but mostly compatibility and error handling.
https://github.com/19majkel94/type-graphql/blob/d859d9c964080023b4d28af68eab39c217dbea61/src/interfaces/ResolverInterface.ts#L6

**Comment by 19majkel94** [comment]
I don't see why resolver should return observable instead of value - it's called once and should produce result once, there's no need for an event stream. You can always do `.toPromise()`.

**Comment by 4F2E4A2E** [comment]
> I don't see why resolver should return observable instead of value - it's called once and should produce result once, there's no need for an event stream. You can always do .toPromise().
For broader support, flexibility and community acceptance.

 >Also, graphql-js doesn't support this so it's not an easy task and also should be a plugin, not built-in feature with rx-js dependency, not used by majority.
Can't say nothing against a opinion, everyone has his. Still this is a great lib, thanks!

**Comment by 19majkel94** [comment]
> For broader support, flexibility and community acceptance.

I haven't seen any resolver implementation built with observables. Could you show some code sample how it helps solving problems better than promises? 😉

**Comment by 4F2E4A2E** [comment]
Of yource i can't since [graphql-js supports promise only at the moment](https://github.com/graphql/graphql-js/issues/501), but that's the thing, though you could be the first, it's not about that.

**Comment by 19majkel94** [comment]
I don't need working example, I just want to see an idea, what problem its solves, etc. Then I can think about implementation when I will see the potential 😉

**Comment by chrisdevereux** [comment]
This might help: https://github.com/apollographql/graphql-subscriptions

**Comment by 19majkel94** [comment]
@chrisdevereux 
1. `graphql-subscriptions` are `AsyncIterator` based, not `Observable`
2. TypeGraphQL already has support for Subscriptions using [apollographql/graphql-subscriptions](https://github.com/apollographql/graphql-subscriptions):
https://19majkel94.github.io/type-graphql/docs/subscriptions.html

**Comment by chrisdevereux** [comment]
> TypeGraphQL already has support for Subscriptions using apollographql/graphql-subscriptions:
https://19majkel94.github.io/type-graphql/docs/subscriptions.html

Ah, I totally misread this Issue then. Excellent!

**Comment by MichalLytek** [comment]
Closing as it doesn't look useful anymore 🔒
