### ISSUE TITLE
browser.shim.js error for internet explorer 11

### ISSUE THREAD

**Issue by domi7777** [MichalLytek/type-graphql#350]
**Describe the bug**
`browser.shim.js` cannot be processed by internet explorer 11 because it contains arrow function code: 

`const dummyFn = () => void 0;`

I was able to fix the issue by changing it to:
```
var dummyFn = function () {
  return function () {
  };
};
```

Now, I'm not sure if the `browser.shim.ts` should be updated likewise, or if typescript compilation target could be set to ecmascript 5 for this file only.

**Comment by 19majkel94** [comment]
@domi7777 
TypeGraphQL is a Node.js framework and it requires ES2016 target to work because it uses a few new features of EcmaScript:
https://typegraphql.ml/docs/installation.html#typescript-configuration

So it makes no sense to transpile the lib to ES5. What is your use case that you need IE 11 support?

**Comment by domi7777** [comment]
@19majkel94 , as documented in https://typegraphql.ml/docs/browser-usage.html , we use the browser.shim to be able to share our typescript model in the frontend, so the browser.shim.js ends up in the browser.

**Comment by 19majkel94** [comment]
@domi7777 And your bundler doesn't handle transpilation to the target ES version?

**Comment by domi7777** [comment]
@19majkel94 our tsconfig.json contains   `  "target": "es5",` already, and we don't compile browser.shim.ts as it is already transpiled to browser.shim.js in the `node_modules/type-graphql`.

**Comment by 19majkel94** [comment]
@domi7777
But a lot of packages in npm are not distributed in ES5-compatible version, so you need to transpile them too to make it work in IE11 or older browser.

**Comment by domi7777** [comment]
@19majkel94 I guess I could add babel to my build to transpile this file, but I thought it would be overkill.

The other libs I use provide different versions of their scripts (umd/esm5/esm2015/...)

**Comment by 19majkel94** [comment]
@domi7777 
Can you point me to the example lib that has multiple entrypoints for different target/build systems? I would like to support them too.

**Comment by domi7777** [comment]
@19majkel94 I'm really no expert on this matter, but here's an example: [apollo-angular](https://github.com/apollographql/apollo-angular). 

I'm not sure it is worth investing time to support fully Ecmascript5 as type-graphql is a server-side library, and only the browser.shim.js is used on frontend side as a way to not include the library in the bundle. 

That is why I thought simply changing the two arrow functions to es5 functions would make internet explorer happy without the burden of changing the build configuration.

**Comment by 19majkel94** [comment]
Ok, I will try to fix the shim for now 💪
