### ISSUE TITLE
Custom npm package for object validation?

### ISSUE THREAD

**Issue by wolfiton** [MichalLytek/type-graphql#357]
Hello,

I want to implement my custom validation using an external package that can be found in this git repo https://github.com/oussamahamdaoui/forgJs.

How can I replace the class-validator with forgJS?

Can I have a schema wide validation for all my  objects?

Thanks in advance

**Comment by 19majkel94** [comment]
You can use middleware for that purpose and wrap it in a method decorator, just like in docs for joi:
https://typegraphql.ml/docs/custom-decorators.html#method-decorators

In the future with #123 you will have an access to the metadata like `MyArgs` class, so no need to manually provide validate schema if you can derivate it from a class.

I will also try to rewrite the core to add a special support for validation lib in plugins 😉

**Comment by MichalLytek** [comment]
Closing this one via 3c767e6 🔒 

@wolfiton you can now use provide your own `validate` function implementation that will call `forgJS`.
