### ISSUE TITLE
How to "mixin" InputType/ObjectType classes?

### ISSUE THREAD

**Issue by chengjia0807** [MichalLytek/type-graphql#359]
As I know a Javascript class can only extend one another class, and typescript mixin method can mix mulitple classes into one.

I tried to mixin multiple object classes by using mixin but it does not work. However "extends"  is working perfectly.

Just want to know that does TypeGraphql support mixin classes on objects?

Thanks
CJ

**Comment by georgyfarniev** [comment]
@chengjia0807 can you provide your code sample where your mixing your objects? Code of mixin function you use? What is the final purpose of mixing Input and Output type?

**Comment by 19majkel94** [comment]
@chengjia0807 
You can try to use ES class mixins:
https://mariusschulz.com/blog/typescript-2-2-mixin-classes

**Comment by 19majkel94** [comment]
I think I should add an example about this pattern.

In the future I might publish a fork of [mix with](https://github.com/justinfagnani/mixwith.js/) with TS support.

**Comment by chengjia0807** [comment]
> I think I should add an example about this pattern.
> 
> In the future I might publish a fork of [mix with](https://github.com/justinfagnani/mixwith.js/) with TS support.

that would be very helpful! Thank dude. By the way, I love this library

**Comment by MichalLytek** [comment]
Closing via 31af325 🔒 

You can see the example of using mixin classes and inheritance to reduce duplication between input types, and object types too 😉
