### ISSUE TITLE
Field decorator generating wrong type on schema

### ISSUE THREAD

**Issue by henriquetatagiba** [MichalLytek/type-graphql#397]
**Describe the bug**
Hi, I'm trying to do a custom pagination to my events attribute, but even tho I specify the right type on `@Field` decorator, it still uses the class `User` type to generate the schema as an array.

**To Reproduce**
```typescript
@ObjectType()
export class User extends Typegoose {
  @Field(type => EventPagination, { nullable: true })
  @ArrayProperty({ itemsRef: 'Event' })
  public events: Array<Ref<Event>>;
}
// user.type.ts
```

```typescript
@Resolver(() => User)
export class UserResolver {
  @FieldResolver(() => EventPagination)
  public async events(
    @Root('_doc') user: User,
    @Arg('filter', () => EventFilterInput, { nullable: true })
    filter: EventFilterInput
  ): Promise<EventPagination> {
    return {
      edges: [],
      pageInfo: {
        size: 0,
        total: 0
      },
    };
  }
}
// user.resolver.ts
```

```graphql
type User {
  events(filter: EventFilterInput): [EventPagination!] # <---- WRONG
}
# schema.graphql
```
**Expected behavior**
```graphql
type User {
  events(filter: EventFilterInput): EventPagination # <---- RIGHT
}
# schema.graphql
```

**Enviorment (please complete the following information):**
 - OS: OSX 10.14.5
 - Node 12.6
 - Package version 0.17.4
 - TypeScript version 3.5.2

**Comment by 19majkel94** [comment]
It's because you're trying to overwrite the field type but it treats your annotation as providing the lacking array item type:

https://typegraphql.ml/docs/types-and-fields.html

> For simple types (like string or boolean) this is all that's needed but due to a limitation in TypeScript's reflection, we need to provide info about generic types (like Array or Promise). So to declare the Rate[] type, we have two options available:
> - `@Field(type => [Rate])` (recommended, explicit [ ] syntax for Array types)
> - `@Field(itemType => Rate)` (array is inferred from reflection - also works but is prone to errors)

As many people can have this valid code:

```ts
@Field(itemType => MyItem)
items: MyItem[];
```

I can't just drop the auto Array detection mechanism.

The easiest and also cleaner solution than overwriting ref's array type to pagination object is to separate them:


```ts
@ObjectType()
export class User extends Typegoose {
  // remove the field decorator
  @ArrayProperty({ itemsRef: 'Event' })
  // note the new name
  public eventsRefs: Array<Ref<Event>>;
}
```

```ts
@Resolver(of => User)
export class UserResolver {
  // here everyting is the same
  @FieldResolver(returns => EventPagination)
  // we register a new field of `User` type with a custom resolver
  public async events(
    @Root('_doc') user: User,
    @Arg('filter', () => EventFilterInput, { nullable: true })
    filter: EventFilterInput
  ): Promise<EventPagination> {
    return {
      edges: [],
      pageInfo: {
        size: 0,
        total: 0
      },
    };
  }
}
```

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
