### ISSUE TITLE
`@Arg` parameter decorators in inherited Resolver do not produce any arguments in GraphQl schema.

### ISSUE THREAD

**Issue by altitudems** [MichalLytek/type-graphql#408]
**Describe the bug**
`@Arg` parameter decorators in inherited Resolver do not produce any arguments in GraphQl schema. 

**To Reproduce**
Create a simple resolver that inherits from a base resolver, following closely the documentation here: https://typegraphql.ml/docs/0.16.0/interfaces-and-inheritance.html.

Example:
```typescript
import { Resolver, ClassType, Query, Arg, Int, ObjectType, Field } from 'type-graphql'

export function createBaseResolver<T extends ClassType>(classType: ClassType) {
  const suffix = classType.name

  @Resolver({ isAbstract: true })
  abstract class BaseResolver {
    protected items: T[] = []

    @Query(type => classType, { name: `multiply${suffix}` })
    public async multiply(@Arg('a', type => Int) a: number, @Arg('b', type => Int) b: number) {
      let instance = new classType()
      instance.value = a * b
      return instance
    }
  }

  return BaseResolver
}

@ObjectType()
class MyResource {
  @Field()
  public value: number
}

const MyResourceBaseResolver = createBaseResolver(MyResource)

@Resolver(of => MyResource)
export class StoryResolver extends MyResourceBaseResolver {}
```

Resulting schema:
```graphql
type Query {
  multiplymyresource: MyResource!
  # Notice the missing arguments a and b
}
```

**Expected behavior**
Query or Mutation arguments represented by an `@Arg` decorator to appear in generated schema.

**Logs**
N/A

**Environment (please complete the following information):**
 - OS: OSX
 - Node 10.16.0
 - Package version 0.17.5
 - TypeScript version 3.5.1

**Additional context**
N/A

**Comment by MichalLytek** [comment]
Cannot reproduce:

```ts
async function main() {
  const schema = await buildSchema({
    resolvers: [StoryResolver],
  });
  console.log(printSchema(schema));
}

main();
```
```graphql
type MyResource {
  value: Float!
}

type Query {
  multiplyMyResource(b: Int!, a: Int!): MyResource!     
}
```

I bet you (or your environment like lambda) are using babel which has legacy decorators plugin that doesn't support method parameters decorators, so they are stripped of and args are not registered. See #55 for more info.

**Comment by altitudems** [comment]
Thanks for the feedback. I'll look for that and report back.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒

**Comment by ryanmargono** [comment]
@altitudems did you end up solving this?
