### ISSUE TITLE
Types are comming from different npm packages

### ISSUE THREAD

**Issue by shreyansh2495** [MichalLytek/type-graphql#411]
I dont know the exact cause of this bug, but i think so its related to reflect-metadata.
Steps to reproduce
- Install a different npm package which make use of type-graphql
- After installing you will see in your playground all the types from that npm package will be displayed 

Expected behavior
- In playground and in our project the types which are used by our project should only come

**Comment by MichalLytek** [comment]
Kinda duplicate of #110. Is this a hypothetical situation or why you have two APIs from npm in one node process?

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
