### ISSUE TITLE
The documentation search field is broken

### ISSUE THREAD

**Issue by abdullah-kasim** [MichalLytek/type-graphql#414]
**Describe the issue**

URL: https://typegraphql.ml/docs/introduction.html

The documentation search field at the above url is broken - I can search for a term, but upon clicking the result of any term, it leads to a 404 page.

I used `InputType` as my search term.

**Comment by MichalLytek** [comment]
Thanks for the info. I've changed the account name and forget to update the entry in Algolia DocSearch.

**Comment by MichalLytek** [comment]
It should be fixed now 🎉
