### ISSUE TITLE
Nullable array

### ISSUE THREAD

**Issue by tonyxiao** [MichalLytek/type-graphql#418]
How do I describe the following sdl via type-graphql?
```graphql
type Mutation {
   bulkUpsertItems(inputs: [UpsertItemsInput!]!): [Item]!
}
```

In particular, I don't see a way to get the return type to be `[Item]!`. The `nullable` option changes whether the array itself is nullable, not the array elements.

**Comment by MichalLytek** [comment]
https://typegraphql.ml/docs/types-and-fields.html

> In the case of lists, we may also need to define their nullability in a more detailed form. The basic { nullable: true | false } setting only applies to the whole list ([Item!] or [Item!]!), so if we need a sparse array, we can control the list items' nullability via nullable: items (for [Item]!) or nullable: itemsAndList (for the [Item]) option. Be aware that setting nullableByDefault: true option will also apply to lists, so it will produce [Item] type, just like with nullable: itemsAndList.

**Comment by tonyxiao** [comment]
Ah, thanks so much for the hint. Sorry I missed it in the docs.
