### ISSUE TITLE
Syntax Highlighting for documentation

### ISSUE THREAD

**Issue by JohannesKlauss** [MichalLytek/type-graphql#421]
**Describe the issue**
Currently inside the documentations code snippets there is no syntax highlighting which makes the code very hard to read.

**Are you able to make a PR that fix this?**
I could create a PR, but we would have to settle on a highlighter to use.

**Comment by MichalLytek** [comment]
What is not working for you? 😕 

![image](https://user-images.githubusercontent.com/10618781/65047517-ded47a00-d962-11e9-9023-e206236751ef.png)

**Comment by JohannesKlauss** [comment]
Very weird. It looks like this for me:
<img width="399" alt="Bildschirmfoto 2019-09-17 um 19 48 51" src="https://user-images.githubusercontent.com/6214415/65066202-39ca9900-d984-11e9-9cd1-f27a127650ec.png">
Using the latest version of chrome, no errors in the console.

**Comment by MichalLytek** [comment]
Do you have an adblock enabled or scripts disabled?

**Comment by JohannesKlauss** [comment]
AdBlock disabled, scripts enabled.
Weird thing is: I see the highlighting for a second and then it just gets monochrome. I'll investigate a bit more. Maybe some extension screws it up.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
