### ISSUE TITLE
Using a Union in @Field decorator

### ISSUE THREAD

**Issue by RyannGalea** [MichalLytek/type-graphql#425]
Hi all,

It seems I'm having a conflict with type-graphql and another package 'typegoose' when it comes to using unions.

I have just had a look through source and noticed this comment about unions being only usabled on the @Query:

      Now we can use the union type in the query.
      Notice, that due to TypeScript's reflection limitation, we have to explicitly use the `SearchResultUnion` value in the `@Query` decorator return type annotation.
      For TypeScript compile-time type safety we can also use `typeof SearchResultUnion` which is equal to type `Movie | Actor`.

      ```typescript
      @Resolver()
      class SearchResolver {
        @Query(returns => [SearchResultUnion])
        async search(@Arg("phrase") phrase: string): Promise<Array<typeof SearchResultUnion>> {
          const movies = await Movies.findAll(phrase);
          const actors = await Actors.findAll(phrase);

          return [...movies, ...actors];
        }
      }
      ```

As I am a little confused after seeing this on how I would type a field directly? In my example i hold an 'entityRef 'which will populate the 'entity' when requested. It can return one of many different types depending on the notes parent.

I have been attempting this:

      export const NoteEnityUnion = createUnionType({
        name: 'NoteEnityUnion', 
        types: () => [Contact, Property, BusinessProperty, Supplier, User],
        resolveType: value => {
          if ('contactType'  in value) return Contact
          if ('buildingType' in value) return Property
          if ('supplierType' in value) return Supplier
          if ('firstName'    in value) return User
          return undefined
        }
      });

      @ObjectType()
      export class Note extends GlobalFields {

        @Field() 
        @prop()
        body: string

        @Field(type => NoteEnityUnion)
        @prop({ required: true, refPath: 'entityRef' })
        entity: Ref<Property | Contact | Supplier | User>

        @Field(type => EntitiesEnum)
        @prop({required: true, enum: Object.values(EntitiesEnum), index: true})
        entityRef: EntitiesEnum
        
      } 

      export const NoteModel = getModelForClass(Note)

Firstly this is a correct way to implement a union on a @Field as i don't see any examples of this directly? if not how would I implement this onto a query? I'm just confused by the documentation on this.

The @Query is obviously typing a returned request, but I am only trying to type a field here.

**Comment by MichalLytek** [comment]
`@Query` is technically a `@FieldResolver` for GraphQL `type Query`. So you can use an union type as a field type.

But you need a glue that will resolver mongoose refs into an entities, that's why you should have a property `entityType: EntitiesEnum` that will tell you how to interpret `entityRef: Ref<Property | Contact | Supplier | User>`. Then you can create a `@FieldResolver` for new field `entity: NoteEnityUnion` that will call the mongoose model to fetch selected entity and return it.

**Comment by RyannGalea** [comment]
Ok, I understand,

Typegoose now uses the 'refPath' on @prop to determine which model to pull from which I think from reading your example is the same thing.

Although it seems this may be an unrelated issue I'm having, I may have to create an example repository here soon to reproduce the problem.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒

**Comment by RyannGalea** [comment]
I will create a project to try and trim everything back to simply create the error,

**Comment by RyannGalea** [comment]
I created a repo which reproduces the problem, i believe it has to do with imports/cyclic imports making some exported const's undefined, but i have no idea on how i would resolve this issue.

See repository here guys, i have stripped it back to the very basics and i still have the error on my end. Please let me know if it reproduces on your end.

https://github.com/RyannGalea/typegooseErr
