### ISSUE TITLE
Documentation in Russian

### ISSUE THREAD

**Issue by Hellomik2002** [MichalLytek/type-graphql#426]
I am sorry but can i translate your documentation, i want help to russian-beginner developers?(something like in Vue). I am sorry, if i write off topic letter

**Comment by MichalLytek** [comment]
Sorry but I can't maintain the docs in different language so they will be quickly out of sync. 

Maybe it's better to create a blog in Russian that will act like a getting started into TypeGraphQL for beginner developers?

**Comment by MichalLytek** [comment]
@Hellomik2002 
When you create some tutorial about TypeGraphQL in Russian, please send me the link - I will add that to the repo readme to help russian-beginner developers 😉
