### ISSUE TITLE
Generating schema error

### ISSUE THREAD

**Issue by morenof90** [MichalLytek/type-graphql#429]
I'm trying to build my schema using a glob path string as the boostraping section on the documentation shows:

```
import { buildSchema } from "type-graphql";

async function bootstrap() {
  const schema = await buildSchema({
    resolvers: [__dirname + "/**/*.resolver.ts"],
  });

  // other initialization code, like creating http server
}
```

But I'm getting a Generating shema error: `message: 'Type Query must define one or more fields.'`

**My actual schema building code**
_index.ts_
```
const schema = await buildSchema({
			resolvers: [__dirname + "/resolvers/*.resolver.ts"]
		});
const apolloServer = new ApolloServer({ schema });
```

**My resolver**
_resolvers/testResolver.resolver.ts_

```
import { Resolver, Query } from "type-graphql";

@Resolver()
export class TestResolver {
	@Query(returns => String)
	hello() {
		return "hi";
	}
}
```

If I manually import the resolver everything works fine

**Comment by morenof90** [comment]
I found my error, in the documentation is assumed that schema creation is made on the root folder wich wasn't my case. So I changed my path definition to a relative one using the **path** library and everything works as expected.

A simple path error :/

**Comment by kateile** [comment]
path lib?? show me how
