### ISSUE TITLE
Is there a way to deploy type-graphql project to appsync?

### ISSUE THREAD

**Issue by chengjia080787** [MichalLytek/type-graphql#430]
Sorry guys this question might not relate to your fancy library.

I just want to know whether there is a way to deploy Type-graphql project on Apollo server to AWS app sync?

I know you guys are experts.

Thanks
CJ

**Comment by MichalLytek** [comment]
Please ask your generic question on [Gitter](https://gitter.im/type-graphql/Lobby) or Stackoverflow.

Github issues are not a helpdesk - they are for reporting bugs and feature requests.
