### ISSUE TITLE
Union of Int and String

### ISSUE THREAD

**Issue by troy-harrison** [MichalLytek/type-graphql#439]
I'm attempting to create a union that is of Int and String

const NumOrString = createUnionType({
    name: "NumOrString",
    types: () => [Int, String],
});

I'm getting 
>Direct Array syntax is depreciated.  Use the function syntax () => TClassTypes instead

Looking at the documentation the only difference is the union is between 2 object types insead of scalars.
https://typegraphql.ml/docs/unions.html

**Comment by MichalLytek** [comment]
GraphQL spec doesn't support union of scalars - you can only wrap the object types:
> Note that members of a union type need to be concrete object types; you can't create a union type out of interfaces or other unions.

https://graphql.org/learn/schema/#union-types
