### ISSUE TITLE
Ability To Use TypeGraphQL Decorated Models In Create React App

### ISSUE THREAD

**Issue by chrisdostert** [MichalLytek/type-graphql#441]
**Is your feature request related to a problem? Please describe.**
Create React App does not give ability to modify webpack config so there's no way to share models between backend and frontend. (not considering ejecting a solution because that defeats much of the purpose of create react app)

**Describe the solution you'd like**
Some alternative solution not requiring access to webpack config (see https://github.com/MichalLytek/type-graphql/blob/master/docs/browser-usage.md)

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalLytek** [comment]
```sh
npm i -D @craco/craco
```

```js
// craco.config.js
const { NormalModuleReplacementPlugin } = require("webpack");

module.exports = {
  webpack: {
    configure: (config, { env, paths }) => {
      config.plugins.push(
        new NormalModuleReplacementPlugin(/type-graphql$/, resource => {
          resource.request = resource.request.replace(
            /type-graphql/,
            "type-graphql/dist/browser-shim",
          );
        }),
      );
      return config;
    },
  },
  babel: {
    plugins: [
      [
        "@babel/plugin-proposal-decorators",
        {
          legacy: true,
        },
      ],
    ],
  },
};
```

```sh
craco start
```

**Comment by chrisdostert** [comment]
@MichalLytek thanks! Haven't had a chance to try yet but this looks promising

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
