### ISSUE TITLE
I can't use array as Argument in Mutation

### ISSUE THREAD

**Issue by Hellomik2002** [MichalLytek/type-graphql#450]
```
    @Mutation(returns => Institution)
    async addDataInstit(
        @Arg('types', { nullable: true }) newTypes: string[],
        @Arg('token') token: string[],
        // @Arg('addModerators', { nullable: true }) newModeratorIds?: string[],
        // @Arg('executorIds', { nullable: true }) newExecutorIds?: string[],
        // @Ctx() ctx1?: UserContext,
    ): Promise<Institution> {
        if (this.takeChecker == null) {
            this.takeChecker = await MongoConnection.getInstance();
        }
...
```
is it possible to array as argument use ? 
i can't launch with it

**Comment by MichalLytek** [comment]
`@Arg('token', type => [String]) token: string[],`

**Comment by Hellomik2002** [comment]
Thanks for this quick response

**Comment by Dan-X** [comment]
It seems it't not mentioned anywhere in the doc, maybe mention it somewhere?

**Comment by MichalLytek** [comment]
@Dan-X It's documented properly:
https://typegraphql.com/docs/types-and-fields.html
> So to declare the `Rate[]` type, we have to use the explicit `[ ]` syntax for array types - `@Field(type => [Rate])`.

The docs are intended to read from A to Z, not only installation and jump straight to coding.

**Comment by Dan-X** [comment]
@MichalLytek 
okay I didn't know `@Arg` decorator is the same as `@Field`
my bad.
> The docs are intended to read from A to Z, not only installation and jump straight to coding.
thanks for the lesson
