### ISSUE TITLE
Add static field resolver

### ISSUE THREAD

**Issue by S1lentium** [MichalLytek/type-graphql#455]
In my eslint, (class-methods-use-this) rule is described, where it is forbidden to use methods without specifying **this**:
```js
  @FieldResolver()
  public genres(@Root() track: Track) {
    return track.entity.genres; // expected 'this' to be used by class method 'genres'
  }
```
I want to rewrite the method declaration as follows:
```js
 public static genres(@Root() track: Track) {
    return track.entity.genres;
  }
```
But getting an error:
`(node:8808) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getObjectType' of undefined`
I also get an error when I use ResolverInterface, that the field in entity(type) is missing. But specifying a static field does not solve the problem.

Is it possible to add static field processing to describe resolvers?

**Comment by MichalLytek** [comment]
> Is it possible to add static field processing to describe resolvers?

No, there's no sense for that. As stated in the FAQ:
https://typegraphql.ml/docs/faq.html#should-i-implement-a-field-resolver-as-an-object-type-getter-a-method-or-a-resolver-class-method

If your field resolver doesn't need access to injected services (no this), just implement that as a getter (no args) or method (with args) on the type class itself.

**Comment by S1lentium** [comment]
In any case, I have to turn off the rule. But the rule (airbnb) is relevant and good for the rest of the application. And I would like not to disable for TypeGraphQL.

Is it really impossible to call the resolver as a static method, even if the service is not injected?

like:
`ResolverClass.resolver(service)?`

**Comment by MichalLytek** [comment]
`Is it really impossible to call the resolver as a static method, even if the service is not injected?`

The whole idea of resolver classes is to be able to use class features like `this.` -> decorators, dependency injection, etc.

Static fields/methods are a global variables/methods which is not a good pattern. I would have to specially refactor some logic to not get an instance from the container, now create a fresh instance like with type classes but directly call an resolver class object method.

It makes no sense, it only fix the lint rule, no other added value.

**Comment by S1lentium** [comment]
It can do a preliminary check, for example, check the function descriptor from metadata. If it is a static method, then call it as a static resolver, otherwise call it as an instance of the class.

**Comment by MichalLytek** [comment]
Unnecessary complexity just for fixing the lint rule without any other added value.
Closing this issue 🔒 

If you find a better use case for static field resolver, please feel free to reopen the issue.
