### ISSUE TITLE
package.json: Incorrectly uses the dependancies entry for class-validator

### ISSUE THREAD

**Issue by mathenshall** [MichalLytek/type-graphql#457]
**Describe the bug**
Packages that require singleton instantiation (eg class-validator)  are specified as 'dependancies' rather than peer-dependancies.

Applications and third party libraries that use class-validator may install a version in addition to the required version in type-graphql.

the class-validator library complains that more than one instance of the  library is installed

**To Reproduce**
A quick guide how to reproduce the bug.

Add 
"dependancies": {
   "class-validator": "^0.9.1"
}

to an application using type-graphql 

**Expected behavior**
That yarn or npm would correctly find a version that is compatible with type-graphql and the application and only install that version.

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.

**Enviorment (please complete the following information):**
 -  Node: 10.15.2
 - Package version 0.17.5
 - TypeScript version : 3.7.2
**Additional context**
My general understanding is that most of the dependancies listed should really be peerDependancies....

**Comment by MichalLytek** [comment]
> the class-validator library complains that more than one instance of the library is installed

As far as I know, the error is only about the empty metadata storage, so you may just not used any `class-validator` decorators. If you have a monorepo without deps hoisiting or using `npm link` - peer dependencies won't work for `class-validator`.

> Applications and third party libraries that use class-validator may install a version in addition to the required version in type-graphql.

If the versions are matching, `npm dedupe` works really well to flatten the deps. So it will use your version only and remove the one from `type-graphql` node modules folder.

The reason why I'm not making everything a peer-dependency as there's a dev overhead to lazy load them on demand and it requires users to install all the packages along with `type-graphql`, so it's not anymore "built-in".

In the future there will be a plugin system, so you will only install the things you want to use and the plugins will have peer dependecies on 3rd party packages that are integrating with TypeGraphQL.

**Comment by MatthiasKunnen** [comment]
Just to clarify, in the future class-validator will be not be a dependency but will be included only if the developers wants to?

**Comment by MichalLytek** [comment]
@mathenshall 
`npm i @typegraphq/class-validator class-validator`

**Comment by mathenshall** [comment]
@MichalLytek sorry for delay in acknowledging your reply! I missed the notification in my email :-)

Better late than never, I hope, Thanks for your attention!
