### ISSUE TITLE
Unused types are ignored

### ISSUE THREAD

**Issue by xizall** [MichalLytek/type-graphql#459]
**Is your feature request related to a problem? Please describe.**
I'm trying to integrate type-graphql with schema generating library [neo4j-graphql-js](https://github.com/neo4j-graphql/neo4j-graphql-js) from Neo4j database. This library generates queries, mutations and resolvers just from type definitions.

user.ts

    import { Field, ID, ObjectType } from 'type-graphql';

	@ObjectType()
	class User {
		@Field(() => ID)
		id: number;

		@Field()
		name: string;
	}

post.ts

    import { Field, ID, ObjectType } from 'type-graphql';  
  
	@ObjectType()  
	class Post {  
		@Field(() => ID)
		id: number;

		@Field()  
		text: string;  
     
		@Field(() => User)  
		author: User;  
	}
The problem is when I built schema with `buildTypeDefsAndResolvers` it threw error `Type Query must define one or more fields` . So I created resolver.
dummy-resolver.ts

    import { Int, Query, Resolver } from 'type-graphql';  
  
	@Resolver()  
	class DummyResolver {  
		@Query(() => Int)  
		foo() {  
			return 1;
		}
	}
The problem now is that `buildTypeDefsAndResolvers` only generates types that are used, so user and post types are ignored, but I need definition of these types to pass to neo4j-graphql-js library.

**Describe the solution you'd like**
Adding option `includeUnusedTypes?: boolean` in building schema functions would be pretty great solution.

**Comment by MichalLytek** [comment]
Your types has to be somewhere in the import chain to allow metadata of decorators to be collected and to be registered in schema. As TypeGraphQL was focused on building resolvers, not only object types, you have to manually import them in the entry point file.

You can also use `npm i type-graphql@beta` and `orphanedTypes` option:
https://typegraphql.ml/docs/next/bootstrap.html
