### ISSUE TITLE
Feature Request: Support for graphql object GraphQLInputObjectType in resolver args

### ISSUE THREAD

**Issue by chocopowwwa** [MichalLytek/type-graphql#463]
**Is your feature request related to a problem? Please describe.**
i have an object with type `GraphQLInputObjectType` and i want to use it in my resolver class function as an argument, i couldn't find way to integrate my object with type-graphql metadata

**Comment by MichalLytek** [comment]
```
@Resolver(MySchema)
@Query(returns => [MySchema])
```

😱 So you want to add resolvers to the existing GraphQL Schema?

**Comment by chocopowwwa** [comment]
hmm never mind, i get confused along the way, i just want to be able to use something like https://github.com/Soluto/graphql-to-mongodb so i can effortlessly generate a graphql input from my entity, but i need access to the type as well, thank you for your time

**Comment by MichalLytek** [comment]
@chocopowwwa 
Maybe you could use [generic types](https://typegraphql.ml/docs/generic-types.html) feature for that.
