### ISSUE TITLE
Emitted schema has comments incompatible with extensions

### ISSUE THREAD

**Issue by hisuwh** [MichalLytek/type-graphql#468]
**Describe the bug**
I want to use the GraphQL for VSCode extension with the generated GraphQL schema.  Unfortunately, it contains comments like using `"""` which does not seem to be compatible, e.g.:
```gql
"""
The javascript `Date` as string. Type represents date and time as the ISO Date string.
"""
scalar DateTime
```

Can we have an option to disable these comments until these issues are resolved:

- https://github.com/kumarharsh/graphql-for-vscode/issues/130
- https://github.com/Mayank1791989/gql/issues/143

**To Reproduce**

Setup and use this extension: https://marketplace.visualstudio.com/items?itemName=kumar-harsh.graphql-for-vscode

**Expected behavior**
I want to use the generated schema with this extension to autocomplete.

**Logs**
If applicable, add some console logs to help explain your problem.
You can paste the errors with stack trace that were printed when the error occured.

**Enviorment (please complete the following information):**
 - OS: Windows
 - Node 10.9.0
 - Package version: 0.17.5
 - TypeScript version: 3.7.2

**Comment by MichalLytek** [comment]
RTFM!
https://typegraphql.ml/docs/emit-schema.html
`commentDescriptions: true,`

**Comment by hisuwh** [comment]
I set that - didn't work.  I still got those comments.

**Comment by hisuwh** [comment]
Oh nvm.  I set it to false, because I didn't want those comments - but its the opposite
