### ISSUE TITLE
DataLoader on Apollo Federation example

### ISSUE THREAD

**Issue by valdestron** [MichalLytek/type-graphql#471]
Would love to see a bit more sophisticated example of apollo-federation. Would be nice to see
- circular references between user and other entity
- dataLoader approach using reference resolvers

I could help with that also.

**Comment by MichalLytek** [comment]
What's the difference between TypeGraphQL and apollo-like approach for Apollo Federation?

How does the TypeGraphQL has to do this in different way that you need an example?

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
