### ISSUE TITLE
dateScalarMode:timestamp is not working in my project

### ISSUE THREAD

**Issue by apprithm** [MichalLytek/type-graphql#477]
Hi,
 I have been following this tutorial: https://typegraphql.ml/docs/scalars.html:

 1. set dateScalarMode: "timestamp" in BuildSchema
 2. defined a field in user.type.ts called createdAt and the type is: Date.
 3. Everything builds and runs fine

But when the user JSON object returned from my rest API, it doesn't map to my graphql/typescript class, the "createdAt" field is always null.

P.S. The createdAt field returned by the rest API is also in timestamp format.

Did I miss any step here?

Thanks.

**Comment by MichalLytek** [comment]
Yes, you should return the `Date` instance, not the timestamp as number. Otherwise it will skip this and return as null.

So you should map the timestamp to Date by `new Date(timestamp)` while getting the data from REST API.

**Comment by apprithm** [comment]
@MichalLytek 
Thanks for the response.

Just making sure I understand correctly:

- REST API should return createdAt in "ISO DATE" such as: 2007-04-05T14:30Z
- Set dateScalarMode: "timestamp" in BuildSchema
- Define the createdAt field in my model as Date

Then I would get timestamp number in graphql ?
 
If my REST API will only return createdAt in number format, is there still a way for me to do this ?

**Comment by MichalLytek** [comment]
If you describe in your object type that `createdAt` property is of type `Date`, it means you can call `createdAt.getYear()` and TS will allow to do that. But if you assign a string (representing the ISO date) to the property, it will fail on runtime. So you violate the types contract - you should do `myObject.createdAt = new Date(createdAtISOStringFromRest)` while fetching the data in resolvers.

As you can see in the code:
https://github.com/MichalLytek/type-graphql/blob/ac2bded5154d14886c987fb8709805c040582c4e/src/scalars/timestamp.ts#L19-L24

If you don't return date instance, only number (e.g. `123`), it returns null in that case.

**Comment by apprithm** [comment]
If I don't have control over the rest service. Which currently returning timestamp in LONG format such as: 1575528770.
Is the only wayt for me the get around this is to use another field such as createdAtTimestamp:Number, then manually map it to createdAt:Date in graphql side ?

**Comment by MichalLytek** [comment]
You need a mapper for transforming REST response into GraphQL object type:

```ts
const userFromRest = await getUserFromRest();
const user: User = { 
  ...userFromRest,
  createdAt: new Date(userFromRest.createdAt),
};
```

Maybe the better approach would be to change `createdAt` type to `number` and `type => Int`? Then you have type correctness and no mapping is needed.

**Comment by apprithm** [comment]
I see.
I would like to use Long instead of Int. Can you point some reference of how can I use graphql-scalar Long in the type-graphql file ?

Thanks.

**Comment by MichalLytek** [comment]
@apprithm 
https://typegraphql.ml/docs/scalars.html
