### ISSUE TITLE
Using definite assignment assertion breaks InputType

### ISSUE THREAD

**Issue by erikshestopal** [MichalLytek/type-graphql#478]
Hi! 👋 I didn't see anything in the docs regarding this but having an exclamation mark around an instance variable in a class decorated with `@InputType` breaks the schema generation. 

**To Reproduce**
```ts
@InputType()
class LoginArgs {
  @Field()
  email!: string; // notice the exclamation
}
```

```
Exception: Input Object type LoginArgs must define one or more fields.
```

**Expected behavior**
Schema should be generated without excepttions. 

**Environment (please complete the following information):**
 - OS: `Mac OS `
 - Node `v10.12.0`
 - Package version `0.18.0-beta.6`
 - TypeScript version `3.7.2`

**Comment by MichalLytek** [comment]
Cannot reproduce ❌ `typegraphql-prisma` generates that syntax by default and it's working without a problem.

Please create a repository with a minimal reproducible code example and instructions how to run the code to reproduce the issue.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
