### ISSUE TITLE
typegraphql-prisma gets stuck installing

### ISSUE THREAD

**Issue by codejamninja** [MichalLytek/type-graphql#480]
`typegraphql-prisma` gets stuck installing.

I think it's related to https://github.com/prisma/photonjs/issues/310

I think updating the prisma dependencies will fix it.

**Comment by MichalLytek** [comment]
> However, during the preview I would ask to add comments only in this issue, not to create a new issues, as I don't want to pollute the repo for now 😉

https://github.com/MichalLytek/type-graphql/issues/476

**Comment by codejamninja** [comment]
@MichalLytek sure
