### ISSUE TITLE
Add Date and Time scalars

### ISSUE THREAD

**Issue by glen-84** [MichalLytek/type-graphql#483]
**Is your feature request related to a problem? Please describe.**

I see a `DateTime` scalar, but not a `Date` or `Time` scalar. I'd like to use a `Date` scalar for a `dateOfBirth` field (for example).

**Describe the solution you'd like**

Add a `Date` scalar (formatted like `1991-12-24`), and possibly a `Time` scalar (UTC).

**Describe alternatives you've considered**

https://www.npmjs.com/package/graphql-iso-date

... but type-graphql includes `GraphQLISODateTime`, so I think that it makes sense to also include `Date` and `Time` scalars.

**Additional context**

n/a

**Comment by MichalLytek** [comment]
JS `Date` object consists of both date and time, so it's serialized as a timestamp or an ISO string.

If you need only the date part or only the time, you can use any custom GraphQL scalar you want and use a `scalarsMap` feature to map the `Date` JS class to this scalar:
https://typegraphql.ml/docs/scalars.html#custom-scalars

**Comment by glen-84** [comment]
Aren't `Date` and `Time` fields common enough to be included in this library? Seems a bit strange to use `DateTime` from this library, but `Date` from another.

Also, using `scalarsMap` would likely map _all_ `Date` types to `Date`, which is not what I'd want (I'll still be using `DateTime` fields). I'll specify the GQL type for Date-only fields.

Anyway, I'll use [graphql-iso-date](https://www.npmjs.com/package/graphql-iso-date) for now.

**Comment by MichalLytek** [comment]
> Also, using scalarsMap would likely map all Date types to Date, which is not what I'd want

So annotate each field separately with `@Field(type => MyDateScalar)`.

**Comment by glen-84** [comment]
> So annotate each field separately with `@Field(type => MyDateScalar)`.

That's what I meant by "I'll specify the GQL type for Date-only fields".
