### ISSUE TITLE
type-graphql , typegoose error output 

### ISSUE THREAD

**Issue by okpakomarvis** [MichalLytek/type-graphql#484]
hello please i am having some errors with my type-graphql , typegoose code for the past two days i have been having a sleepless night still getting the same error; "Field \"getCollection\" of type \"[Collection!]!\" must have a selection of subfields. Did you mean \"getCollection { ... }\"?", can you help please ,

this is the link to the project on github
https://github.com/okpakomarvis/Typegraphql-blizzard
![Annotation 2019-12-05 220642](https://user-images.githubusercontent.com/40584739/70274112-d21a3200-17ab-11ea-810e-b3705e83ecba.png)
![Annotation 2019-12-05 221103](https://user-images.githubusercontent.com/40584739/70274593-b8c5b580-17ac-11ea-8479-ce41f40930b3.png)
![Annotation 2019-12-05 221211](https://user-images.githubusercontent.com/40584739/70274595-b8c5b580-17ac-11ea-8d99-e037122df5e4.png)
![Annotation 2019-12-05 221446](https://user-images.githubusercontent.com/40584739/70274597-b95e4c00-17ac-11ea-8dd9-0d4094c7c84a.png)

**Comment by MichalLytek** [comment]
You've already asked that question on gitter and you received an answer.

> If you want to achieve something in your code but you don't know how to do it, or you have some problems with configuration and your code is not working, gitter chat is a better place to ask your question:
https://gitter.im/type-graphql/Lobby
