### ISSUE TITLE
Deprecated peer dependency @types/graphql

### ISSUE THREAD

**Issue by johnnyomair** [MichalLytek/type-graphql#485]
Hi, 
first of all, thanks for your awesome work. ❤️ 

I've noticed that `type-graphql` requires `@types/graphql` as peer dependency, which has been deprecated.

Is it ok to remove this dependency? Is there any way I could help?

**Comment by MichalLytek** [comment]
Thanks! For the report but it's already done - the docs will be updated with `v0.18.0` release that have bumped peer deps of `graphql-js` to version that have included typings in the package.
