### ISSUE TITLE
Cannot return Mongoose documents in resolver

### ISSUE THREAD

**Issue by fromi** [MichalLytek/type-graphql#491]
**Describe the bug**
Mongoose documents rely on getter properties to track changes in a model. There also is an 'id' getter that wraps the '_id' field in a very convenient way: https://mongoosejs.com/docs/guide.html#id

Since I switched to type-graphql, I have this error everytime I try to return mongoose documents in my resolvers: "Cannot return null for non-nullable field ...."
I can workaround this issue by calling document.toObject() all the time to get direct properties instead of getters (I also have to transform '_id' into 'id' all the time then). I can also report the properties one by one in the return value...

**To Reproduce**
Create a very simple mongoose schema:
```
type UserDocument = User & Document
const userSchema: Schema = new Schema({
  name: String
})
const UserModel: Model<UserDocument> = models.User || model<UserDocument>('User', userSchema)
```
A simple graphql type:
```
@ObjectType()
export default class User {
  @Field(() => ID)
  id?: string

  @Field()
  name: string
}
```
And use a very basic resolver (works if not using type-graphql):
```
@Resolver(User)
export class UserResolver {

  @Query(() => User)
  async getUser(@Arg('id') id: string) {
    return UserModel.findById(id)
  }
}
```

**Expected behavior**
Mongoose document getters for 'id' and 'name' gets called and user is resolved.

**Workaround**
This resolver works:
```
@Resolver(User)
export class UserResolver {

  @Query(() => User)
  async getUser(@Arg('id') id: string) {
    const user = await UserModel.findById(id)
    return {id: user.id, name: user.name}
  }
}
```

Thanks for any help!

**Comment by MichalLytek** [comment]
You need to return data, not the mongoose document wrapper. 

You can do that manually or by a middleware that will detect if it's an instance of mongoose `Model` and then call `.toObject()` on it.

Here's an advanced example for Typegoose that also convert the document to the proper object type instance:
https://github.com/MichalLytek/type-graphql/blob/master/examples/typegoose/typegoose-middleware.ts

**Comment by fromi** [comment]
Thanks, that middleware looks like a good solution, I can improve it to transform '_id' into 'id' as well.

For my understanding, could you explain why the mongoose document wrapper worked properly when I directly passed my resolvers to apollo-server and is broken now that I use type-graphql?

**Comment by MichalLytek** [comment]
I think that you use `@FieldResolver` or `@Field` with method or getter - this triggers convertion to the class instance:
```ts
const targetInstance: any = convertToType(targetType, root);
```

**Comment by fromi** [comment]
This is my object:
```
@ObjectType()
export default class TabletopGame {
  @Field(() => ID)
  id?: string

  @Field()
  name!: string

  @Field()
  description!: string

  @Field(() => [Int])
  players!: number[]

  state?: string
  authorId?: string
}
```
No FieldResolver, no method and no getter. I have 2 non annotated properties (used by mongoose but not exposed for now), maybe that's what triggers the convertion?

**Comment by MichalLytek** [comment]
Please create a repository with a minimal reproducible code example.

**Comment by fromi** [comment]
That's way too much work only to satisfy my curiosity :)
The middleware solution is perfect, thanks a lot for the help!

**Comment by ericbf** [comment]
This is a bit old, but we just started using TypeGraphQL in a mongoose project and are hitting this issue as well, but we can’t just use a middleware. We have _a lot_ of expensive virtuals that we can’t just greedily calculate to object.

What actually is the point of `convertToObject`? Can you elaborate why we need to try to convert to the class describing the type?

**Comment by MichalLytek** [comment]
@ericbf as stated in readme, the design goal was to have class instances in resolvers. That allows you to have getters or methods like in OOP, as well as rely on instanceof for narrowing underlying type for unions or interfaces.

**Comment by ericbf** [comment]
Makes sense. In our case, we are using `TypeGraphQL` with `typegoose`, where the class describing the GraphQL type and the mongoose schema type are one and the same, and are compatible with the model instance (that’s to say, the model instance has the getters and methods of the original type, but is an instance of the mongoose model instead of the original class). In many of the getters/setters, we are potentially relying on some of the mongoose specific additions (`parent()` in subdocuments, for example) which would be completely lost by `covertToType`.

If I patch my local version of TypeGraphQL and simply return `data` in `convertToType`, what are the side effects I should expect to see? What would it break?
