### ISSUE TITLE
What is the difference between @Resolver(Recipe) and @Resolver(of => Recipe)?

### ISSUE THREAD

**Issue by fromi** [MichalLytek/type-graphql#492]
In the [Getting Started](https://typegraphql.ml/docs/getting-started.html) documentation, `@Resolver(Recipe)` is used. Based on my understanding, specifying the class type here is unnecessary because `@FieldResolver` is not used inside the class?

In the [Resolvers](https://typegraphql.ml/docs/resolvers.html) documentation, `@Resolver(of => Recipe)` is used, for field resolvers only. Could `@Resolver(Recipe)` also work here? If not, what is the point of `@Resolver(ClassType)` contructor?

**Comment by MichalLytek** [comment]
`@Resolver(of => Recipe)` is the recommended one.

`@Resolver(Recipe)` is kinda alias but will be removed in the future for API consistency.
