### ISSUE TITLE
Doc site is down.

### ISSUE THREAD

**Issue by zifahm** [MichalLytek/type-graphql#494]
The documentation site seems to be down.

 https://typegraphql.ml/

**Comment by MichalLytek** [comment]
![image](https://user-images.githubusercontent.com/10618781/70889667-6de54280-1fe3-11ea-958f-c06069252835.png)

For me it also works. Please check your internet connection.

**Comment by zifahm** [comment]
![cropedDown](https://user-images.githubusercontent.com/3761062/70890044-10182100-200a-11ea-9272-a2c018e93ce2.png)

**Comment by MichalLytek** [comment]
The github.io hosting server is working, the DNS is working too, I can't do nothing more about it - looks like some internet providers has some problems. You have to wait or find another website hosted by github.io that is not working and report the issue to them.

**Comment by zifahm** [comment]
Funny enough it works on my mobile data but not on my WiFi. I guess its the google dns?

**Comment by zifahm** [comment]
@MichalLytek  Worked after changing my dns provider to open dns.

**Comment by wanjas** [comment]
I'm getting the same IP from Google and Open dns. 
`Name:	typegraphql.ml
Address: 195.20.50.182`
typegraphql.ml is not working and IP itself leads to http://www.dot.tk/en/index.html?lang=en

**Comment by zifahm** [comment]
@wanjas typegraphlq.ml is now typegraphql.com. Hope that helps
