### ISSUE TITLE
0.18.0-beta.7 breaks schema generation of GraphQL interface types

### ISSUE THREAD

**Issue by kaienbcjdoapwkfldue** [MichalLytek/type-graphql#496]
**Describe the bug**
^0.18.0-beta.7 breaks schema generation of GraphQL interface types. 0.17.5 still works.

**To Reproduce**

**Enviorment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node 12.6.0
 - Package version 0.18.0-beta.7
 - TypeScript version 3.6.2

**Comment by MichalLytek** [comment]
> ^0.18.0-beta.7 breaks schema generation of GraphQL interface types

All tests are passing, so filling
> To Reproduce

is highly needed, so please create a repository with a minimal reproducible code example.

And, have you read the changelog, PR #415 and updated your `buildSchema` code?

**Comment by kaienbcjdoapwkfldue** [comment]
Sorry, I missed the point on orphaned types, although I don't really understand why types implementing interfaces are considered to be orphaned if not explicitly returned by a resolver, because they are still integral part of the API.

If I have an interface `Animal` that is implemented by a `Cat` and a `Dog` and a resolver that is returning `Anmal` types, then `Cat` and `Dog` should as a default be included in the schema, because otherwise there is no point in using an interface in the first place.

Anyway, I'll use the `orphanedTypes` option or resort to globs.
Thank you and keep up the good work!

**Comment by MichalLytek** [comment]
I can't implicitly emit all types from metadata storage - I rely on GraphQL JS mechanism that emit only the types referenced in the schema. So for interfaces you need to use `orphanedTypes`. You can read more about this feature in the discussion:
https://github.com/MichalLytek/type-graphql/issues/110#issuecomment-562177912
