### ISSUE TITLE
Errors in the "Get Started Documentation"

### ISSUE THREAD

**Issue by charlie632** [MichalLytek/type-graphql#501]
**Describe the issue**
 There are some things that are wrong in the get started docs. For example, this input `NewRecipeDataInput ` is never declared. It should be `NewRecipeInput`.

Also, the `class-validator` decorator, `ArrayMaxSize` is written as `MaxArraySize`

**Are you able to make a PR that fix this?**
Yeah, I can create a PR :)

**Additional context**

**Comment by charlie632** [comment]
#502 PR Open

**Comment by MichalLytek** [comment]
Thanks @charlie632 for pointing that 💪
