### ISSUE TITLE
@Directive decorator doesn't escape strings properly

### ISSUE THREAD

**Issue by GrayStrider** [MichalLytek/type-graphql#509]
`@Field({defaultValue: "Hi!"})
@Directive('deprecated', {reason: '"Use another field instead."'})
deprecated: string`

Have to wrap the `reason` around in two sets of quotes, otherwise doesn't compile:
![image](https://user-images.githubusercontent.com/43771776/71751887-27dc1a00-2ed1-11ea-9f4a-0e5b8a5fdd07.png)

**Comment by MichalLytek** [comment]
As stated in docs:

> Current implementation of directives in TypeGraphQL is using some crazy workarounds because graphql-js doesn't support setting them by code

So it's not possible to build a good API when using workarounds.

If we automatically detect string value and wrap it into second set of quotes, it would fail for string enums that has to be passed without quotes into the SDL. The best way is to use the string based declarations:

```ts
@Directive('@deprecated(reason: "Use `newField`")')
```
