### ISSUE TITLE
Input logic in 0.18.0-beta.4

### ISSUE THREAD

**Issue by joemckie** [MichalLytek/type-graphql#510]
Since 0.18.0-beta.4, the logic for inputs (although only _nested_ inputs, strangely) seems to have changed, resulting in Firestore throwing errors when using their data directly (Firestore only takes plain objects, not instantiated classes)

I've managed to work around it by using `classToPlain() as Type`, but doing this for each instance of an input is quite messy.  I'm wondering if this is intended behaviour?

**Comment by MichalLytek** [comment]
>  I'm wondering if this is intended behaviour?

Yes, TypeGraphQL always transform the plain args into classes instance according to the shapes of Input Types.
In previous version there was a bug and only a root-level args/inputs were transformed, now all of them.

> (Firestore only takes plain objects, not instantiated classes)

What do you mean? Can you show your input type classes?

**Comment by joemckie** [comment]
> What do you mean? Can you show your input type classes?

Here is a sample:

```ts
@InputType()
export class OrderInput implements Partial<Order> {
  @Field(_type => OrderCustomerInput, { nullable: true })
  public partialCustomer?: OrderCustomerInput;

  @Field(_type => OrderStatus)
  public status: OrderStatus;

  @Field(_type => [OrderLineItemInput])
  public lineItems: OrderLineItemInput[];
}
```

After doing some digging, it seems like this is limited only to nested arrays.

In this instance, `lineItems` throws an error as the array contains classes that need converting, however as other properties are simple types, they are mapped 1-to-1 (I presume spreading a class applies its properties onto the new object, however the array maintains the internal classes).

If this is intended behaviour there's probably not much to be done, I just wanted to check and raise an issue in case anyone else came across this behaviour. I can see the benefits of using classes when performing validation on inputs 😄

**Comment by MichalLytek** [comment]
>  this is limited only to nested arrays.
> lineItems throws an error as the array contains classes that need converting

What is limited? Why it is throwing an error?

> I can see the benefits of using classes when performing validation on inputs

You mean that earlier you passed wrong data and now the validation works and it throws validation errors? 😄

**Comment by joemckie** [comment]
> What is limited? Why it is throwing an error?

It's limited because Firestore doesn't accept classes, only plain objects. When I insert into the database, I spread the input, which converts it into a plain object, but any nested properties don't get converted automatically.

> You mean that earlier you passed wrong data and now the validation works and it throws validation errors? 😄

Not quite 😉before, `type-graphql` didn't instantiate nested properties so it worked fine. Now it's changed, I need to convert those manually. 

I'm going to close this issue, I don't think there's anything wrong with the code!

**Comment by MichalLytek** [comment]
> It's limited because Firestore doesn't accept classes, only plain objects.

All right! So Firebase is the proper guilty one 😄 
https://github.com/firebase/firebase-js-sdk/issues/311
