### ISSUE TITLE
directive decorator is missing in current dist build

### ISSUE THREAD

**Issue by volbrene** [MichalLytek/type-graphql#513]
hello, I was wondering why I didn't have the directive decorator available, even though it's available in your git. It seems you made a mistake with the versioning process at npm. The current npm package does not contain the code in git. 

It would be great, if you can fix it :)

 - type-graphql npm package version: 0.17.6

**Comment by MichalLytek** [comment]
https://github.com/MichalLytek/type-graphql/blob/master/CHANGELOG.md#unreleased

`npm i type-graphql@beta`
