### ISSUE TITLE
Use DI Container inside buildSchemaSync from graphql-tools

### ISSUE THREAD

**Issue by volbrene** [MichalLytek/type-graphql#517]
Hello,

it it possible to use DI Container inside buildSchemaSync, when I use the directive decorators.

At the moment (without using buildSchemaSync), I can add the type-di container inside buildSchema. 

Old version:
```
const schema = await buildSchema({
    resolvers: resolvers,
    container: Container,
    authChecker: authChecker,
  });
```

New Version with buildSchemaSync:
```
const schema = await buildSchemaSync({
    resolvers: [DemoResolver],
  });

  // register the used directives implementations
  SchemaDirectiveVisitor.visitSchemaDirectives(schema, {
    auth: AuthDirective,
    authorized: AuthDirective,
    authenticated: AuthDirective,
    deprecated: DeprecatedDirective,
  });
```

**Comment by MichalLytek** [comment]
> it it possible to use DI Container inside buildSchemaSync

Yes, in the same fashion like the async `buildSchema` one.
