### ISSUE TITLE
How can I query only relevant fields?

### ISSUE THREAD

**Issue by DevelGitH** [MichalLytek/type-graphql#519]
I have the following simple query, where the client can retrieve informations from all users.
For performance reasons, I would like to retrieve only those fields from the database that the user has requested. Currently all fields are fetched from the database, even the user has only requested the columns id and email.

```
@Resolver(of => User)
export class UserResolver {
  constructor(
    // constructor injection of a service
    private readonly userService: UserService
  ) {}

  @Query(returns => [User])
  async users(
    @Args() options: UserArgs
  ): Promise<User[]> {
// How can I get here the fields that the user has requested?
    var users = await this.userService.findAll(options);
    return users;
  }
}
```

```
{
  users {
    id
    email
  }
}
```

**Comment by christianMurschall** [comment]
The short answer is: you can pull the [graphql info object](https://graphql.org/graphql-js/type/#graphqlobjecttype) as an argument in your resolve function:

``` typescript
  @Query(returns => [User])
  async users(
    @Args() options: UserArgs,
    @Info() info: GraphQLResolveInfo
  ): Promise<User[]> {
      // Inspect the info object and check which fields are requested
    var users = await this.userService.findAll(options);
    return users;
  }
}
```


But I really doubt, that this is worth the work. Did you confirm, that your query is in fact taking too much time by tests and measurements?
Have you tested your theory that fetching less fields will increase performance by a noticeable amount? Or are you taking preemptive measurements? 

> preemptive optimization is the root of all evil
> *Donald Knuth*

**Comment by DevelGitH** [comment]
Hi, thanks for your reply. I've also found out that there is an info object from the type GraphQLResolveInfo, but how can I extract now the fields that were requested? I've looked at the property fieldNodes but there weren't the fields that I was looking for.

Currently this is just a preventive measure and for testing the possibilities of type graphql/graphql.
Normally I'll always fetch all fields, but once I had also a table with over 10.000 entries (also with joins), where fetching only the relevant fields increased the performance by a noticeable amount.

**Comment by MichalLytek** [comment]
@DevelGitH See #10

**Comment by glen-84** [comment]
I posted a simple example [here](https://github.com/MichalLytek/type-graphql/issues/10#issuecomment-573061281).

**Comment by DevelGitH** [comment]
Thanks that helped :)
