### ISSUE TITLE
Omitting certain enum values (non-string/number) from schema

### ISSUE THREAD

**Issue by oeed** [MichalLytek/type-graphql#522]
**Is your feature request related to a problem? Please describe.**
I have been using a pattern of coupling associated functions or values with the enum in a namespace with the same name. I like it as it simply keeps things tidier and easier to find, but I can understand if some people mightn't like it. When complied, the values declared in the namespace become included in the enum as one single object.

The problem is when TypeGraphQL reads the enum it, understandably, includes every key including functions, arrays, etc.

```typescript
export enum DateGranularity {
  hourly = "hourly", // one grain per hour
  daily = "daily", // one grain per day
  fullCampaign = "fullCampaign" // one grain for the entire campaign
}

export namespace DateGranularity {

  export const asArray = () => [DateGranularity.hourly, DateGranularity.daily, DateGranularity.fullCampaign]

  // returns true if 'a' is finer granularity than 'b' (i.e. site is finer grain than region)
  export function isFinerOrEqual(a: DateGranularity, b: DateGranularity) {
    return a === b || a === DateGranularity.hourly || (a === DateGranularity.daily && b === DateGranularity.fullCampaign)
  }

}

registerEnumType(DateGranularity, {
  name: "DateGranularity"
})

// e.g. helper functions can be used as such
DateGranularity.isFinerOrEqual(DateGranularity.hourly, DateGranularity.daily)
```

This renders the following schema:
```graphql
enum DateGranularity {
  hourly
  daily
  fullCampaign

  asArray # notice the array and function are included
  isFinerOrEqual
}
```

**Describe the solution you'd like**
I've read over the internal code and can understand what is happening. I'd be quite happy to make a PR with the changes, but I can see a few possible routes or perhaps it's not a desired feature.

_Possible solution 1:_
As TypeScript [only allows strings and numbers](https://www.typescriptlang.org/docs/handbook/enums.html) as enum values, I think the most intuitive and straight forward solution is to modify `getEnumValuesMap` and simply only include string or number values in the map (hence stripping out any functions, arrays, etc. declared in namespaces). Please correct me though if this wouldn't work.

_Possible solution 2:_
Alternatively, rather than doing it automatically, `EnumConfig` could be modified to have an optional white/blacklist of keys to include in the schema. It is a bit more flexible, but I prefer solution 1 as it uses existing language restrictions and doesn't require any extra declarations.

While it doesn't really match my exact use case, this solution may perhaps be useful to be able to shield of certain enum values (i.e. internal-only values) from the schema. Obviously, there are fairly straightforward workaround to achieve that though.

**Describe alternatives you've considered**
I tried having a wrapper function for registering which would register a different object with only the keys I wanted, but this doesn't work when you try to use the enum as an input/output type because it tries to find the enum by equating objects (which fails as the full enum and object with desired keys are different).

**Comment by MichalLytek** [comment]
As your use case is rather rare, it will be better if you just do:
```ts
import { enumWithoutNamespace } from "./helpers";

registerEnumType(enumWithoutNamespace(DateGranularity), {
  name: "DateGranularity"
})
```

`registerEnumType` doesn't require passing en enum, only an object with keys (used in schema) and values (replaced in runtime).

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes as no response from OP 🔒
