### ISSUE TITLE
Graphql playground - show schema based on access role

### ISSUE THREAD

**Issue by DevelGitH** [MichalLytek/type-graphql#525]
I've implemented the authorization middleware (https://typegraphql.ml/docs/authorization.html) for my resolvers successfully, so only users with valid jwt token can perform certain queries/mutations.

Is it also possible to show in the graphql playground only these queries/mutations to the users that they've access to?

**Comment by MichalLytek** [comment]
Closing as completely out of topic - Github issues are not a helpdesk for generic GraphQL question, only for bug reports and feature request directly related to TypeGraphQL 🔒 

> valid jwt token

> graphql playground

![image](https://user-images.githubusercontent.com/10618781/72686316-9cc76a80-3af3-11ea-9516-82999e483c0b.png)
