### ISSUE TITLE
example for interface-inheritance does not work for implemented fragments

### ISSUE THREAD

**Issue by leetmachine** [MichalLytek/type-graphql#529]
**Describe the issue**
the example interfaces-inheritance does not work as expected. When running the supplied graphql statements the fragments do not return the additional fields. 

**Tested on version 0.17 and 0.18.10-beta with no success. 
steps to reproduce:**
1. start example/interfaces-inheritance server.
2. run the supplied addStudent mutation.
3. run the supplied persons query.
![image](https://user-images.githubusercontent.com/9122789/73507220-1f221b00-438d-11ea-9968-57d70c8c4231.png)

what was expected:
both objects returned are Students, so should have their universityName field present.

code:
https://github.com/MichalLytek/type-graphql/blob/master/examples/interfaces-inheritance/examples.gql

I'm trying to implement the same thing in my own code base but having the same issue. I would really appreciate the update!

**Comment by MichalLytek** [comment]
AFAIK, it's related to #373. Could you confirm that that issue is about the same problem?

**Comment by christianvanr** [comment]
maybe not usefull, but i had the same problem (due to the orphanized type) and have solved it quit easy like this 

`@InterfaceType({
  resolveType: value => {
    return value.constructor.name;
  }
})

**Comment by leetmachine** [comment]
@MichalLytek confirmed, looks the solution presented here solved the issue. Thanks!

**Comment by MichalLytek** [comment]
I've added the workaround to the examples in 801a453.
Maybe finding by `value.constructor` is better than `instanceof` check 🤔
