### ISSUE TITLE
Cannot read property 'type' of undefined on building with union result type

### ISSUE THREAD

**Issue by ashkart** [MichalLytek/type-graphql#536]
I have an error when working with union result type.
Here is [working demo](https://codesandbox.io/s/github/ashkart/typegraphql_issue_demo)
Uncomment `getUserWithUnion` method in `resolver.ts` to reproduce the problem.

```
TypeError: Cannot read property 'type' of undefined
    at /home/maxim/workspace/demo/node_modules/type-graphql/dist/schema/schema-generator.js:66:101
    at Array.map (<anonymous>)
    at types (/home/maxim/workspace/demo/node_modules/type-graphql/dist/schema/schema-generator.js:66:22)
    at resolveThunk (/home/maxim/workspace/demo/node_modules/graphql/type/definition.js:438:40)
    at defineTypes (/home/maxim/workspace/demo/node_modules/graphql/type/definition.js:837:15)
    at GraphQLUnionType.getTypes (/home/maxim/workspace/demo/node_modules/graphql/type/definition.js:806:26)
    at typeMapReducer (/home/maxim/workspace/demo/node_modules/graphql/type/schema.js:272:28)
    at typeMapReducer (/home/maxim/workspace/demo/node_modules/graphql/type/schema.js:286:20)
    at Array.reduce (<anonymous>)
    at new GraphQLSchema (/home/maxim/workspace/demo/node_modules/graphql/type/schema.js:145:28)
```

**Comment by MichalLytek** [comment]
@ashkart Why `UserNotFoundProblem` has no decorators applied?

**Comment by ashkart** [comment]
Because i created it through `createUnionType` method. I didnt find any decorator for this case.
Should i use any of them? Which one?

**Comment by MichalLytek** [comment]
https://typegraphql.ml/docs/unions.html
> types: () => [Movie, Actor], // function that returns array of object types classes

As stated per GraphQL specification, union type can consist only for object types:
http://graphql.org/learn/schema/#union-types

**Comment by ashkart** [comment]
Confirmed, this is my bad, just got some misunderstanding with different graphql union types guides.

**Comment by aounleonardo** [comment]
Hey @MichalLytek , would it be possible to have a clearer error message and stacktrace when the schema build fails? I frequently run into this problem and it takes time to find the change that caused it :/ 
I'll try to look into it myself too, but I doubt that I have enough knowledge about the library :/

**Comment by MichalLytek** [comment]
@aounleonardo Do you use the latest `1.0.0-rc.1`?

**Comment by aounleonardo** [comment]
No I'm still on: "type-graphql": "^0.17.6",
But I digged into the dist files and the error comes in the graphql `GraphQLSchema` constructor, so I need to look into the core code, or we could add more verifiers before we even call the constructor.

**Comment by MichalLytek** [comment]
> No I'm still on: "type-graphql": "^0.17.6",

So please update and check because the error messages are not much more improved.

**Comment by aounleonardo** [comment]
@MichalLytek Good to know, thanks! I upgraded but the messages are still not that helpful, though I guess the problem is still coming from the graphql library side.
Here are my packages:
```
ubuntu@host:~/backend$ cat package.json | grep graphql
    "@types/graphql-relay": "^0.6.0",
    "express-graphql": "^0.9.0",
    "graphql": "15.0.0",
    "graphql-relay": "^0.6.0",
    "type-graphql": "1.0.0-rc.1",
    "@types/graphql": "^14.5.0",
```
And here's the error message, it would be helpful if they could log the name of the class causing that error.
```
$ ts-node-dev --respawn src/index.ts
Using ts-node version 8.8.2, typescript version 3.8.3
{
  err: TypeError: Cannot read property 'name' of undefined
      at /home/ubuntu/backend/node_modules/type-graphql/dist/schema/schema-generator.js:130:114
      at Array.map (<anonymous>)
      at interfaces (/home/ubuntu/backend/node_modules/type-graphql/dist/schema/schema-generator.js:127:59)
      at resolveThunk (/home/ubuntu/backend/node_modules/graphql/type/definition.js:468:40)
      at defineInterfaces (/home/ubuntu/backend/node_modules/graphql/type/definition.js:661:37)
      at GraphQLObjectType.getInterfaces (/home/ubuntu/backend/node_modules/graphql/type/definition.js:621:31)
      at collectReferencedTypes (/home/ubuntu/backend/node_modules/graphql/type/schema.js:361:61)
      at new GraphQLSchema (/home/ubuntu/backend/node_modules/graphql/type/schema.js:148:9)
      at Function.generateFromMetadataSync (/home/ubuntu/backend/node_modules/type-graphql/dist/schema/schema-generator
.js:30:24)
      at Function.generateFromMetadata (/home/ubuntu/backend/node_modules/type-graphql/dist/schema/schema-generator.js:
15:29)
}

```

**Comment by aounleonardo** [comment]
Oh actually maybe I spoke too quickly, the error comes from the callback called by their constructor...

**Comment by aounleonardo** [comment]
Maybe this could help:
I checked these lines in the type-graphql schema generator:
```
const schema = new graphql_1.GraphQLSchema({
    query: this.buildRootQueryType(options.resolvers),
    mutation: this.buildRootMutationType(options.resolvers),
    subscription: this.buildRootSubscriptionType(options.resolvers),
    types: this.buildOtherTypes(orphanedTypes),
    directives: options.directives,
});
```
The error is throw in the constructor. But I tried calling these buildFunctions before it, and they didn't throw.

Then I printed the output of each of them and got this:
```
query: Query,
mutation: Mutation,
subscription: undefined,
types: [ User, Message, Alert, Notification, Event, Checkup ],
directives: undefined
```

Now I'm looking for a way to describe the Query and Mutation objects...

**Comment by MichalLytek** [comment]
@aounleonardo Please create a repository with a minimal reproducible code example.
Then I can see the mistake in your code, the place where is no guard/check and make proper error thrown there.

**Comment by aounleonardo** [comment]
I'm not really worried about the error, I could just go back in my latest commit. 
I'm trying to just improve the error messages, and find where we could add verifiers in the schema generator to pinpoint the errors.

**Comment by aounleonardo** [comment]
It was a problem of circular imports. 

```
src/types/nodes/
├── chat.ts
├── index.ts
└── user.ts
```
I defined the `ObjectType Chat` and the `InterfaceType Chatable` in chat.ts
and the `ObjectType User` implements `Chatable` in user.ts
I export * from both files in index and then I import the others from "." in each.

It doesn't work if I do this, but it works if I import {Chat, Chatable} from "./chat" in user.ts.

Am I doing a wrong pattern here? And should I remove the index file and just always reference files from each others?

**Comment by MichalLytek** [comment]
Yes, barrel export never works in any library for circular references - always import the file directly.

**Comment by aounleonardo** [comment]
Sorry for the wasted time then. 
But I'm still going to try and implement a verification system that throws neater error messages when building a schema. Just not today :(
