### ISSUE TITLE
Integrationwith graphql-scalars

### ISSUE THREAD

**Issue by sido420** [MichalLytek/type-graphql#547]
I think it'd be beneficial to integrate https://github.com/Urigo/graphql-scalars with typegraphql or at least provide clear instructions on how to use https://github.com/Urigo/graphql-scalars with typegraphql in documentation. I think it should be trivial, but couldn't figure out how.

Ideally, we should be able to start using the scalar types provided by https://github.com/Urigo/graphql-scalars without making any significant modifications to code.

**Comment by MichalLytek** [comment]
Github issues are not a helpdesk - you already asked the question on Gitter so there's no need to open an issue if it's not a bug report or feature request but only your question how do do something :lock:
