### ISSUE TITLE
Can't import @Directive decorator

### ISSUE THREAD

**Issue by izundo-viennv** [MichalLytek/type-graphql#548]
**Describe the bug**
Can't import @Directive decorator. It doesn't exists

**To Reproduce**
![image](https://user-images.githubusercontent.com/29116432/75212233-da857600-57b8-11ea-941b-6dd28e7ce10d.png)

**Enviorment (please complete the following information):**
 - OS: [Windows]
 - Node (10.17.0)
 - Package version [0.17.6] 
 - TypeScript version (3.7.5)

**Comment by MichalLytek** [comment]
@izundo-viennv Do you see that feature in docs?
https://typegraphql.ml/

It's not yet released in the stable channel:
https://github.com/MichalLytek/type-graphql/blob/master/CHANGELOG.md#unreleased

You need to opt-in for beta by `npm i type-graphql@beta`.
