### ISSUE TITLE
resolvers parameter in buildSchema doesn't accept exported Array

### ISSUE THREAD

**Issue by AmrAnwar** [MichalLytek/type-graphql#549]
**Describe the bug**
I updated my type-graphql to the beta **^0.18.0-beta.10**, because error in the stable version with serverless. now I'm getting another error in the **buildSchema** function
- my code is like: 
```js 
// resolver.ts
export const resolverArray  = [AddressResolver, ProfileResolver];
```
```js
// schema.ts
import {resolverArray} from '../resolver';
... 
  const schema = await buildSchema({
    resolvers: resolverArray,
    authChecker: customAuthChecker,
    emitSchemaFile: path.resolve(__dirname, 'schema.gql'),
  });
```
- Error happened only when I compile using tsc: 
```
src/graphql/schema/index.ts:27:5 - error TS2322: Type '(typeof AddressResolver |  typeof ProfileResolver )[]' is not assignable to type 'NonEmptyArray<Function> | NonEmptyArray<string>'.
  Property '0' is missing in type '(typeof AddressResolver)[]' but required in type 'NonEmptyArray<string>'.

27     resolvers: resolverArray,
       ~~~~~~~~~

  node_modules/type-graphql/dist/utils/buildSchema.d.ts:10:5
    10     resolvers: NonEmptyArray<Function> | NonEmptyArray<string>;
           ~~~~~~~~~
    The expected type comes from property 'resolvers' which is declared here on type 'BuildSchemaOptions'


Found 1 error.
```
- the code works when I create the resolverArray when passing it to the Resolver parameter like:
```js
buildSchema({
    resolvers: [AddressResolver, ..etc],
...
```

**Enviorment **
 - OS: macOS
 - Node v10.15.3
 - TypeScript version: 3.7.5

**Comment by MichalLytek** [comment]
v0.18 is using `NonEmptyArray` instead of just `[]` to prevent passing empty array.

In your case, TS doesn't now that it's not empty array, so the simplest fix is to tell TS compiler that it's a tuple, not a dynamic array:
```ts
export const resolverArray  = [AddressResolver, ProfileResolver] as const;
```

In other cases, you can just assert the type if you know what you're doing:
```ts
const schema = await buildSchema({
  resolvers: resolverArray as NonEmptyArray<Function>,
});
```

**Comment by AmrAnwar** [comment]
@MichalLytek  thanks, it worked defining as  **NonEmptyArray<Function>** as you said, here:
```js
export const resolverArray = [AddressResolver, ProfileResolver] as NonEmptyArray<Function>;
```
and thanks for your quick response

**Comment by travigd** [comment]
Can this decision be revisited? It makes it painful to use arrays that aren't array literals and there is a runtime initialization check anyway.

**Comment by MichalLytek** [comment]
> there is a runtime initialization check anyway

But there shouldn't as we want to have type safety, not runtime failures 😉 

If you create the array directly in the options it's not a problem.

If you create multiple arrays in modules and then import them and merge, just use `as const` syntax while creating each of them to tell TS it's gonna be a constant tuple, not a mutable array.

If you create your array dynamically based on some options, use a type guard that will check the length of the array and tell the compiler it's gonna be non empty array:

```ts
function isNotEmptyArray<T>(array: T[]): array is NonEmptyArray<T> {
  return array.length > 0 && array[0] !== undefined;
}
```

**Comment by EirikFA** [comment]
I think it is worth to note that using `as const` makes the exported array `readonly`, which results in `The type 'readonly [typeof AResolver, typeof AnotherResolver, ...]' is 'readonly' and cannot be assigned to the mutable type 'NonEmptyArray<string | Function>'.ts(4104)`.

**Comment by MichalLytek** [comment]
@EirikFA 
Thanks for reporting this 🙏 

Looks like it's the new TS behavior, so I gonna change the type to:
```ts
export type NonEmptyArray<TItem> = readonly [TItem, ...TItem[]];
```

**Comment by MichalLytek** [comment]
I've added a more explicit info in docs how to do that:
https://typegraphql.com/docs/next/bootstrap.html#create-executable-schema
