### ISSUE TITLE
A big thank you from our team @ Mr Yum

### ISSUE THREAD

**Issue by andreimc** [MichalLytek/type-graphql#553]
I just wanted to do a shout out yo you @MichalLytek  and the rest of the contributors, you guys have helped us a lot and we have started contributing a monthly $50 dollars, we know it's not a lot but we are also a start up! Once we get more traction we will become a Gold Sponsor.

👍 and keep up the good work! We are loving this project and it has saved us numerous hours!

A big shout out from the Mr Yum team  and lots of ❤️ from Melbourne, Australia!

**Comment by MichalLytek** [comment]
And a big Thank You from my side for the financial support ❤️ 

I've updated the sponsors section on website and Readme with your logo 😃 

![image](https://user-images.githubusercontent.com/10618781/75522057-50801c00-5a09-11ea-966e-1602a808aa13.png)

> Once we get more traction we will become a Gold Sponsor.

I would love to see first official Gold Sponsor 😍

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
