### ISSUE TITLE
Issue with graphql-jit

### ISSUE THREAD

**Issue by numToStr** [MichalLytek/type-graphql#554]
**Describe the bug**
So, I am using `type-graphql` with `fastify-gql` with has support for `graphql-jit`.
When I enable jit in `fastify-gql`, first-time everything works fine, but second time I use a mutation with returns a `Union`. I get the error below.

```
Abstract type <Name>Union must resolve to an Object type at runtime for field Mutation.<Mutation_Name>. Either the <Name>Union type should provide a \"resolveType\" function or each possible types should provide an \"isTypeOf\" function.
```
This error only comes when a mutation returns a `Union`. Other than that every mutation works fine.
But when I disable the jit, everything works fine. I don't know if this is `type-graphql` specific error or `graphql-jit` error.

BTW, thanks for this awesomee lib :heart: 

**Enviorment (please complete the following information):**
 - OS: Linux 5.5
 - Node: ^12.16.0
 - Package version: ^0.18.0-beta.10
 - TypeScript version:  ^3.8.2
 - fastify: ^2.12.0
 - fastify-gql: ^3.0.6

**Comment by MichalLytek** [comment]
> I don't know if this is type-graphql specific error or graphql-jit error.

If something works without JIT, it's a problem with `graphql-jit`. To achieve high speed they make some shortcuts and some contstructs that are legal in `graphql-js` execution might not work in `graphql-jit`.

Please open an issue on their repo and then try to find a cause of this issue - maybe we can make some workaround for that case.

**Comment by numToStr** [comment]
Thanks for the explanation. I will open an issue on their repo.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒

**Comment by rfgamaral** [comment]
I'm interested in this as well. Have you opened an issued already @numToStr? Can you please link it here, I can't find it.

**Comment by StarpTech** [comment]
Hi, we run into the same limitation it would breat to find out what's wrong to open a detail error report in graphql-jit.
