### ISSUE TITLE
typegraphql-prisma: prisma's @id type is not respected

### ISSUE THREAD

**Issue by unlight** [MichalLytek/type-graphql#561]
**Describe the bug**
typegraphql-prisma generate ID field as String
```
model User {
  id         String    @id  @default(cuid())
}
```
Generated `User.ts`
```
  @Field(_type => String)
  id!: string;
```

**Expected behavior**
```
  @Field(_type => ID)
  id!: string;
```

**Enviorment (please complete the following information):**
typegraphql-prisma@0.1.5

**Additional context**
N/A

**Comment by MichalLytek** [comment]
> during the preview I would ask to add comments only in this issue, not to create a new issues, as I don't want to pollute the repo for now 😉

Please add a comment with your problem in this issue: https://github.com/MichalLytek/type-graphql/issues/476
