### ISSUE TITLE
How to modify parent from FieldResolver

### ISSUE THREAD

**Issue by angelvega93** [MichalLytek/type-graphql#563]
Hi, i would like to know if is possible to modify parent from FieldResolver.

Ex.
```
Pagination(current: 2){
    PageInfo {
       total
    }
    Movies {
        id
        ...
    }
}
```

I would like to modify PageInfo total from Movies FieldResolver.
How can I achieve this?

**Comment by MichalLytek** [comment]
It's not possible in GraphQL, at least not recommended - GraphQL runtime might capture the old value before you modify it.

You need to organise your resolvers in a different way, like the `Pagination` resolver would return the object with `PageInfo` and `Movies`.
