### ISSUE TITLE
Multiple Args include all arguments

### ISSUE THREAD

**Issue by backbone87** [MichalLytek/type-graphql#570]
**Describe the bug**
When using multiple `Args` parameter decorators, each of these parameters contain all args and not just the ones from their respective `ArgsType`.

**To Reproduce**
```ts
@ArgsType()
class SliceArgs {
  @Field(() => Int, { defaultValue: 0 })
  public skip!: number;

  @Field(() => Int, { defaultValue: 30 })
  public take!: number;
}

@ArgsType()
class MyObjectFilterArgs {
  @Field(() => Boolean, { defaultValue: null, nullable: true })
  public active!: boolean | null;
}

@Resolver()
class MyObjectQueries {
  public async myObjects(
    @Args()
    sliceArgs: SliceArgs,
    @Args()
    filterArgs: MyObjectFilterArgs,
  ): Promise<MyObject[]> {
    // sliceArgs and filterArgs both contain all 3 args: skip, take, active
    // isEqual(sliceArgs, { skip: 0, take: 30, active: null });
    // isEqual(filterArgs, { skip: 0, take: 30, active: null });
    
    // insteadof
    // isEqual(sliceArgs, { skip: 0, take: 30 });
    // isEqual(filterArgs, { active: null });

    return db.findMyObjects({ ...sliceArgs, ...filterArgs });
  }
}
```

**Expected behavior**
An args object should only contain the args from its respective `ArgsType`.

**Enviorment (please complete the following information):**
 - Image: node:12-alpine
 - Package version: 0.17.6
 - TypeScript version: 3.8.3

**Additional context**
While not documented, using multiple `Args` works as expected except for this issue

**Comment by MichalLytek** [comment]
> While not documented, using multiple Args works as expected except for this issue

And because of that issue it's not supported thus prohibited to use more than one `@Args` at the same time.

**Comment by backbone87** [comment]
> And because of that issue it's not supported thus prohibited to use more than one @Args at the same time.

i mean it works already? they even get the correct prototypes. the only issue are extrenous props on the arg object. should be quite straight forward to filter the props? and the presented use case is quite common imho.

please dont be so fast with rejecting stuff. I appreciate your work on this library and from what i see in the next branch i definitely like the direction you are taking this tool, but closing issues so quickly while not addressing the presented use case leaves a bitter taste. we can even rebrand this as a feature request, if that makes it better somehow.

**Comment by MichalLytek** [comment]
Sorry but I have literally no time last days, so I can't deliberate more on that.

This issue is covered by the one with mapping names:
https://github.com/MichalLytek/type-graphql/issues/263

If we have the mapping mechanism, it will automatically strip off all the additional properties as a side-effect, so that's why for now you can't use that pattern.

I've added that to my `vNext` board to not forget about that 😉 :
https://github.com/MichalLytek/type-graphql/projects/2#card-34384644

**Comment by backbone87** [comment]
np. I can work around the current until next version is available. Thanks for reconsidering
