### ISSUE TITLE
@Args() and @Ctx() breaks build when using babel-loader

### ISSUE THREAD

**Issue by tzarger** [MichalLytek/type-graphql#571]
**Describe the bug**
Using @Args() and @Ctx() being empty function seems to cause issues with babel-loader when I am using the suggested method in previous issues. I think this issue is a new one, thus opening a new issue.

> babel-plugin-transform-typescript-metadata

which actually still doesn't completely work as I have to also use:

> babel-plugin-parameter-decorator

The issue seems to give the error: 

> TypeError: Cannot read property '0' of undefined

The issue is the fact the @Args() is undefined since it has no typing it seems.

**Here is my babel-loader**
`{
  test: /\.(j|t)s$/i,
  use: [
    {
      loader: "babel-loader",
      options: {
        cacheDirectory: true,
        presets: ["@babel/preset-typescript"],
        plugins: [
          "babel-plugin-parameter-decorator",
          "babel-plugin-transform-typescript-metadata",
          ["@babel/plugin-proposal-decorators", { legacy: true }],
          ["@babel/plugin-proposal-class-properties", { loose: true }]
        ]
      }
    }
  ],
}`

**tsconfig.json**
`
{
   "compilerOptions":{
      "target":"es2019",
      "moduleResolution":"node",
      "resolveJsonModule":true,
      "module":"commonjs",
      "noEmit":true,
      "strict":true,
      "esModuleInterop":true,
      "emitDecoratorMetadata":true,
      "experimentalDecorators":true,
      "skipLibCheck":true,
      "jsx":"preserve",
      "baseUrl":".",
      "paths":{
         "@/*":[
            "src/*"
         ]
      }
   },
   "include":[
      "src",
      "run",
      "types"
   ]
}
`

Is there something I am missing? Or something to get this to work as there seems to be others that say this works. For clarity if only using @Arg(...), that works. I need @Ctx() for passing user and db connection through... unless there is a better injection method for that?

Is there any work-around for this?

**Environment (please complete the following information):**
 - OS: Mac OS
 - Node 11.15.0
 - Package version 0.17.6
 - TypeScript version 3.8.2

**Additional context**
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.8.3",
    "@babel/plugin-proposal-numeric-separator": "^7.8.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.8.3",
    "@babel/plugin-proposal-optional-chaining": "^7.8.3",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-react": "^7.8.3",
    "@babel/preset-typescript": "^7.8.3",

This is being used in an SSR scenario, not sure that matters.

**Comment by MichalLytek** [comment]
There's no official support for JS yet, so you can't use babel or other JS tools.
And I'm afraid it won't change in the future as #296 gonna use custom TS compiler plugin so you will loose a lot of TypeGraphQL vNext goodness by sticking to babel.

Please read that thread and ask other guys for help if it still doesn't work for you:
https://github.com/MichalLytek/type-graphql/issues/55#issuecomment-487365175
