### ISSUE TITLE
Why Middleware not called outside http request 

### ISSUE THREAD

**Issue by jeromeSH26** [MichalLytek/type-graphql#581]
Thks again for this great library. I'm using it for a while now.
I'm trying to use it with moleculerjs and that's work petty well.

However, I just realized that the middleware are not called when the resolver are called from a typescript function.
Executing the same query through the playground (or apollo client) calls the middleware well.

code example,

**Resolver** 
```
@Resolver(of => GqlUsers)
class UsersResolver {
	@Query(() => [GqlUsers], { name: "getAllUsers" })
	@UseMiddleware([isAuth])
	async getAllUsers(
		@Ctx() context: IGraphQLContext
	): Promise<Array<IDataUsers>> {
		return allUsers();
	}
}
```
**context definition**
```export interface IGraphQlBaseContext {
	userAuthId: string;
}

export interface IGraphQLContext
	extends IGraphQlBaseContext,
		MoleculerContext<any, any> {}

```
**middleware**
```
export const isAuth: MiddlewareFn<IGraphQLContext> = async (
	{ context },
	next
) => {
	if (!context.userAuthId || context.userAuthId.trim() === "") {
		throw new GraphQLError("not authorized");
	}

	return next();
};

```

**this is where I called the resolver (inside a function), but the middleware is never called**
```
const user = new UsersResolver();
const data: Array<IDataUsers> = await user.getAllUsers(mergedContext );
```

**Comment by MichalLytek** [comment]
It's by design - middlewares might use `context` and when you're calling the method manually ("from a typescript function" or "outside http request") you might not provide that because it's not required by the method signature.

In your case it would be the `info` value - `GraphQLResolverInfo`, which is not available outside the `GraphQL` execution context.
