### ISSUE TITLE
FieldResolver from another Resolver was invoked.

### ISSUE THREAD

**Issue by xinghul** [MichalLytek/type-graphql#585]
So I have two resolvers, `ClientResolver` and `PublicClientResolver`, and in `ClientResolver` I have a `FieldResolver` defined: 
```
@Resolver(() => Client)
export class ClientResolver {
    @FieldResolver(() => Brand)
    public async brand(@Root() client: Client): Promise<Brand> {
        return this.clientLoader.brand.load(client.brandId);
    }
}
```

Now the issue is, whenever I call the method from another resolver `PublicClientResolver`, the `FieldResolver` from `ClientResolver` is called, is this expected?

**Comment by MichalLytek** [comment]
Try new `type-graphql@0.18.0-beta.14`

**Comment by xinghul** [comment]
Thank you for the quick response, let me try that and will get back to you.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
