### ISSUE TITLE
Context Request with express.jwt

### ISSUE THREAD

**Issue by iamchathu** [MichalLytek/type-graphql#586]
**Describe the issue**
As in example of the documentation when we create custom auth with JWT, Typescript error when compiling that Property 'user' does not exist on type 'Request<ParamsDictionary>'

How to extend the request to add user property?

```ts
context: ({ req }) => {
    const context = {
      req,
      user: req.user, // `req.user` comes from `express-jwt`
    };
    return context;
  },
```

**Are you able to make a PR that fix this?**
No sure, still trying to figure out error.

**Additional context**

**Comment by MichalLytek** [comment]
https://stackoverflow.com/a/51114250/5472617
