### ISSUE TITLE
@Arg defaultValue "null" seems not to be recognized

### ISSUE THREAD

**Issue by karladler** [MichalLytek/type-graphql#593]
**Describe the bug**
Setting the defaultValue like explicitly to `null` `in @Arg('id', { defaultValue: null })`  seems not to be applied, when omitting the argument `id` on request.

**To Reproduce**
````
  @Query(() => User)
  user(@Arg('id', { defaultValue: null }) id: string): User {
    console.log('id', id);

    if (id === null) {
````
Logs `id undefined`;

**Expected behavior**
Logs `id null`; when requested without arguments.

**Environment (please complete the following information):**

- OS: OSX
- Node 12
- Package version: "type-graphql": "^0.17.6",
- TypeScript version: "typescript": "^3.8.3"

**Comment by MichalLytek** [comment]
@karladler Can you reproduce the default `null` value using GraphQL SDL?

**Comment by eezing** [comment]
@MichalLytek Yes, default `null` is valid in SDL. In addition, providing `null` as argument in query also produces `undefined` in type-graphql.

A graphql-js example where null arguments are valid:

https://repl.it/repls/ClearcutRaggedFormat
```javascript
const { graphql } = require('graphql');
const { makeExecutableSchema } = require('graphql-tools');

const typeDefs = `
  type Query {
    hello(msg: String = null): Boolean
  }
`;

const resolvers = {
  Query: {
    hello: (_, args) => {
      console.log(args); // --> { msg: null }
      return true;
    },
  },
};

const schema = makeExecutableSchema({ typeDefs, resolvers });

const query = `
  query {
    a: hello
    b: hello(msg: null)
  }
`;

graphql(schema, query)
```

**Comment by MichalLytek** [comment]
And what is the practical difference between:
```graphql
hello(msg: String = null)
```
and
```graphql
hello(msg: String)
```

In both cases if argument is not provided, it gonna be null/undefined, and from client perspective the arg is optional.

**Comment by eezing** [comment]
Is default `null` practical? No, not really.

But, an explicit `null` argument from query does have meaning; for example, delete record if argument is null or leave it untouched if argument is undefined (implicit vs explicit).

**Comment by MichalLytek** [comment]
But there is no difference in GraphQL Specification about implicit undefined when value not provided and explicit null when null provided.

It's just a case in JS where we have two empty values representation.
So relying on this behavior means your not using GraphQL but GraphQLJS and when somebody change the language of the implementation of this query (other microservice) it won't work anymore 😕

**Comment by eezing** [comment]
Ok, I stand corrected. Semantically there is a difference, but like @MichalLytek said, the spec states that we should not treat implicit and explicit null differently.

https://spec.graphql.org/June2018/#sec-Null-Value

**Comment by MichalLytek** [comment]
More context:
https://github.com/graphql/graphql-js/issues/1298#issuecomment-377365916

So, if `query { hello }` gives undefined for `hello(msg: String)` and `null` for `hello(msg: String = null)`, maybe just treat `undefined` and `null` in the same way, like `arg ?? value` or `if (arg != null)` 😉 

With `hello(msg: String = null)` you never have `undefined`, always `null` even if somebody doesn't provide any arg value, so you can't "leave it untouched if argument is undefined".

**Comment by karladler** [comment]
so `{ defaultValue: null }` is basically doing nothing since it's the same as setting default to undefined. 
Since it Maybe there should be a warning generated, bc it's not that logic and if I test later for `id !== null` the rest of my logic will fail.
A hint in the doc could be also helpful.

**Comment by MichalLytek** [comment]
Closing as `null` as default value is not really practical and supporting this would confuse more people than satisfy, e.g. when they think that `defaultValue: null` means no default value 🔒
