### ISSUE TITLE
https://typegraphql.ml/ is compromised 

### ISSUE THREAD

**Issue by zuzu-dev** [MichalLytek/type-graphql#596]
Documentation links are compromised.please check into that

**Comment by MichalLytek** [comment]
Duplicate of #572 🔒

**Comment by zuzu-dev** [comment]
@MichalLytek consider updating the npmjs.com page. Thats where the link is at Getting started and Documentation sections.

**Comment by MichalLytek** [comment]
@zuzu-dev 
Newer versions has the new url:
https://www.npmjs.com/package/type-graphql/v/0.18.0-beta.15

Unfortunately, I can't rewrite the history and publish new Readme for the old package version.
