### ISSUE TITLE
Basic Field Resolvers Don't Invoke Methods

### ISSUE THREAD

**Issue by travigd** [MichalLytek/type-graphql#597]
**Describe the bug**
If a "basic" field is defined as a property (not a method), then even if it is defined/typed as a function, it is not executed.

**To Reproduce**
```
@ObjectType()
class TestObject {
  @Field(() => String)
  testField = () => "foo";
}
```

**Expected behavior**
The `testField` should be resolved by invoking the anonymous function.

**Environment **
Using type-graphql 0.18.0-beta.15

**Additional context**
This occurs for me in a case where I have an abstract class. You can't define decorators on abstract methods, so I type them as callable and then define the method on the concrete subclasses. It would also be useful in cases where you want to make sure that the `this` binding of the method is correct, but that seems less likely with the way type-graphql is structured.

e.g.
```ts
abstract class PetBase {
  @Field(() => String)
  abstract species: () => Promise<string>;
}

@ObjectType()
class Dog extends PetBase {
  async species() {
    return "dog";
  }
}
```

---

The easiest workaround to this is to re-declare the field inside of `Dog` but that kind of defeats the purpose of what I'm trying to do with inheritance.

With "advanced" resolvers, we do perform a `typeof ... === "function"` check then call the function if it actually is a function, so I don't see why we couldn't do that here. The only exception to this might be an "exotic" use case where you have a `GraphQLScalar` that serializes functions, but seems... unlikely.

**Comment by MichalLytek** [comment]
>  You can't define decorators on abstract methods

That's why you should use the recommended pattern as the workaround does not work with args:
https://typegraphql.com/docs/next/interfaces.html#resolvers-and-arguments
```ts
  @Field()
  avatar(@Arg("size") size: number): string {
    throw new Error("Method not implemented!");
  }
```

If you need to use `abstract`, that should work:

```ts
abstract class PetBase {
  abstract getSpecies(): Promise<string>;

  @Field(returns => String)
  species() {
    return this.getSpecies();
  }
}

@ObjectType()
class Dog extends PetBase {
  async getSpecies() {
    return "dog";
  }
}
```

**Comment by travigd** [comment]
I started looking through the code and I realized that as well. When I came back to this issue, you beat me to the conclusion.

Thanks for the time!
