### ISSUE TITLE
DateTime error in subscription.

### ISSUE THREAD

**Issue by zifahm** [MichalLytek/type-graphql#600]
Im getting an error for DateTime field when subscription gets triggered

```
{"message":"Unable to serialize value '2020-04-07T09:25:08.132Z' as it's not instance of 'Date'","locations":[{"line":12,"column":3}],"path":["newMessage","sentOn"],"
  extensions":{"code":"INTERNAL_SERVER_ERROR"}}
```
## I wonder whats causing the error. I dont seem to find any difference between the two

unlike [TypeGraphQL DateTime](https://github.com/MichalLytek/type-graphql/blob/2065131a0564270cee5be095468ae5952117c7d6/src/scalars/isodate.ts)
```
serialize(value: Date) {
    if (!(value instanceof Date)) {
      throw new Error(`Unable to serialize value '${value}' as it's not instance of 'Date'`);
    }
    return value.toISOString();
  },
```

GraphqlDateTime ["graphql-iso-date" DateTime](https://github.com/excitement-engineer/graphql-iso-date/blob/master/src/dateTime/index.js)
```
 serialize (value) {
    if (value instanceof Date) {
      if (validateJSDate(value)) {
        return serializeDateTime(value)
      }
  },


export const serializeDateTime = (dateTime: Date): string => {
  return dateTime.toISOString()
}
```

**Comment by MichalLytek** [comment]
> I dont seem to find any difference

TypeGraphQL DateTime is throwing an error, "graphql-iso-date" DateTime is returning undefined -> null in response.

> But this works fine while querying the data from the db and just sending it directly

Maybe you use some redis-based graphql subscription that seralize the payload.

You can see that here:
https://github.com/MichalLytek/type-graphql/blob/395357541cc4ca286a94fcad41a99c87b06df5b9/examples/redis-subscriptions/recipe.resolver.ts#L56-L71

**Comment by DarkLite1** [comment]
For others ending up here who work with UTC DateTime strings the package [graphql-scalars](https://github.com/Urigo/graphql-scalars) can be used.

**Comment by madmaxlax** [comment]
> For others ending up here who work with UTC DateTime strings the package [graphql-scalars](https://github.com/Urigo/graphql-scalars) can be used.

I'm having trouble adding the graphql-scalars for UTC Date Time to the right spot for type-graphql, could you provide an example @DarkLite1

**Comment by zifahm** [comment]
@madmaxlax 


```import { DateTimeResolver } from 'graphql-scalars';

@Field(() => DateTimeResolver)
```

**Comment by melanke** [comment]
Well, it threw a different error
```ts
import { Field, ObjectType } from 'type-graphql'
import { DateTimeResolver } from 'graphql-scalars'

@ObjectType()
export class DateAndValue {
  @Field(() => DateTimeResolver)
  date?: Date

  @Field(() => Number)
  value?: number
}
```
Error: Schema must contain uniquely named types but contains multiple types named "DateTime".
    at new GraphQLSchema (C:\Workspace\manoamana\node_modules\graphql\type\schema.js:194:15)


Anyone has any tip? Thanks in advance

**Comment by zifahm** [comment]
> Well, it threw a different error
> 
> ```ts
> import { Field, ObjectType } from 'type-graphql'
> import { DateTimeResolver } from 'graphql-scalars'
> 
> @ObjectType()
> export class DateAndValue {
>   @Field(() => DateTimeResolver)
>   date?: Date
> 
>   @Field(() => Number)
>   value?: number
> }
> ```
> 
> Error: Schema must contain uniquely named types but contains multiple types named "DateTime". at new GraphQLSchema (C:\Workspace\manoamana\node_modules\graphql\type\schema.js:194:15)
> 
> Anyone has any tip? Thanks in advance

Does the scalar need to be mapped?

**Comment by littlespice33** [comment]
> 

I am also seeing this issue

**Comment by bambrose24** [comment]
The problem lies in the way that the default GraphQL DateTime scalar tries to deserialize the date string. If you override your models using the modelsEnhanceMap feature you can set this yourself. A trick is to change the name of the DateTime scalar you're being suggested to use above.

```ts
import { DateTimeResolver as BetterDateTimeResolver } from "graphql-scalars";
import {
  ModelsEnhanceMap,
  applyModelsEnhanceMap,
} from "@generated/type-graphql";
import { Field } from "type-graphql";
BetterDateTimeResolver.name = "BetterDateTimeResolver";


const modelsEnhanceMap: ModelsEnhanceMap = {
  User: {
    fields: {
      createdAt: [Field(() => BetterDateTimeResolver)],
    },
  },
}


applyModelsEnhanceMap(modelsEnhanceMap);

```

This ended up working for me.

**Comment by itpropro** [comment]
This problem still exists, was there a real solution instead of dirty overwriting the resolver @MichalLytek @zifahm, because there was no real solution provided when the issue was closed?

**Comment by MichalLytek** [comment]
@itpropro It was closed because not enough context was provided.
I suspect the issue comes from the pub-sub that serialized the payload (like redis), and this mechanism affects all scalars.
It's out of scope to provide a solution for that, it's too narrow case and TypeGraphQL is mostly query builder, not a fully fledged framework with db and queue solutions integrated.
