### ISSUE TITLE
linter complains "ts(4060)" when following the doc trying generic types

### ISSUE THREAD

**Issue by berton1982** [MichalLytek/type-graphql#603]
i copied the code from the doc: generic types, but failed. linter complains ts 4060 Return_type_of_exported_function_has_or_is_using_private_name.

how to solve this issue?
thx

**Comment by MichalLytek** [comment]
The best way is to read the docs:
https://typegraphql.com/docs/inheritance.html#resolver-inheritance

> Be aware that with some tsconfig.json settings (like declarations: true) we might receive a [ts] Return type of exported function has or is using private name 'BaseResolver' error - in this case we might need to use any as the return type or create a separate class/interface describing the class methods and properties.

I would recommend to set `declarations: false` in `tsconfig.json` if you're not creating a reusable library, but a standalone app that doesn't need `*.d.ts` files.

**Comment by berton1982** [comment]
thx a lot. thats my problem

**Comment by fw623** [comment]
Note that if you need `declarations: true` for whatever reason, #691 shows how to make it work.
