### ISSUE TITLE
Can we use Resolver and it's metadata to dynamically create REST service

### ISSUE THREAD

**Issue by akhilshastri** [MichalLytek/type-graphql#604]
type-graphql roks on graphql part but there are many client application that does not support gql, the way to communicate is REST only. I am looking for a REST service feature aside to graphql schema/resolver. 

Based on my current type-graphql learning, it has enough meta-data to define a REST service ( I am loosely mapping it to gql resolvers ) few things might needed to get from user/develope.

I am happy to contribute if it's considerable

**Comment by MichalLytek** [comment]
GraphQL schema contains enough information to expose a REST API, so you don't need anything TypeGraphQL specific, just a standard tools that works with any GraphQL schema,  e.g.:

[![](https://user-images.githubusercontent.com/25294569/63839869-bfac8300-c988-11e9-978e-6b6c16c350de.gif)](https://github.com/Urigo/sofa)

https://sofa-api.com/

**Comment by akhilshastri** [comment]
seems great, thanks @MichalLytek

**Comment by arthu** [comment]
Has anyone get sofa-api working with type-graphql?
