### ISSUE TITLE
Subscriptions are firing twice

### ISSUE THREAD

**Issue by amsul** [MichalLytek/type-graphql#608]
**Describe the Bug**
Doesn't seem like anyone else has reported or had this issue - but it seems as though my subscriptions are firing twice when their topic is published to.

**To Reproduce**
```typescript
private count = 0

@Subscription({ topics: 'MY_SUBSCRIPTION' })
contestCreated(@Root() payload: { value: string }): string {
  this.count += 1
  console.log(this.count)
  return 'return value'
}
```

**Expected Behavior**
When `pubSub.publish('MY_SUBSCRIPTION', { value: 'some value' })` is called, `this.count` should be logged once to the console with the value `1`.

Instead, it gets logged twice, once with `1` and once with `2`.

**Dependencies in `package.json`:**
```
"apollo-server": "2.12.0",
"class-validator": "0.12.1",
"graphql": "14.6.0",
"pg": "7.3.0",
"reflect-metadata": "0.1.13",
"type-graphql": "0.17.6",
"typeorm": "0.2.24"
```

**Comment by MichalLytek** [comment]
@amsul 
Sorry but I'm unable to reproduce the issue, at least using the latest `0.18.0-beta.17` version.

Please create a repository with a minimal reproducible code example.

**Comment by amsul** [comment]
@MichalLytek ah this was my bad - there were multiple subscribers and so the subscription was logging for each subscriber that needs to be notified 🤦
