### ISSUE TITLE
Resolve Fields in Schema Based On Condition

### ISSUE THREAD

**Issue by tnolan8** [MichalLytek/type-graphql#610]
Hi guys,

Let me preface with I'm relatively new to GraphQL so I might be missing something basic so apologises if that's that case! I'm currently using TypeORM + type-graphql and was wondering if there's any way to conditionally resolve a field based on a condition? My use case:

```javascript
// model/User.ts

@ObjectType()
@Entity()
export class User extends BaseModel {
    @Field(() => String)
    @Column({ unique: true })
    @IsNotEmpty()
    email: string;

   @Field(() => String)
    @Column({ default: "user" })
    @IsNotEmpty()
    role: string;
}

// resolvers/UserResolver.ts

@Resolver()
@injectable()
export class UserResolver {
    constructor(@inject("UserService") private userService: UserService) {}

    @Query(() => User)
    @UseMiddleware(authenticate)
    async getUser(@Arg("id") id: string): Promise<User> {
        const user = await this.userService.get(Number(id));
        return user;
    }
}
```
Users can have two different roles "admin" | "user". If an "admin" makes a request to getUser e.g. 
```javascript
query {
    getUser(id: "1") {
        email
        role
   }
}
```
: they should be able to see the `role` field on my model, but if a "user" was to submit this request I wouldn't want to resolve `role`. Is it possible to do something along the those lines using `@Field()`? This seems like it should be possible (I hope) without creating another Resolver/Type but I'm not sure how to go about it. Any help would very much be appreciated!

**Comment by MichalLytek** [comment]
You can't hide the field from the GraphQL schema.

But you can write a `@FieldResolver` (or `@Field` method) that will contain your business logic - read the user role from context, throw error (or return null) if not `admin`, return `user.role` 😉 

And you can also use [authorization feature](https://typegraphql.com/docs/authorization.html) for your purpose of limiting access to the field:
```ts
@ObjectType()
export class User {
  @Authorized("admin")
  @Field()
  role: string;
}
```

**Comment by tnolan8** [comment]
D'oh. I was even looking at the `authorization` example but missed the fact you can apply the decorator to the fields themselves! Much appreciated!
