### ISSUE TITLE
Feature Request: External schema instead of decorators

### ISSUE THREAD

**Issue by webnoob** [MichalLytek/type-graphql#613]
**Is your feature request related to a problem? Please describe.**
Consider this feature `class-validator` offers: https://github.com/typestack/class-validator#defining-validation-schema-without-decorators

This allows you to provide a scheme and not use decorators.

I have a DTO I would like to use on my client and my API (client receives the data from the API in the form matching the DTO). As it stands, I have to write 2 copies of that model, one with the `type-graphql` decorators and one without (as the client doesn't know what they are).

**Describe the solution you'd like**
I would like to provide an external schema for a model (see: https://github.com/typestack/class-validator#defining-validation-schema-without-decorators).

This would then allow me to share models between the API client but on the API side I can apply the schema so it builds the graphql schema as intended.

**Comment by MichalLytek** [comment]
> As it stands, I have to write 2 copies of that model, one with the type-graphql decorators and one without (as the client doesn't know what they are).

You can use shim to reuse the classes in client:
https://typegraphql.com/docs/next/browser-usage.html

> I would like to provide an external schema for a model (see: typestack/class-validator#defining-validation-schema-without-decorators).

You can use middlewares for that - create custom method decorator that gonna accept the schema to validate args against, just like the yup example:
https://typegraphql.com/docs/next/custom-decorators.html

**Comment by webnoob** [comment]
Oh, interesting! Sorry for not reading the docs properly and seeing that.

If I can use the shim so the classes can be used on the client, I won't need to specify the schema. I prefer decorators myself.
