### ISSUE TITLE
allow subscribe function to return promise

### ISSUE THREAD

**Issue by onichandame** [MichalLytek/type-graphql#617]
**Is your feature request related to a problem? Please describe.**
The custom subscribe function passed to a subscription resolver is required to return AsyncIterator synchronously. However, there is async business logic that I need to run in the subscribe function. e.g. add/remove subscription count after an expensive async function is resolved/rejected.

**Describe the solution you'd like**
as described in [this issue](https://github.com/graphql/graphql-js/issues/895), people are adding support for this feature.

**Describe alternatives you've considered**
I am manipulating the count before running the async function as a workaround. But this is not an exact match of our initial design, which is based on the business logic. Therefore some unprecedented errors may emerge.

**Additional context**
N/A

**Comment by MichalLytek** [comment]
The `ResolverFn` from `graphql-subscriptions` is synchronous, so we have to wait for the PRs to be merged:
https://github.com/apollographql/graphql-subscriptions/pull/220
https://github.com/apollographql/graphql-subscriptions/pull/197

**Comment by MichalLytek** [comment]
Related to #470 👀

**Comment by glen-84** [comment]
Looks like this may be unblocked soon.

**Comment by ericwooley** [comment]
One of those got closed. Is this still blocked?

**Comment by MichalLytek** [comment]
Probably not, will take a look at that soon 😉

**Comment by MichalLytek** [comment]
Solved by #1578 🔒 

https://github.com/MichalLytek/type-graphql/blob/v2.0.0-beta.4/src/decorators/types.ts#L31-L33
