### ISSUE TITLE
@FieldResolver missing injected property

### ISSUE THREAD

**Issue by Abdizriel** [MichalLytek/type-graphql#618]
**Describe the Bug**
By performing a query from a client (@react-apollo) and requesting a field which has to be resolved field resolver does not have an injected container property

**To Reproduce**
I have a scoped-container as a presented in documentation
```ts
(global as any).schema = (global as any).schema || await TypeGraphQL.buildSchema({
      authChecker,
      resolvers: Resolvers,
      container: ({ context }) => context.container,
    })
```

in case when user is authenticated I am adding it's tenant value to a container which works in all cases but not in @FieldResolver

```ts
context: async ({ req }: any) => {
  const requestId = Math.floor(Math.random() * Number.MAX_SAFE_INTEGER);
  const container = Container.of(requestId);

  const context = { 
    req, 
    requestId, 
    container,
    user: req.user, 
  };
  container.set("context", context);

  if(req.user) {
    const tenant = await req.user.tenant
    container.set('tenant', tenant)
  } else {
    container.set('tenant', null)
  }
  return context;
},
```

I've got a problem with all @FieldResolvers when I am doing a request from client, however if I am doing a request from playground it works without issues.

Here's is a example of a Resolver I have

```ts
@Service()
@Resolver(_ => Appointment)
export class AppointmentResolver {
  constructor(
    private readonly appointmentService: AppointmentService
    @InjectRepository(Appointment) private readonly appointmentRepository: Repository<Appointment>,
    @Inject("tenant") private readonly tenant: Tenant
  ) {}

  @FieldResolver(_ => [User])
  async employees(@Root() appointment: Appointment) {
    const entries = await appointment.appointmentToServices
    return Promise.all(entries.map(async entry => await entry.employee))
  }

  @Authorized()
  @Query(_ => Appointment)
  public async getAppointment(
    @Arg('appointmentId') id: string
  ) {
    try {
      return this.appointmentService.getById(id)
    } catch (err) {
      throw new ApolloError(err.message)
    }
  }

  @Authorized()
  @RelayedQuery(_ => Appointment)
  public async getAppointments(
    @RelayLimitOffset() {limit, offset}: RelayLimitOffsetArgs
  ) {
    try {
      return this.appointmentRepository.findAndCount({ 
        where: { 
          tenant: this.tenant,
        },
        skip: offset,
        take: limit
      })
    } catch (err) {
      throw new ApolloError(err.message)
    }
  }
}
```

**Expected Behavior**
The query from client would return a resolved field (for example **employees**)

**Logs**
```
GraphQL error: Service "tenant" was not found, looks like it was not registered in the container. Register it by calling Container.set("tenant", ...) before using service.
```

**Environment (please complete the following information):**

- OS: MacOS 10.15
- Node: 10.15
- Package version: 0.18.0-beta.10 
- TypeScript version: 3.8.3

**Comment by MichalLytek** [comment]
> I've got a problem with all @FieldResolvers when I am doing a request from client, however if I am doing a request from playground it works without issues.

Please try to reduce the amount of your app code and create a minimal reproducible code example.

Based on your report, I have no idea what "@FieldResolver missing injected property" means as you described issues with TypeDI, not TypeGraphQL.

**Comment by Abdizriel** [comment]
@MichalLytek It can be close - I got wrong error all the time and issue was different one.
