### ISSUE TITLE
Generating schema error

### ISSUE THREAD

**Issue by muco-rolle** [MichalLytek/type-graphql#619]
**Describe the Bug**
I'm new to typegraphql, and I saw similar bugs but for me is different I have a type Recipe with a resolver RecipeResolver  when I generate the schema I get  an error  message 'Type Recipe must define one or more fields.'

**To Reproduce**
This is my code 
```typescript
import 'reflect-metadata';

import { Field, Query, buildSchema, ObjectType, Resolver } from 'type-graphql';
import { ApolloServer } from 'apollo-server';

async function bootstrap() {
	try {
		@ObjectType()
		class Recipe {
			@Field()
			id: string;

			@Field()
			title: string;
		}

		@Resolver()
		class RecipeResolver {
			private recipesCollection: Recipe[] = [];

			@Query(returns => [Recipe])
			async recipes() {
				return await this.recipesCollection;
			}
		}

		const schema = await buildSchema({
			resolvers: [RecipeResolver],
			emitSchemaFile: {
				path: __dirname + 'schema.graphql',
				commentDescriptions: true
			}
		});

		const server = new ApolloServer({
			schema,
			playground: true
		});

		const { url } = await server.listen(4000);
		console.log(`🚀 running at ${url}`);
	} catch (error) {
		console.log(error);
	}
}

bootstrap();


```

**Environment :**

- OS: [Manjaro 18]
- Node (e.g. 12.16.2)
- Package version [0.17.6] (please check if the bug still exist in newest release)
- TypeScript version (3.8.3)

**Comment by MichalLytek** [comment]
It's not a reproducible example cause it lacks of `reflect-metadata` import.

**Comment by MichalLytek** [comment]
After fixing that import, everything works without any issue using your code to reproduce.

**Comment by muco-rolle** [comment]
@MichalLytek Actually, I forgot to add it in Reproduce section, so  I still has the issue

**Comment by MichalLytek** [comment]
Please create a repository with a minimal reproducible code example.

The code from the snippet you've provided work without any issues, I cannot reproduce the report.

**Comment by muco-rolle** [comment]
I was compiling with babel node after removing, use ts-node it works
