### ISSUE TITLE
Allow interception of @ArgsType() property keys

### ISSUE THREAD

**Issue by denkquer** [MichalLytek/type-graphql#621]
I would like to sanitize my arguments using a decorator that returns the new sanitized value like so:
```ts
@ArgsType()
export class UpdateArgs {
  @Field({ nullable: true })
  @Length(1, 255)
  @Sanitize()
  bio: string;
}
```
From what I've read and tried so far. Writing such a decorator is not trivial right now, is it?
I'd love a clue btw. <3

However it is super easy writing such a decorator when using inline `@Arg()` declarations such as:

```ts
@Resolver()
export class SomeResolver {
  @Query((returns) => Foo, { nullable: true })
  async updateFoo(
    @Arg('bio', (type) => String) rawBio: string,
    @Sanitize('bio') sanitizedBio: string
  ) { ... }
````

Here I am using a parameter decorator to inject a new value into an argument.
In my implementation I just get the args object and reasign the key. Thats why I have to pass it to my middleware aswell.

Would love feedback. Im new to decorators and advanced graphql stuff

Thanks

**Comment by denkquer** [comment]
I realize I can still use my approach with an `@ArgsType()` style declaration but I'd like to just overwrite the original value.

**Comment by MichalLytek** [comment]
It should be possible with something like that:

```ts
@ArgsType()
export class UpdateArgs {
  @Field({ nullable: true })
  @Length(1, 255)
  bio: string;

  @Sanitize()
  sanitizedBio: string = this.bio;
}
```

or that:

```ts
@ArgsType()
export class UpdateArgs {
  @Field({ nullable: true })
  @Length(1, 255)
  bio: string;

  @Sanitize()
  get sanitizedBio(): string {
    return sanitize(this.bio);
  }
}
```

However I haven't test that, it's just an idea.

The other approach would be to write `@Sanitize` decorator in a way that it register a getter on that property so it will return sanitized original value.

**Comment by denkquer** [comment]
Thanks a ton for your ideas. I did not thought of getters at all.

Your second approch definitely works. You don't even need a decorator in that case.
Inspired by your idea I came up with another approach.

__Setters__ 

While setters are cumbersome in js they work just as well as getters here:

```ts
  @Length(1, 255)
  sanitizedBio: string;

  @Field({ nullable: true })
  set bio(val: string) {
    this.sanitizedBio = sanitizeHtml(val, { allowedTags: [], allowedAttributes: {} });
  }
```
Whats cool about this approach is that they work super well with validation decorators, because the sanitized value is validated instead.

Playing with setters a bit I came up with this hacky idea:
```ts
  @Length(1, 255)
  @Field({ nullable: true })
  set bio(val: string) {
    Object.defineProperty(this, 'bio', {
      value: sanitizeHtml(val, { allowedTags: [], allowedAttributes: {} }),
      enumerable: true,
    });
  }
```
__Dont judge me! :rofl:__
While this is certainly not clean coding and performance propably also takes a hit..

_This works!_

It has the neat effect that I dont have to rename my field and can just drop the object in typeorm.
Obviously the setter is gone after the first assignment and sanitation won't work anymore but this is not to bad because I prevent reassignment through `Object.defineProperty()` anyway.

What do you guys think :laughing:

**Comment by MichalLytek** [comment]
This looks really weird but I'm glad that you find a somewhat hacky solution 😉
