### ISSUE TITLE
Can't use typedi Container on buildSchema 

### ISSUE THREAD

**Issue by arnoldmanuel** [MichalLytek/type-graphql#631]
**Bug**
When I try to use typedi I get an error.  

**To Reproduce**
To reproduce the bug/problem you can simply install typedi and use it like in the docs from type-graphql with typescript.

**Expected Behavior**
The code should compile fine.

**Logs**
My Error I get when running the code like in the docs from type-graphql 
https://typegraphql.com/docs/dependency-injection.html

throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
              ^
TSError: ⨯ Unable to compile TypeScript
src/index.ts (22,5): Argument of type '{ resolvers: string[]; container: typeof Container; }' is not assignable to parameter of type 'BuildSchemaOptions'.
  Object literal may only specify known properties, and 'container' does not exist in type 'BuildSchemaOptions'. (2345)

**Environment (please complete the following information):**

- OS: Windows
- Node 13.14.0
- Package version 1.0.0-rc.1
- TypeScript version 3.3.3333

**Additional Context**
It looks like buildSchema wants a container from type ContainerType, but the Container, which I import from typedi is just a Container. So I don't know, is that an bug from typedi or is buildSchema wrong? Because I do it exactly like in the docs and it doesn't work.

**Comment by MichalLytek** [comment]
Please upgrade your TS version and see if the error still happening.

**Comment by arnoldmanuel** [comment]
@MichalLytek Jesus, thanks, didn't see that...don't know why. Thanks a lot, such a simple bug haha.

**Comment by xgenvn** [comment]
I think this is because of the old version of typescript that `typeorm init` providing. Upgrade TS version and everything is good.
