### ISSUE TITLE
Authorization function executes multiple times for single field decorator @Authorized

### ISSUE THREAD

**Issue by khanakia** [MichalLytek/type-graphql#632]
**Describe the Bug**
Performance issue Authchecker executing the request multiple times

**To Reproduce**
Hi, I am using the authorization example from the source code require("./examples/authorization/index.ts"); and run the command yarn dev

**Expected Behavior**
Under the /examples/authorization/auth-checker.ts file I added the console.log(roles) on LINE 7
I am running the query and it returns the Access denied error so that good example is working but I see it runs the `authchecker` function 3 times which results in so shouldn't it run only 1 time as i have only one single `AUTHORIZED` decorator only on `ratings` all other fields are public
```
[ 'ADMIN' ]
[ 'ADMIN' ]
[ 'ADMIN' ]
```
```
query GetRecipesForAdmin {
  recipes {
    title
    description
    ratings
  }
}
```

**Logs**
<img width="1367" alt="Screenshot 2020-05-21 at 5 17 41 PM" src="https://user-images.githubusercontent.com/2174170/82556248-fc5b8280-9b86-11ea-9ca6-1c95c03da472.png">
<img width="627" alt="Screenshot 2020-05-21 at 5 17 11 PM" src="https://user-images.githubusercontent.com/2174170/82556214-ea79df80-9b86-11ea-9f90-bd29607de638.png">

**Environment (please complete the following information):**

- OS: OSX
- Node v12.12.0
- Package version "0.0.0-unreleased"
- TypeScript version ^3.8.3

**Additional Context**

**Comment by MichalLytek** [comment]
The `recipies` list contains 3 array items, so the field resolver `ratings` is called 3 times, that's why it invokes auth checker three times 😉

**Comment by khanakia** [comment]
Oh, i see. Thank you for clearing the confusing and also very fast response. :)
