### ISSUE TITLE
Unable to set description for ArgsType decorated entity

### ISSUE THREAD

**Issue by Mikhus** [MichalLytek/type-graphql#633]
**Describe the Bug**

When dealing with ArgsType there is no possibility to set entity description, decorator does not allow to bypass any arguments, which makes auto-generated docs weak.

**Expected Behavior**
Expected ArgsType to handle options, like:

```typescript
@ArgsType({ description: 'Some specific description for SomeArguments entity' })
class SomeArguments {
  // ...
}
```

**Comment by MichalLytek** [comment]
Could you should me where the args type description should appear in the SDL?

```ts
@ArgsType({ description: 'Some specific description for SomeArguments entity' })
class SomeArguments {
  @Field({ description: 'Some arg description' })
  someArg: string;
}

@Resolver()
class SomeResolver {
  @Query(returns => String, { description: 'Some query description' })
  someQuery(@Args() args: SomeArguments) {
    // ...
  }
}
```

```graphql
type Query {
  # Some query description
  someQuery(
    # Some arg description
    someArg: String!
  ): String!
}
```

**Comment by Mikhus** [comment]
Yeah, sorry, I've missed that it only defines the input args type in resolver, I have already found that it is differs from InputType, initially I thought ArgsType is InputType - my mistake. Thank you, and sorry for this dumb issue :)
