### ISSUE TITLE
[Docs] 1.0.0-rc.2 Examples links are broken 

### ISSUE THREAD

**Issue by vuki656** [MichalLytek/type-graphql#636]
**Describe the issue**
In the examples section on the **1.0.0-rc.2** version of the docs, none of the links work.

They all point to links from
https://github.com/MichalLytek/type-graphql/tree/1.0.0-rc.2/

For example **simple usage**:
https://github.com/MichalLytek/type-graphql/tree/1.0.0-rc.2/examples/simple-usage

**Are you able to make a PR that fix this?**
If I try to edit the docs from the website it sends me to the master branch version of the docs that has the correct link.

I could edit the links [here ](https://github.com/MichalLytek/type-graphql/blob/gh-pages/docs/1.0.0-rc.1/examples.html) but I'm not sure where the links should point or if that's the right place to edit the links. 

I'm open to fixing this If someone can let me know what is the correct path for the doc links.

**Comment by MichalLytek** [comment]
Closing via 07677b9 🔒
