### ISSUE TITLE
1.0.0-rc.2 ArgsType extends broken

### ISSUE THREAD

**Issue by darky** [MichalLytek/type-graphql#638]
**Describe the Bug**

Example of code:

```typescript

@ArgsType()
class Foo {
  @Field(type => Int})
  fieldFoo!: number; // only this field exists in args, because it parent class
}

@ArgsType()
class Bar extends Foo {
  @Field(type => Int)
  fieldBar!: number; // this field not exists in args, because it child class
}

@Resolver(() => Something)
class Resolver {
  @Query(returns => Something)
  async method(@Args() args: Bar) {
    // bla-bla
  }
}

```

On *0.17.6* version:

```graphql
method(fieldFoo: Int!, fieldBar: Int!): Something!
```

On *1.0.0-rc.2* version

```graphql
method(fieldFoo: Int!): Something!
```

**Comment by MichalLytek** [comment]
@darky Sorry but unable to reproduce:

https://github.com/MichalLytek/type-graphql/tree/07677b97f091bc33eee27305c0f2bae5fb89299f/tests/functional/interfaces-and-inheritance.ts#L113-L122

https://github.com/MichalLytek/type-graphql/blob/07677b97f091bc33eee27305c0f2bae5fb89299f/tests/functional/interfaces-and-inheritance.ts#L141-L144

https://github.com/MichalLytek/type-graphql/blob/07677b97f091bc33eee27305c0f2bae5fb89299f/tests/functional/interfaces-and-inheritance.ts#L368-L381

**Comment by darky** [comment]
Maybe it occured on 3 levels of extending
I have this case:

```typescript
class A {}

class B extends A {}

class C extends B {}
```

**Comment by MichalLytek** [comment]
@darky Please create a PR then that adds a failing test case which represents your use case 😉

**Comment by darky** [comment]
Sorry, seems problem from other place.
But I can't extract it from large project :(
Exists real regression between 0.x.x and 1.x.x, but I can't find real cause of problem.
Maybe later I find it and create proper bug or maybe it will be fixed in new versions of type-graphql :)

**Comment by MichalLytek** [comment]
> Exists real regression between 0.x.x and 1.x.x, 

The only potential change is that now the schema is build in isolation, so all the type classes has to be referenced somewhere in the `@Query(type => Foo)` or in other places.

Nothing has changed in the args inheritance and building in the last 2 years.

Feel free to reopen the issue if you are able to reproduce the issue 😉
