### ISSUE TITLE
Link in wiki to docs is blocked by ESET antivirus as potentially dangerous

### ISSUE THREAD

**Issue by Artimunor** [MichalLytek/type-graphql#641]
**Describe the Bug**
Link  in wiki to docs is blocked by ESET antivirus as potentially dangerous

**To Reproduce**
Click on link in github wiki with ESET Internet Security installed

**Expected Behavior**
This to appear:
https://typegraphql.com/docs/introduction.html

**Logs**
![image](https://user-images.githubusercontent.com/6189700/83323105-e754b280-a25c-11ea-9205-d2e973c6bdf4.png)

**Environment (please complete the following information):**
- OS: Windows 10 v2004

**Comment by MichalLytek** [comment]
Thanks, fixed! 💪
