### ISSUE TITLE
Query/Mutation returns `Unknown operation`

### ISSUE THREAD

**Issue by numToStr** [MichalLytek/type-graphql#651]
**Describe the Bug**
I have been using `type-graphql` w/ `fastify-gql`. Recently I updated both (as now both supports graphql v15) and Now, I am getting this error on every query/mutation. Previously It was working fine.

```
{
  "error": {
    "errors": [
      {
        "message": "Unknown operation named \"\"."
      }
    ],
    "data": null
  }
}
```
I don't know if this `type-graphql` error or `fastify-gql` error. If it is not `type-graphql` error, then I will happily report the issue in `fastify-gql` repo.

**Expected Behavior**
Should resolve the query/mutation

**Environment (please complete the following information):**

- OS: Manjaro Linux
- Node: 12.17.0
- Package version: 1.0.0-rc2
- TypeScript: 3.9.5

**Comment by MichalLytek** [comment]
If it works with apollo server and not with `fastify-gql`, it can't be a TypeGraphQL fault.

You can try to recreate the error using raw `graphql-js` and report the issue in fastify-gql repo.

**Comment by numToStr** [comment]
Thanks for your suggestion. I will try to recreate it with `graphql-js`.

**Comment by numToStr** [comment]
This issue is coming from `graphql-js` itself when an unnamed query gets executed which I was doing.

Fix: https://github.com/Urigo/graphql-modules/issues/1199#issuecomment-641900072
