### ISSUE TITLE
Cannot read property 'prototype' of undefined on UseMiddleware

### ISSUE THREAD

**Issue by ricosandyca** [MichalLytek/type-graphql#652]
**Describe the Bug**
I tried to add my custom middleware using `@UseMiddleware`, but got this `Cannot read property 'prototype' of undefined` error. 

**To Reproduce**

The middleware 
```ts
export const Logger: MiddlewareFn = async (_, next) => {
  return await next()
}
export default buildSchemaSync({ resolvers: [...], , globalMiddlewares: [Logger] })
```

The resolver
```ts
@Resolver()
export default class {
  @Query(() => String)
  @UseMiddleware(Logger)
  hello (): string {
    return 'world'
  }
}
```

**Logs**
`Cannot read property 'prototype' of undefined`

**Environment (please complete the following information):**

- OS: Linux
- Node: 12.6.3
- Package version: 1.0.0-rc.2
- TypeScript version: 3.9.5

**Additional Context**
I've tried to follow this step [https://typegraphql.com/docs/next/installation.html#typescript-configuration](https://typegraphql.com/docs/next/installation.html#typescript-configuration) but it didn't work

**Comment by MichalLytek** [comment]
> I've tried to follow this step typegraphql.com/docs/next/installation.html#typescript-configuration but it didn't work

So what is your `tsconfig.json`? Do you use babel?

**Comment by ricosandyca** [comment]
No, i'm not using Babel.

This is my `tsconfig.json` file
```json
{
  "compilerOptions": {
    "target": "es2018",
    "module": "commonjs",
    "lib": ["es2018", "esnext.asynciterable"],
    "outDir": "dist/",
    "rootDir": "src/",
    "strict": true,
    "esModuleInterop": true,                
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "skipLibCheck": true, 
    "forceConsistentCasingInFileNames": true
  }
}

```

**Comment by MichalLytek** [comment]
The only weird thing I can see is that the resolver class has no name 😛 

Please create a repository with a minimal reproducible code example and instructions how to run it.

**Comment by ricosandyca** [comment]
It's even working so far with no class name 😂

I just changed my `tsconfig.json` target to `es5` and `es3` and i got a different error `next is not a function`. The `property` error appear when i set the typescript target to `es2016` or higher.

**Comment by ricosandyca** [comment]
I don't know why, but it's working now. I just move my `Logger` middleware function outside the `buildSchemaSync` function's file. It works only on `es2015` or higher.
