### ISSUE TITLE
specify argument type on @Arg decorator

### ISSUE THREAD

**Issue by techo207** [MichalLytek/type-graphql#655]
I'm making a query like this: 
```typescript
	@Query( () => Int )
	async getNumber( @Arg( 'number' ) number: number ): Promise<number> {
		return number;
	}
```
How can i specify that input number should be integer type, I've tried use the same Int exported from the module but typescript complains  'Int' refers to a value, but is being used as a type here

```typescript
	@Query( () => [User] )
	async users( @Arg( 'where' ) where: FindableUserProperties, @Arg( 'order' ) order: OrdenableUserProperties,
		@Arg( 'skip' ) skip: Int, @Arg( 'take' ) take: number ): Promise<Array<User>> {
//     ↑ ↑ ↑   int  on skip is not a variable
		return User.find( {
			where, order, skip, take,
		} );
	}
```

Should be option to specify type on `@Arg()` decorator, something like:
```typescript
      @Arg( 'skip' , {type: Int})
```

**Comment by smolinari** [comment]
https://github.com/MichalLytek/type-graphql/blob/722e3a38c518527b0880f34bee925cbbb037e97a/examples/resolvers-inheritance/resource/resource.resolver.ts#L44

Scott

**Comment by MichalLytek** [comment]
@techo207 Thanks for ignoring the issue template and the link when "You want to ask a question or discuss with other community members" 😉
Next time such issue will be just deleted without any notice as GitHub is not a place for questions how to achieve something.

Thanks @smolinari for helping.
