### ISSUE TITLE
Extending base object type class without using implementation in SDL

### ISSUE THREAD

**Issue by serendipity1004** [MichalLytek/type-graphql#656]
When I create two classes like below

```
@ObjectType()
class Person{
    @Field()
    createdAt!: string;
    
    @Field()
    updatedAt!: string;
}

@ObjectType()
class Student extends Person{
    @Field()
    name!: string;
}
```

I have to query student like below

```
query getStudent{
    persons{
        __typename
        createdAt
        updatedAt
        ... on Student{
            name
        }
    }
}
```

But I think it would be useful if we can create a base class that does not create an actual class in SDL and just serve as a typescript base extension so that instead of above we can query student like below

```
query getStudent{
    students{
        __typename
        createdAt
        updatedAt
        name
    }
}
```

**Comment by MichalLytek** [comment]
Please show your `persons` query code (resolver).

**Comment by serendipity1004** [comment]
I was actually looking at code https://github.com/MichalLytek/type-graphql/blob/v1.0.0-rc.2/examples/interfaces-inheritance/resolver.ts

But I think I see it now. If I set the return type in the resolver as Student then I won't have to query for Person.

**Comment by MichalLytek** [comment]
That's how raw GraphQL works - if the return type is an interface, you can ask for all interface fields and then also for fields of other types implementing that interface but using a fragment syntax. It's not related to TypeGraphQL.
