### ISSUE TITLE
EmitSchemaFileOptions interface is not exported

### ISSUE THREAD

**Issue by spikyjt** [MichalLytek/type-graphql#663]
The interface `EmitSchemaFileOptions` is not exported from `utils/buildSchema.ts`, which makes typing a parameter to pass to the `emitSchemaFile` property of `buildSchema()` cumbersome.

I had to use `boolean | string | PrintSchemaOptions & { path?: string }` which is less than pleasant and difficult to grok.

**Comment by MichalLytek** [comment]
You can just use `BuildSchemaOptions["emitSchemaFile"]`.
Exporting `EmitSchemaFileOptions` won't help you because you would still need to use `boolean | string | EmitSchemaFileOptions`.

**Comment by spikyjt** [comment]
@MichalLytek no you can't because `emitSchemaFile` is potentially undefined, so can't be used as a type. Compile error is `error TS2339: Property 'emitSchemaFile' does not exist on type 'BuildSchemaOptions'`.

Exporting it would help, because at least the union types are all known, whereas the compound type has to be figured out by exploring the source. Plus you may not need to use all that, if know you are always passing an object of properties.

**Comment by MichalLytek** [comment]
![image](https://user-images.githubusercontent.com/10618781/85882622-e1141080-b7df-11ea-858d-5bb5c9ef348d.png)

**Comment by spikyjt** [comment]
My bad. I was importing `BuildSchemaOptions` (let the IDE do it for me and didn't notice!).

It would therefore be helpful to export this type independently. OK, it's not as cumbersome, but it's just as difficult to discover.

Can I change this ticket to ask for that? Or create a new one? Or will you not entertain it?

**Comment by MichalLytek** [comment]
I don't find useful exporting part of the type of the field while it can be easily accessed with the solution mentioned above.

**Comment by spikyjt** [comment]
@MichalLytek sorry I didn't mean exporting part of the type, now I understand better, I meant exporting `BuildSchemaOptions["emitSchemaFile"]` as `EmitSchemaFile` or similar. Anyway, if you prefer not to, it's your project! Thanks for getting back so quickly.
