### ISSUE TITLE
GraphQL 14 compatibility

### ISSUE THREAD

**Issue by tommy5dollar** [MichalLytek/type-graphql#665]
Can I just confirm that v1 won't work with GraphQL 14? I'd happily upgrade to GraphQL 15 but another package we're reliant on only supports 14 but I also need the schema isolation in v1. Is there a version with schema isolation and GraphQL 14 I could use temporarily?

**Comment by MichalLytek** [comment]
I'm afraid not - TypeGraphQL doesn't have a large company that sits behind, so I can't afford to support all past versions and new at the same time, working on two forks in parallel.

**Comment by tommy5dollar** [comment]
That's fine, thanks for the clarity.
