### ISSUE TITLE
[Doc/Discussion] Exporting types for the client, what's the best practice?

### ISSUE THREAD

**Issue by desmap** [MichalLytek/type-graphql#667]
Now, I am doing this:

E.g., in the class file `Movie.ts` where I declare and `export default` the `@ObjectType` I just export another
```
export type MovieType = <Pick<Movie, MutableKeys<Movie>>
```
which I can easily import into the client. Since in the build all type information is stripped away, the client shouldn't even know the full model (assuming tree-shaking is working properly without including the full class). Does it make sense?

**Comment by MichalLytek** [comment]
Please move your question to Gitter as it's the place for discussion with community.

![image](https://user-images.githubusercontent.com/10618781/86449723-dba35280-bd18-11ea-8ad0-e1ca38304dbf.png)

**Comment by desmap** [comment]
Just did

**Comment by desmap** [comment]
However, might be still a topic for the docs or not?

**Comment by MichalLytek** [comment]
I don't think so, you can just import type class type without any issues.
