### ISSUE TITLE
Return type of exported function has or is using private name 'PaginatedResponseClass'.

### ISSUE THREAD

**Issue by khanakia** [MichalLytek/type-graphql#670]
**Describe the Bug**
I am using the Pagination Generic Class from the example but getting error while tsc compiling https://github.com/MichalLytek/type-graphql/blob/master/docs/generic-types.md

**To Reproduce**
A quick guide how to reproduce the bug.
<img width="988" alt="Screenshot 2020-07-14 at 6 48 13 PM" src="https://user-images.githubusercontent.com/2174170/87430363-bc52d200-c602-11ea-9dfd-6c632b7486df.png">

**Expected Behavior**
Error should be remove.

**Logs**
```
OptionResolver.ts:13:7 - error TS4023: Exported variable 'PaginatedItemResponse' has or is using name 'PaginatedResponseClass' from external module "/Volumes/D/www/js/kookjs/kook_server/packages/core/gql/PaginatedResponse" but cannot be named.

const PaginatedItemResponse = PaginatedResponse(Option);
```

**Environment (please complete the following information):**

- OS: MAC
- Node v12.12.0
- Package version  "^1.0.0-rc.1"
- TypeScript version Version 3.9.6

**Comment by MichalLytek** [comment]
![image](https://user-images.githubusercontent.com/10618781/87430781-0083a980-c5e6-11ea-9746-6573ec450db3.png)

**Comment by khanakia** [comment]
Thanks Michal

Anyway i have created a workaround without using ANY type and loosing the TYPE Checking and tsc command does not give any error.

So i am just posting the solution for other peoples looking the way around.

I created a custom INTERFACE so my pagination.ts file will look like
```
import { Field, ObjectType, ClassType } from "type-graphql";
import { MetaOutput } from './MetaOutput'

export interface IPaginatedResponse {
  items: any;
  meta: MetaOutput;
}

export function PaginatedResponse<TItem>(TItemClass: ClassType<TItem>) {
  // `isAbstract` decorator option is mandatory to prevent registering in schema
  
  @ObjectType(`Paginated${TItemClass.name}Response`)
  class PaginatedResponseClass {
    // here we use the runtime argument
    @Field(type => [TItemClass])
    // and here the generic type
    items: TItem[];

    @Field(type => MetaOutput)
    meta: MetaOutput;
  }
  return PaginatedResponseClass;
}
```

And you can add the files in your Resolver.ts like this
```
import { PaginatedResponse, IPaginatedResponse } from "pagination";
const PaginatedItemResponse = PaginatedResponse(Option);
type PaginatedItemResponse = InstanceType<typeof PaginatedItemResponse>;

@injectable()
@Resolver()
export default class OptionResolver {
  constructor() {}

  @Query(() => PaginatedItemResponse)
  async options(): Promise<IPaginatedResponse> {
    const items = await Option.getMany();
    return {
      items,
      meta: {
        page: meta.page,
        limit: meta.limit,
        orderBy: meta.orderBy,
        total: total,
      },
    };
  }
}
```
As you can see I have the correct GQL Schema Generated 
<img width="600" alt="Screenshot 2020-07-14 at 7 29 09 PM" src="https://user-images.githubusercontent.com/2174170/87434601-4ea9a480-c608-11ea-9bc6-ba5cda33f86d.png">

**Comment by MichalLytek** [comment]
I would incline to put `declarations: false` instead of duplicating the class and interface types.

For API code you don't need to emit `d.ts` files, it's not a library published on npm 😃

**Comment by khanakia** [comment]
Hi Michal,

Thanks for the awareness. 👍 

I am aware of this. But i am building a Framework and Option is a package out of my MONOREPO and this package will be available to the NPM to download.  😃

**Comment by Distortedlogic** [comment]
this not solved? if using workspaces then declarations must emit
