### ISSUE TITLE
Using Parcel.js with NODE_ENV=production causes errors

### ISSUE THREAD

**Issue by geoyws** [MichalLytek/type-graphql#672]
**Describe the Bug**
Parcel.js can't seem to bundle a TypeGraphQL application. I haven't tried Webpack yet, but just wanted to add an issue here first to see if I can get any help.

**To Reproduce**
Clone any TypeGraphQL application repository and try to bundle it with Parcel.js and change NODE_ENV to `production`.

**Expected Behavior**
There should be an `Error: Cannot complete value of unexpected output type: __Schema!`.

**Logs**
![image](https://user-images.githubusercontent.com/1738396/88266571-fce8d480-cd01-11ea-947e-a32ee1b78e85.png)
The console.log here is from a monorepo but it doesn't work for a basic repo as well.

**Environment (please complete the following information):**

- OS: [e.g. Windows] MacOS Catalina 10.15.6
- Node (e.g. 10.5.0) v12.13.0
- Package version [e.g. 0.12.2] (please check if the bug still exist in newest release) 0.17.6
- TypeScript version (e.g. 2.8.2) 3.9.7

**Comment by MichalLytek** [comment]
I bet you need to turn of the minification of the bundle as it may produce plenty of bugs due to mangled identifiers.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒

**Comment by abrar30** [comment]
I tried to turn off minification , it still throw the same error 
`parcel build dist/index.js  --no-minify  --target node --bundle-node-modules --out-dir bundle`
This is how i run after bundle 
`NODE_ENV=production && node ./bundle/index.js`

used version for _**type-graphql and graphql**_
```javaScript
"type-graphql": "0.17.6",
"graphql": "14.5.8",
  node  v12.16.3
```
is there any way i can bundle it ? 
thanks

**Comment by geoyws** [comment]
Is there an example project that can help my team and I prove to our superiors that TypeGraphQL can bundle? Otherwise without bundling our docker image will be a hefty 200MB with a hefty build complexity
