### ISSUE TITLE
Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by Nondukishor** [MichalLytek/type-graphql#677]
{
  "errors": [
    {
      "message": "Cannot read property 'context' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "riders"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'context' of undefined",
            "    at new jwtMiddleWare (/media/nipu/works/civilized/rider-service/src/middleware/jwtMiddleware.ts:7:69)",
            "    at DefaultContainer.get (/media/nipu/works/civilized/rider-service/node_modules/type-graphql/dist/utils/container.js:16:51)",
            "    at IOCContainer.getInstance (/media/nipu/works/civilized/rider-service/node_modules/type-graphql/dist/utils/container.js:37:42)",
            "    at dispatchHandler (/media/nipu/works/civilized/rider-service/node_modules/type-graphql/dist/resolvers/helpers.js:74:65)",
            "    at Object.applyMiddlewares (/media/nipu/works/civilized/rider-service/node_modules/type-graphql/dist/resolvers/helpers.js:88:12)",
            "    at /media/nipu/works/civilized/rider-service/node_modules/type-graphql/dist/resolvers/create.js:27:26",
            "    at field.resolve (/media/nipu/works/civilized/rider-service/node_modules/graphql-extensions/src/index.ts:274:18)",
            "    at field.resolve (/media/nipu/works/civilized/rider-service/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:103:18)",
            "    at resolveFieldValueOrError (/media/nipu/works/civilized/rider-service/node_modules/graphql/execution/execute.js:502:18)",
            "    at resolveField (/media/nipu/works/civilized/rider-service/node_modules/graphql/execution/execute.js:460:16)"
          ]
        }
      }
    }
  ],
  "data": null
}

My Middleware code is 
`import { MiddlewareFn } from "type-graphql/dist/interfaces/Middleware";
import { ExpressContext } from "../Context/ExpressContext";
import { verify } from "jsonwebtoken";
import { Rider } from "../entity/Rider";
import { accessToken, refreshToken } from "../config/config";

const jwtMiddleWare: MiddlewareFn<ExpressContext> = async ({ context },next) => {
    
    const access_token: any = context.req.headers["access_token"] ? context.req.headers["access_token"] : null;
    const refresh_token: any = context.req.headers["refresh_token"] ? context.req.headers["refresh_token"] : null;

    try {
        if (!access_token) {
            throw new Error("Please provide JWT token with prefix");
        }
        if (!access_token.match(/Bearer [A-Za-z0-9\-\._~\+\/]+=*/g) ||!refresh_token.match(/Bearer [A-Za-z0-9\-\._~\+\/]+=*/g)) {
            throw new SyntaxError("Token Structure mismatch Please Add Your Prefix");
        }
        const token = access_token?.split(" ")[1];
        const rf_token = refresh_token?.split(" ")[1]

        verify(token, process.env.SECRET_KEY, async (err: any, decoded: any) => {
            if (err) {
                verify(
                    rf_token,
                    process.env.SECRET_KEY,
                    async (err: any, refreshDecode: any) => {
                        if (err) {
                            throw new Error("Sorry Token has been expired");
                        } else {
                            const retrieve: any = await Rider.findOne({where: { id: refreshDecode.payload.id }});
                            context.req.headers["access_token"] = (await accessToken( retrieve)) as any;
                            context.req.headers["refresh_token"] = (await refreshToken(retrieve.id)) as any;
                            next();
                        }
                    }
                );
            } else {
                context.payload = decoded as any;
                next();
            }
        });
    } catch (err) {
        throw new Error("Not Authenticated");
    }
};

export default jwtMiddleWare;
`

Resolver is 
`
  @Query(() => [Rider])
  @UseMiddleware(jwtMiddleWare)
  async riders(): Promise<Rider[] | any> {
    console.log("Hello I am from riders")
    const allRiders = await Rider.find();
    if (!allRiders) throw new Error("Sorry Riders not found");
    return allRiders;
  }
`

**Comment by MichalLytek** [comment]
https://www.apollographql.com/docs/apollo-server/api/apollo-server/#constructoroptions-apolloserver

```ts
  // Create GraphQL server
  const server = new ApolloServer({
    schema,
    context: ({ req, res }) => {
      return { req, res};
    },
  });
```

**Comment by Gaurav-Balyan** [comment]
> `at new jwtMiddleWare` means it's trying to create an instance of the class while your middleware is a function.
> 
> It means you haven't read the docs, especially the installation part about `tsconfig` requirements. Hence that's all my tips for fixing your mistake, go ahead, read it and apply the config properly.

Can you include a link here to the docs you are refering to.
