### ISSUE TITLE
Expand the contributing guidlines

### ISSUE THREAD

**Issue by outofgamut** [MichalLytek/type-graphql#682]
**Describe the issue**
The project could use a dedicated file for explaining to developers how to contribute. We can add a CONTRIBUTING.md file and move any documentation related to contributions out of README.md into it. This will make it easier for devs looking to help contribute to find the information they need. As a follow-up, or part of this PR, we could also bring some of the content from the links referenced in README.md's contribution section into the CONTRIBUTING.md, so the content is self-contained.

**Are you able to make a PR that fix this?**
Yes, I can make a PR for this.

**Additional context**

**Comment by MichalLytek** [comment]
Please use a proper template:

![image](https://user-images.githubusercontent.com/10618781/90806228-05422880-e31d-11ea-877f-54de736abdb6.png)

**Comment by outofgamut** [comment]
Updated to align with the documentation template

**Comment by MichalLytek** [comment]
> Yes, I can make a PR for this.

That's great! So please open a PR with suggested changes so we can then discuss any additional things needed to be done 😉

**Comment by outofgamut** [comment]
PR up!
