### ISSUE TITLE
Allow overwriting the output of Object properties with getter functions

### ISSUE THREAD

**Issue by Lobidu** [MichalLytek/type-graphql#686]
If an ObjectType has both a property and a function of the same name, TypeGraphQl will return the value of the property instead of the function, regardless of where the decorator is defined. This could cause unintended data leakage.

I think it would be preferential for a "getter" function to take precedence over a property value.

I came across this behavior when I tried to implement globally unique IDs for Objects (as inspired by GraphQL's Relay) where any object has a Global ID consisting of its object name and its numeric ID, then Base64 encoded eg. The Object `Account` with ID `1`, so its GlobalID would be `Account:1`, encoded: `QWNjb3VudDox`. 
The idea is that the GraphQL interface will always expose the GlobalID, while the server will work with the decoded ID as saved in Sequelize. Both the Public ObjectType and the internal Model should be working with a property named 'id', but with their respective values.

To do so, I tried to overwrite the result of the `id` field using a field resolver function:

```js
@ObjectType()
export default class Account extends Model {
    id!: number

    @Field(returns => ID)
    id(): string {
        return Buffer.from(`${this.constructor.name}:${this.id}`).toString('base64')
    }
}
```

However, the `Account` instance's `id` field seems to take precedence before the decorated function, so the resolver returns the unencoded `id` ("1").

As a workaround I have renamed the Model's `id` field to `_id` to signal its internal characteristic, which may be more explicit, too.

Style considerations aside, I still believe that the above behaviour should be considered. Keeping the current behaviour could lead to unexpected results or - worst case - information leakage when it is not the decorated property that is returned, but an undecorated property of the same name. This may become especially evident when working with inherited properties.

**Comment by MichalLytek** [comment]
@Lobidu 
I'm afraid you can't have both property and the method named the same 😕 
It's TypeScript compilation error, not a TypeGraphQL runtime issue.

So I'm afraid you need to have private `_id` property for internal id and a getter or method (with `@Field`) to return the relay id representation 😉

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
