### ISSUE TITLE
resolver <=> schema mapping on client side

### ISSUE THREAD

**Issue by Eluminati** [MichalLytek/type-graphql#687]
**Is your feature request related to a problem? Please describe.**
I want to combine the benefits of TypeORM with the benefits of graphQL and especially of Type-GraphQL.
I am planing to send querys to the server which can be answered by the local data base and will be updated later by the response from the server. Also I am planing to connect multiple client wia WebRTC and use a client as a server to relieve the server. So I have to pretent to call the "server" but in reality I am calling another client which has to resolve the graphQL query / mutation/ what ever. With graphQL I have a unified tool to do this.

Unfortunately type-graphql doesn't support schema <=>resolver mapping on client side but this has to work when I want to use this beautyful library. =)

I don't want to rule out that I made a mistake by just using the 

**Describe the solution you'd like**
The solution would be a client version of buildSchema together with webpack or other bundler (or even without a bundler).

**Describe alternatives you've considered**
I have considered to use this example: https://github.com/hasura/client-side-graphql/blob/master/examples/graphql-wrapper-rest/src/App.js

But in this case I have to write a new resolver in this style:
https://github.com/hasura/client-side-graphql/blob/master/examples/graphql-wrapper-rest/src/graphql/resolvers.js
while type-graphql can generate this resolvers. It would be very nice to have the same resolvers on server side and client side

**Comment by MichalLytek** [comment]
I'm sorry, but what do you mean by "resolver <=> schema mapping"?

> It would be very nice to have the same resolvers on server side and client side

Have you checked the apollo-client example?
https://github.com/MichalLytek/type-graphql/blob/v1.0.0/examples/apollo-client/src/apollo/client.ts

**Comment by Eluminati** [comment]
Ah thanks!

This is what I am searching for: `createResolversMap(schema);`
