### ISSUE TITLE
Describe why we need to use explicit to use Array or Promise

### ISSUE THREAD

**Issue by HKhademian** [MichalLytek/type-graphql#690]
**Describe the issue**
type-graphql can easily detect simple types like string and map to nonnullable string type in graphql.
but why there isn't any built-in (may disable by default) to convert:
1- simple types like string|null , string|undefied , [String] , [String|null] , [String] | null , ...
2- async functions return types in typescript: Promise<String|null> , Promise<Boolean> , ...
Is there ant limitation in Typescript Decorative api or can I/we help to implement this in the library?

**Comment by MichalLytek** [comment]
> For simple types (like string or boolean) this is all that's needed but due to a limitation in TypeScript's reflection, we need to provide info about generic types (like Array or Promise)

https://typegraphql.com/docs/types-and-fields.html

#296
