### ISSUE TITLE
Misleading documentation for custom GraphQLScalarTypes

### ISSUE THREAD

**Issue by ovstackelberg** [MichalLytek/type-graphql#692]
**Describe the issue**
An erroneous example implementation is used in https://github.com/MichalLytek/type-graphql/blob/master/docs/scalars.md#custom-scalars.

```typescript
parseValue(value: string) {
  return new ObjectId(value); // value from the client input variables
}
```

You can not rely on the assumption, that `value` is actually of type `string`.
If the client passes a `boolean` using query variables instead, `typeof value === "boolean"` although `string` is expected.
It is better to use the type `unknown` and check if it's of type `string`.

```typescript
parseValue(value: unknown) {
  if (typeof value === "string") {
    new ObjectId(value); // value from the client input variables
  }
  return null;
}
```

**Additional context**
The implementation of the `DateTime` scalar makes the same mistake and should be fixed.
https://github.com/MichalLytek/type-graphql/blob/master/src/scalars/isodate.ts

```
parseValue(value: string) {
  return new Date(value);
}
```

Passing `true` would not throw an error, but generate a date representing `1970-01-01T00:00:00.001Z`, because it gets interpreted as `1`.

**Comment by MichalLytek** [comment]
> You can not rely on the assumption, that value is actually of type string.

That's what happening when you trust other library docs:
https://www.graphql-tools.com/docs/scalars/#date-as-a-scalar

> The implementation of the DateTime scalar makes the same mistake and should be fixed.

I wanted to get rid of maintaining that scalars at all as they are just simple and common date iso and timestamp scalars. But I think it might be hard after the 1.0.0 release 😛

**Comment by MichalLytek** [comment]
Closing via 1e6b5ad 🔒
