### ISSUE TITLE
Resolver not passed to buildSchema appear in schema

### ISSUE THREAD

**Issue by wesselvanderlinden** [MichalLytek/type-graphql#693]
**Describe the Bug**
It seems that type-graphql adds a resolver to the schema even though I didn't add it to the `resolvers` option.

**To Reproduce**
```
import "reflect-metadata";
import {buildSchemaSync, Query, Resolver} from "type-graphql";

@Resolver()
class Something {
    @Query(() => Boolean)
    something() {
        return true;
    }
}

@Resolver()
class SomethingElse {
    @Query(() => Boolean)
    somethingElse() {
        return true;
    }
}

const schema = buildSchemaSync({resolvers: [Something]});

console.log(Object.keys(schema.getQueryType()!.getFields()));
```
The output will be `["something", "somethingElse"]` even though I expected it to be `["something"]`. It seems that the `SomethingElse` resolver is also added to the schema, even though I didn't pass it in the `resolvers` option.

**Expected Behavior**
I expect the schema return from either `buildSchema` or `buildSchemaSync` to only contain the queries and mutations defined in the resolvers passed as options argument.

**Environment (please complete the following information):**

- OS: Manjaro linux
- Node 14.8.0
- Package version 0.17.6
- TypeScript version 3.7.4

**Comment by MichalLytek** [comment]
Please update to v1.0.0

**Comment by wesselvanderlinden** [comment]
wow, I should've looked better. Sorry :)
