### ISSUE TITLE
Provide alternative to parameter decorators

### ISSUE THREAD

**Issue by vjpr** [MichalLytek/type-graphql#695]
Parameter decorators are not working with babel's `preset-typescript`. Could you provide a field decorator to configure them?

**Comment by vjpr** [comment]
https://github.com/WarnerHooh/babel-plugin-parameter-decorator allows parameter decorators to work.

I ran into an issue with an object destructor parameter though:

```
  async projects(@Args() {where}: ProjectsArgs) {
  }
```

**Comment by MichalLytek** [comment]
Please try to configure your babel setup according to some tips in #454.
