### ISSUE TITLE
TypeOrm Integration Fails if there is a Relation between entities: "Schema must contain uniquely named types but contains multiple types named" 

### ISSUE THREAD

**Issue by ap-vasu** [MichalLytek/type-graphql#696]
When integrating it with typeorm entities using the Nullable HOC concept which u have mentioned in other issue getting the same this error Schema must contain uniquely named types but contains multiple types named "CreateGroupInput".

```ts
export const GroupWrapper = (nullable: boolean) => {
  @InputType(nullable ? "UpdateGroupInput" : "CreateGroupInput")
  @ObjectType('GroupType')
  @Entity()
  class Group extends DefaultEntity {
    @Field({
      nullable: !nullable,
    })
    @PrimaryGeneratedColumn("uuid")
    _id: string;

    @Field({
      nullable,
    })
    @Column({
      unique: true,
    })
    name: string;
  }
  return Group;
}
```

```ts
export const GroupPlanWrapper = (nullable: boolean) => {
  @InputType(nullable ? "UpdateGroupPlanInput" : "CreateGroupPlanInput")
  @ObjectType("GroupPlanType")
  @Entity("group_plan")
  class GroupPlan extends DefaultEntity {
    @Field((type) => Group)
    @ManyToOne(
      () => Group,
      (group) => group._id,
      {
        cascade: true,
        eager: true,
      }
    )
    @JoinColumn({ name: "group_id" })
    group: Promise<Group>;

    @Field({ nullable })
    @Column()
    name: string;
  }

  return GroupPlan;
}  
```

_Originally posted by @ap-vasu in https://github.com/MichalLytek/type-graphql/issues/62#issuecomment-689312343_

Edited by @MichalLytek (snippets formatting)

**Comment by MichalLytek** [comment]
@ap-vasu Please show your usage of that code - how do you call those HOC function, how many times, in which places, etc.

**Comment by ap-vasu** [comment]
I am calling it in Group-entity once and in Group-resolver.

[group-entity.txt](https://github.com/MichalLytek/type-graphql/files/5193921/group-entity.txt)
[group-plan-entity.txt](https://github.com/MichalLytek/type-graphql/files/5193923/group-plan-entity.txt)
[group-resolver.txt](https://github.com/MichalLytek/type-graphql/files/5193924/group-resolver.txt)

**Comment by MichalLytek** [comment]
Your custom code is too complex, you haven't show the `NullableHOC`.
Unfortunately, I don't have enough capacity to debug custom user code.

So if you think it's a bug in TypeGraphQL, please try to debug your code and recreate the issue with minimal ammount of code, providing a simple case where it fails, like "fields are missing while extending the class".

**Comment by ap-vasu** [comment]
This NullableHOC was defined by you in the issue #134 . Any which ways I am in a rush to close this soon... so will have to fail DRY principle and repeat some code is what I think.

NullableHOC
```
export function NullableHOC<T>(
  hoc: (nullable: boolean) => T,
  nullable: true,
): HOCClass<typeof hoc, typeof nullable>;
export function NullableHOC<T>(
  hoc: (nullable: boolean) => T,
  nullable: false,
): HOCClass<typeof hoc, typeof nullable>;
export function NullableHOC<T>(hoc: (nullable: boolean) => T, nullable: boolean) {
  return hoc(nullable);
}

export type InstanceType<T> = T extends ClassType<infer R> ? R : never;

export type HOCClass<T extends Function, U extends boolean> = T extends (...args: any[]) => infer R
  ? U extends true ? ClassType<Partial<InstanceType<R>>> : R
  : never;
```

**Comment by MichalLytek** [comment]
I believe there's a silly mistake somewhere in your code (the one from snippet or other) and I can't debug your code made from issues snippets.

Please try to reproduce the issue `Schema must contain uniquely named types but contains multiple types named` without this big layers of nested HOC and generic classes to prove that it's TypeGraphQL fault somewhere.

I need a clear reproduction repository with a minimal code example (not a dump of half of your project). 
Ideally, a PR with a failing test case.

If you can to that, please open a separate GH issue with the reproduction steps.
