### ISSUE TITLE
Default Values are nullable but dont fallback for the value "null"

### ISSUE THREAD

**Issue by cjanietz** [MichalLytek/type-graphql#697]
**Describe the Bug**
Currently if you define an argument with a default value, TypeGraphQL marks it automatically as nullable (which is totally reasonable). TypeGQL arg converters will enrich the default value given absence nature of an argument for the field. However if you now send null (which I find reasonable) you will not see the default value but null, because convertArg will return the null value.

**To Reproduce**
Define a field with an argument and a default value and send null for that very argument.

**Expected Behavior**
If the value is null it should still default to the defined default value.

**Logs**
-

**Environment (please complete the following information):**

- OS: Linux
- Node 12
- Package version: 1.0.0
- TypeScript version: 4.0.2

**Additional Context**
It might not seem reasonable to send null for a missing argument, but Apollo Link (with Schema Stitching) actually does just that. It will null any nullable argument and therefore this automatically produces problem without intention.

**Comment by MichalLytek** [comment]
TypeGraphQL doesn't apply default values for input. It's done by `graphql-js`, TypeGraphQL is only the API wrapper.

Please try to recreate that with `graphql-js` and show me how it works for sending null while having default value set.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
