### ISSUE TITLE
Union type for argument and/or field

### ISSUE THREAD

**Issue by TulioMolina** [MichalLytek/type-graphql#698]
I just defined a union type of two object types following the [documentation](https://typegraphql.com/docs/unions.html)  by using the type-graphql's ```createUnionType``` function. I was hoping that I could use that union type as type for a resolver argument inside the arg decorator. Nevertheless, the reflection system was not able to properly assign that type to the argument. It would be nice to be able to define custom union types that could be used to define not only resolvers return type, as it currently allows, but also for arguments and object/input type fields.

**Comment by MichalLytek** [comment]
1) You can use union type as an object type field type:
https://github.com/MichalLytek/type-graphql/blob/2ccccc1d67ab160f583401d500730bae381cdcee/tests/functional/unions.ts#L79-L83

2) GraphQL spec doesn't allow to use unions in args or input types:
https://github.com/graphql/graphql-spec/pull/733

So you can't expect unions in args in TypeGraphQL anytime soon 🔒

**Comment by TulioMolina** [comment]
Thank you for your soon answer. I only tried to assign the union type to an argument and to a resolver return type; and as it didn't work out for the argument, I wrongly assumed it wasn't going to work for object type fields. A workaround could be to define a custom scalar type and assign the argument/input field to that scalar type, which would handle the raw input from the client and decide what to do depending on the received TS input type.

I consider it would be great for the documentation (which is pretty intuitive and helpful already) to explicitly mention that union types **can** be used to define object type fields.

**Comment by MichalLytek** [comment]
>  A workaround could be to define a custom scalar type and assign the argument/input field to that scalar type, which would handle the raw input from the client and decide what to do depending on the received TS input type.

The common workaround is you have N fields input type where all fields are nullable. Then in your mutation/query you check manually if only one of the fields have value and boom you have input union 😅 That's how the new `@oneOf` directive gonna work soon.

> I consider it would be great for the documentation (which is pretty intuitive and helpful already) to explicitly mention that union types can be used to define object type fields.

I see that the official GraphQL docs doesn't mention that too. Could you make a PR and add a side note with that info? Thanks! 👍

**Comment by TulioMolina** [comment]
> The common workaround is you have N fields input type where all fields are nullable. Then in your mutation/query you check manually if only one of the fields have value and boom you have input union  That's how the new `@oneOf` directive gonna work soon.

That sounds neat, I think I'll go for it. I'm fairly new to graphql and TS in general, so I wasn't aware of that technique. Thank you!





> I see that the official GraphQL docs doesn't mention that too. Could you make a PR and add a side note with that info? Thanks!

Never mind. Of course, no problem.
