### ISSUE TITLE
Non-arrow functions are not supported as middleware

### ISSUE THREAD

**Issue by mhagmajer** [MichalLytek/type-graphql#699]
Middleware defined as a regular function does not work:

```typescript
export async function ResolveTime({ info }, next) {
  const start = Date.now();
  await next();
  const resolveTime = Date.now() - start;
  console.log(`${info.parentType.name}.${info.fieldName} [${resolveTime} ms]`);
};
```

TypeGraphQL as of 1.0 [checks for prototype](https://github.com/MichalLytek/type-graphql/blob/v1.0.0/src/resolvers/helpers.ts#L99) when determining if a middleware is a class or an arrow function. Non-arrow do have a prototype so this check won't work for them.

**Comment by MichalLytek** [comment]
Unfortunatelly, there's nothing I can do about it.

You need to use arrow function `const MyMiddleware: MiddlewareFn` or a class implementing an interface.

**Comment by mhagmajer** [comment]
> Unfortunatelly, there's nothing I can do about it.

@MichalLytek so you are saying there is no way to differentiate between an arrow function, regular function and an EcmaScript class?

**Comment by MichalLytek** [comment]
I believe there are some hacky ways with parsing `toString()` but they are fragile and relying on not using compiler/transiplers.

In regular function you don't have type safety like interface with classes or `MiddlewareFn` in const arrow function so I don't plan support regular functions in middlewares, it makes no sense to invest time into it while it gives no added value.
