### ISSUE TITLE
@types/node in both dependencies and devDependencies

### ISSUE THREAD

**Issue by MatthiasKunnen** [MichalLytek/type-graphql#700]
**Describe the Bug**
`@types/node` is both in dependencies and devDependencies. This causes Yarn to install the latest version (^14.6.0) from the devDependencies.

Yarn generates the following in `yarn.lock`:
```yaml
type-graphql@^1.0.0:
  version "1.0.0"
  resolved "https://registry.yarnpkg.com/type-graphql/-/type-graphql-1.0.0.tgz#7413fd5ff959f1a738615ecfad6e2ca2d68572bf"
  integrity sha512-ejXSEmqewrv9MX/0XOSKBc7utjrF6N0UeZJQ0w/R/Ene4Or9/cA+8iLQnuqgBDlNpXIdcq4rSvrk3mUMAIqOQA==
  dependencies:
    "@types/glob" "^7.1.3"
    "@types/node" "^14.6.0"
    "@types/semver" "^7.3.3"
    glob "^7.1.6"
    graphql-query-complexity "^0.7.0"
    graphql-subscriptions "^1.1.0"
    semver "^7.3.2"
    tslib "^2.0.1"
```
Note the dependency not stating `"@types/node" "*"`.

**To Reproduce**
Install `type-graphql` with yarn and look at `yarn.lock`

**Expected Behavior**
A module should not be in both `devDependencies` and `dependencies`.

**Environment:**

- OS: Ubuntu 18.04
- Node (e.g. 10.5.0) 12.18
- Package version 1.0.0
- TypeScript version 4.0.2
- Yarn: 1.22.5

**Comment by MichalLytek** [comment]
The `*` means that install any version. NPM supports that by checking if you already have `@types/node` in your `node_modules` - if so, it uses that version, and if not, it's installing the `@latest` one.

> This causes Yarn to install the latest version (^14.6.0) from the devDependencies.

So it's a Yarn bug 🤷‍♂️ I have no idea why any package manager should install dev dependencies of 3rd party library, it's against npm spec.

**Comment by MatthiasKunnen** [comment]
Is there any reason to have `@types/node` in `devDependencies` too? Is it for development?

**Comment by MichalLytek** [comment]
Yes, `devDependencies` is for development and having control over the version and `"@types/node":"*"` is for forcing "peer dependency" installation.

**Comment by MatthiasKunnen** [comment]
Alright, I'll take this issue to Yarn
