### ISSUE TITLE
no exported member formatArgumentValidationError

### ISSUE THREAD

**Issue by jayson-valentino** [MichalLytek/type-graphql#706]
import { formatArgumentValidationError } from "type-graphql";

[INFO] 16:44:04 Restarting: /Users/jaysonvalentino/Desktop/typeqraphql/src/index.ts has been modified
Compilation error in /Users/jaysonvalentino/Desktop/typeqraphql/src/index.ts
[ERROR] 16:44:05 ⨯ Unable to compile TypeScript:
src/index.ts:5:10 - error TS2305: Module '"../node_modules/type-graphql/dist"' has no exported member 'formatArgumentValidationError'.

5 import { formatArgumentValidationError } from "type-graphql";

**Comment by MichalLytek** [comment]
I think it was removed over a year ago, so you need to update to `v1.0.0` instead of relying on outdated blog articles.
