### ISSUE TITLE
FieldResolver's nullable argument is not set to specified defaultValue when it is set to null

### ISSUE THREAD

**Issue by malisetti** [MichalLytek/type-graphql#707]
**Describe the Bug**
@Arg('skip', { nullable: true, defaultValue: 0 }) skip?: number

when skip is set to null in the graphql query, field resolver function is not receiving it as 0

**Expected Behavior**
skip is set to 0 its default value

**Environment (please complete the following information):**

- OS: Ubuntu 18.04
- Node v12.13.1
- Package version ^0.17.5
- TypeScript version 3.7.2

**Comment by smolinari** [comment]
What happens, if you remove the `nullable` property?

Scott

**Comment by malisetti** [comment]
@smolinari the current behavior is proper. When `nullable` is not set on the argument it is set to the defaultValue. It is set to null when it is nullable.
