### ISSUE TITLE
Access argument of root object in FieldResolver

### ISSUE THREAD

**Issue by maurocolella** [MichalLytek/type-graphql#708]
**Is your feature request related to a problem? Please describe.**
I have a specific use case which I am having a difficult time solving.

I have an entity, which exposes "revisions". Such as:
```
query{
    getEntity(id: "xxxx") {
        revisions { edges { node { activeFrom } } }
    }
}
```

But while some users should be able to access all revisions, some users should only be able to access the most recent revision.

`revisions` is resolved using a `@FieldResolver`. Now, in my query, I want to sometimes override privileges, and _selectively_ display all revisions or just the latest. Something like:

```
getEntity(id: "xxxx", active: true) {
```

Passed down to my field resolver. 

Currently, I can't find a good way to achieve this unless I am missing something.

**Describe the solution you'd like**
Perhaps a field decorator that exposes the parent query somehow. Something like `@Root` but in this case I also want the arguments. Not just the resolved parent entity.

**Describe alternatives you've considered**
The most obvious alternative is to tightly couple revisions with the root entity. Not preferred for obvious reasons. I have looked at and am looking at ways to use middlewares.

**Additional context**
No other context to add for now.

**Comment by MichalLytek** [comment]
Please show your generated schema SQL

**Comment by maurocolella** [comment]
```
type ParentEntity {
  id: ID!
  name: String
  revisions(
    before: ID
    after: ID
    first: Int = 10
    last: Int = 10
  ): RevisionConnection
}
```

```
type Revision {
  id: ID!
  activeFrom: DateTime!
  parent: ParentEntity!
}
```

The resolver (of Entity) is:
```
  @FieldResolver(() => RevisionConnection)
  async revisions(
    @Root() parent: ParentEntity,
    @Args(() => GetRevisionArgs) arguments_: GetRevisionArgs,
    @CurrentSession() user: AuthContext,
  ) : Promise<Connection<Revision>> {
    const entityRevisions = await this.entityService.getRevisions(
      entity.id,
      Object.values(Access).includes(user.access) &&
        user.access === Access.MEMBER,
    )

    return connectionFromArray(payAndConditionsRevisions || [], arguments_)
  }
```

This currently works based on privileges from the auth context.

My problem is that when I retrieve an entity (`getEntity`), I want to pass an argument to override whichever visibility setting.

**Comment by MichalLytek** [comment]
I need to see the whole graph, your snippets are missing e.g. `RevisionConnection`

**Comment by maurocolella** [comment]
I am sorry, much of the graph is under NDA. `RevisionConnection` is defined as:

```
type RevisionConnection {
  pageInfo: PageInfo!
  edges: [RevisionEdge!]!
}

type RevisionEdge {
  node: Revision!
  cursor: ID!
}

type PageInfo {
  hasNextPage: Boolean
  hasPreviousPage: Boolean
  startCursor: ID!
  endCursor: ID!
}
```

**Comment by MichalLytek** [comment]
> I want to sometimes override privileges, and selectively display all revisions or just the latest

Why you can't just put the `active` arg on the `revisions` field resolver?

If you are supposed to return different subset of `revisions` based on the state of `entity`, I would add some arbitrary data to the object returned from `getEntity` like `{ ...entity, isActive: true }` so the you can access that value in field resolver and return filtered `revisions`.

Your problem with accessing args of parent isn't scoped to TypeGraphQL, so you can search for other GraphQL solution on stackoverflow etc.

**Comment by maurocolella** [comment]
@MichalLytek both propositions make sense in that context, thanks, although there are cases where access to the request state, rather than the parent entity's state, makes sense for example when parent and child are stored in separate databases.

One might genuinely want to lookup some additional information from the parent.

About this, the `Apollo` documentation seems to mention a per-state context:
https://stackoverflow.com/questions/39732223/graphql-pass-args-to-sub-resolve#answer-56137694

But as you point out, I don't think this refers to arguments or the accessibility of arguments across child resolvers.

I am still genuinely wondering if that's a feature that could make sense.

**Comment by MichalLytek** [comment]
In theory field resolvers represent connection between the nodes of the graph that can be accessed from different queries, like:
```graphql
query AllUsers {
  users(isActive: true) {
    friends {
      # ...
    }
  }
}
```
And 
```graphql
query CurrentUser {
  me {
    friends {
      # ...
    }
  }
}
```
So your field resolver should rely only on parent object `@Root` and its own arg to resolve because otherwise you loose the "implement once, use everywhere` paradigm and in every user-related query/mutation or even some other side of relation like `post -> author -> friends` you gonna need to add some data manually.

**Comment by guguji5** [comment]
hi @maurocolella , I face the same issue, How you figure out of that, I have a query like below.
```
{
  accounts(account_name: "guguji5") {
	total
        item {
	        account_id
	        account_name
	        email
     }
  }
}
```
the `accounts` field contain a `total` and `item`, both are fuzzy match the argument `account_name`. so the item @FieldResolver must get the argument of `accounts`, but I can't.

**Comment by maurocolella** [comment]
Hi @guguji5 . I think I went with the argument on the FieldResolver itself.

> your field resolver should rely only on parent object @Root and its own arg

You have an `@Root` argument that can be accessed in the FieldResolver. In your case, does it contain the account_name or a reference to the account?

See: https://typegraphql.com/docs/0.17.0/resolvers.html#field-resolvers

**Comment by guguji5** [comment]
> Hi @guguji5 . I think I went with the argument on the FieldResolver itself.
> 
> > your field resolver should rely only on parent object @root and its own arg
> 
> You have an `@Root` argument that can be accessed in the FieldResolver. In your case, does it contain the account_name or a reference to the account?
> 
> See: https://typegraphql.com/docs/0.17.0/resolvers.html#field-resolvers

Thank you @maurocolella  for your reply, as I know the @Root argument can get the value of `accounts`, but not to get the query object of `accounts`

My original plan is making twice connection mysql to fetch total and item, the two sql both need `account_name` as LIKE field. so I need access the argument of `accounts` in item' FieldResolver.

But I find it should connecting mysql once to fetch the items, and calculate the `total` on items' sum.

My confusion is how to access the parent obj like original graphql param like that
<img width="735" alt="image" src="https://user-images.githubusercontent.com/17986248/211703951-725d5c03-e2ee-4903-95e0-990722df218a.png">

**Comment by maurocolella** [comment]
Hi @guguji5 .

You're welcome. The point being: as hinted at in the answer by @MichalLytek , my own initial approach was not optimal, and I was trying to work against the framework.

It's difficult for me to provide additional help without context, but I would suggest trying to look at the problem in different ways. Seeing if there are arguments that you could pass explicitly for example, at any level of the hierarchy.
