### ISSUE TITLE
Inherited extensions are being left behind

### ISSUE THREAD

**Issue by MechJosh0** [MichalLytek/type-graphql#709]
**Describe the Bug**
Using `@Extensions` on an inherited class or field does not get remembered in the parent class.

On the parent model extensions are working perfectly fine, but when I try to use the same extensions on a model which is inherited they're not available in the middleware.

**To Reproduce**
```typescript
// Person.model.ts
@Extensions({ parentUser: true })
@ObjectType()
export default class Person extends BaseModel {
	@Extensions({ fieldUser: true })
	@Field()
	name: string;
}
```

```typescript
// Base.model.ts
@Extensions({ parentBase: true })
@ObjectType()
export default class BaseModel {
	@Extensions({ fieldBase: true })
	@Field()
	id: number;
}
```

```typescript
// Logger.Middleware.ts
export class LoggerMiddleware implements MiddlewareInterface<Context> {
	constructor(private readonly logger: Logger) {}

	use({ info }: ResolverData, next: NextFn) {
		const parent = info.parentType.toConfig().extensions || {};
		const field = info.parentType.getFields()[info.fieldName].extensions || {};

		console.log(parent);
		// {
		//	parentUser: true,
		// }

		console.log(field);
		// {
		//	fieldUser: true,
		// }

		return next();
	}
}
```

**Expected Behavior**
```typescript
// Logger.Middleware.ts
// ...

		console.log(parent);
		// {
		//	parentUser: true,
		//	parentBase: true,
		// }

		console.log(field);
		// {
		//	fieldUser: true,
		//	fieldBase: true,
		// }
// ...
```

**Environment (please complete the following information):**

- OS: Mac
- Node: v13.14.0
- Package version: v1.0.0
- TypeScript version: v3.7.5

**Additional Context**
I'm using TypeORM: v0.2.22.

**Comment by MichalLytek** [comment]
@MechJosh0 Thanks for reporting this issue!

That feature was the community contribution and I've forgotten about tests for inheritance of that extensions values.
There were two places in code to fix and now it should be working 😉 

Closing via cc4048a 🔒
