### ISSUE TITLE
graphql-scalars integration

### ISSUE THREAD

**Issue by carlocorradini** [MichalLytek/type-graphql#716]
**Is your feature request related to a problem? Please describe.**
Can we add more scalar types?
The library [graphql-scalars](https://github.com/Urigo/graphql-scalars) is 100% Typescript based and offers a huge amout of custom GraphQL scalar types for creating precise type-safe GraphQL schemas.
In my opinion it's a huge advantage integrating TypeGraphQL with the graphql-scalars library where they both benefit.

**Describe the solution you'd like**
An integration where we map the graphql-scalars into fully supported TypeGraphQL scalars.

**Additional context**
Recently I found the issue dealing with Date only and UUID scalars. I don't want to map Date with DateTime type and UUID with a simple string type.

> Thanks in advance for your help.

_What do you think about this feature request?_

**Comment by MichalLytek** [comment]
You can use any scalars you want in TypeGraphQL:
https://typegraphql.com/docs/scalars.html#custom-scalars

**Comment by chav-aniket** [comment]
@carlocorradini were you able to add scalar resolvers to your buildSchema? I can add typedefs but can't figure out how to add resolvers

**Comment by carlocorradini** [comment]
Take a look here : <https://github.com/GiovanniZotta/fog_cloud_project/blob/main/graphmarket/libs/entities/product/Product.ts>

Simply import and add the type ;)

**Comment by carlocorradini** [comment]
Exactly, if you want to map a class from/to a scalar, omitting the type in @Field() simply add it to scalarsMap.

**Comment by chav-aniket** [comment]
right right, I was trying to add them all but on second thought it does seem more reasonable to only add what will be used. Thank you for all the explanation!
