### ISSUE TITLE
Using GraphQLJSONObject from graphql-type-json with default values results in Cannot convert value to AST: {}.

### ISSUE THREAD

**Issue by pellejacobs** [MichalLytek/type-graphql#719]
**Describe the Bug**

Using GraphQLJSONObject from the graphql-type-json with default values results in `Cannot convert value to AST: {}.` This seems similar to a question asked on gitter back in February: https://gitter.im/type-graphql/Lobby?at=5e3c8865bfe65274eae4ae66

Practically, this causes in errors when using an ORM such as sequelize-typescript with `@Column({ defaultValue: {} })`

**To Reproduce**

Following code fails:

```typescript
import 'reflect-metadata'
import * as path from 'path'
import { buildSchemaSync } from 'type-graphql'
import { GraphQLJSONObject } from 'graphql-type-json'
import { Arg, Field, InputType, Mutation, ObjectType, Query, Resolver } from 'type-graphql'

@ObjectType()
@InputType('RecipeInput')
class Recipe {
  @Field(type => String) title: string
  @Field(type => GraphQLJSONObject) json: any = {}
  // @Field(type => GraphQLJSONObject) json: any // this line works fine.
}

@Resolver(of => Recipe)
export class RecipeResolver {
  @Query(returns => Recipe)
  async recipes() {
    return []
  }

  @Mutation(returns => Recipe)
  async createRecipe(@Arg('recipe', type => Recipe) recipe) {
    return {}
  }
}

buildSchemaSync({
  resolvers: [RecipeResolver],
  emitSchemaFile: path.resolve(__dirname, 'schema.gql'),
})
```

I have to admit that it is not clear from the documentation whether the usage of ObjectType & InputType on the same class is officially supported, although it is very convenient.

**Environment (please complete the following information):**

- OS: MacOS
- Node: 14
- Package version: 1.0.0
- TypeScript version: 4.02

**Comment by MichalLytek** [comment]
It can't be supported because input types are different than object types - fields can have resolvers, field types can be an interfaces or an union. From the other side, input type fields have default values while object type ones not.

The FAQ solution is just an info about workaround if you really have dumb simple class with 3 string fields. So if you encounter some issue, first try to split them and then report issue.

**Comment by pellejacobs** [comment]
Fair enough, if it is not supported then I can close this issue. Splitting them out works fine, as there is no longer any reason to define a default value on the property as you can define any default input value with `@Field({ defaultValue: {} })`. Thanks!
