### ISSUE TITLE
Mutation response is always empty object when using createUnionType

### ISSUE THREAD

**Issue by rebirthtobi** [MichalLytek/type-graphql#720]
**Describe the Bug**
I am using `createUnionType` to create a union response but i am always getting an empty object as a response.

**To Reproduce**
This is the union created
```
const signUpResponse = createUnionType({
    name:  "signUpResponse",
    types: () => [User, ErrorResponse],
});
```

This is the mutation function
```
@Mutation(returns => signupResponse)
    async signUp(@Arg("input", returns => SignUpArgs) signUpArgs: SignUpArgs):
        Promise<User | ErrorResponse> {
        if (signUpArgs.password !== signUpArgs.confirmPassword) {
            return Object.assign(
                new ErrorResponse(),
                {
                    message:    "incorrect data",
                    identifier: signUpArgs.email,
                    error:      "password and confirm password does not match",
                },
            );
        }

        const userResponse = await this.userProvider.createUser({
            ...signUpArgs,
            password: getEncryptedPassword(signUpArgs.password),
        });

        if (userResponse instanceof ErrorResponse) {
            return userResponse;
        }

        return userResponse;
    }
```

This is play ground
<img width="1176" alt="Screenshot 2020-10-07 at 06 29 53" src="https://user-images.githubusercontent.com/20771062/95291025-89695480-0866-11eb-9a06-a7ef51f1ccb8.png">

**Expected Behavior**
I expect it to return the error response when error response is return and also user when user is returned

** Logs**
I do get this inside by console 
`No metadata found. There is more than once class-validator version installed probably. You need to flatten your dependencies.`

**Environment (please complete the following information):**

- OS: Mac Catalina
- Node: v12.18.4
- Package version: ^1.0.0
- TypeScript version: ^3.6.3

**Additional Context**
I try to return a single object type (ErrorResponse) it returned fine

**Comment by MichalLytek** [comment]
This happens if you return a plain object, not an instance of object type class from your resolver. 
Please double check if `userResponse` is instance of `User` class. 

If you still think it's TypeGraphQL fault, please replace your custom services with simple:
```ts
const user = new User();
user.property = value;
// ...
return user;
```

**Comment by rebirthtobi** [comment]
@MichalLytek  i tried the following

1. i use the resolveType in createUniontype
```
const signupResponse = createUnionType({
    name:        "SignupResponse",
    types:       () => [User, ErrorResponse] as const,
    resolveType: value => {
        if ("error" in value) {
            return ErrorResponse;
        }
        if ("firstName" in value) {
            return User;
        }

        return undefined;
    },
});
```
Then i return an object, i still got the same empty object

2. I tried using this
```
const error = new ErrorResponse();
            error.message = "incorrect data";
            error.identifier = signUpArgs.email;
            error.error = "password and confirm password does not match";

            return error;
``` 
with the resolve type above but i still got an empty object

3. I tried only
```
const error = new ErrorResponse();
            error.message = "incorrect data";
            error.identifier = signUpArgs.email;
            error.error = "password and confirm password does not match";

            return error;
```
Without the resolveType and still got an empty object

4. I have also tried returning a plain object without the resolveType but still got an empty object

Currently i have remove the unionType so that i can continue on what i am working on

**Comment by MichalLytek** [comment]
@rebirthtobi Unfortunately, I cannot reproduce your issue:
```ts
const testUnion = createUnionType({
  name: "testUnion",
  types: () => [User, ErrorResponse],
});

@ObjectType()
class User {
  @Field()
  name: string;
}

@ObjectType()
class ErrorResponse {
  @Field()
  message: string;
}

@Resolver()
class TestResolver {
  @Query(returns => testUnion)
  async test(): Promise<typeof testUnion> {
    const user = new User();
    user.name = "username";
    return user;
  }
}
```

![image](https://user-images.githubusercontent.com/10618781/95488900-650c9580-0996-11eb-818d-455c974490e1.png)

Please create a repository with a minimal reproducible code example.
Minimal means not a half of your project. Ideally a one resolver with one query/mutation, the affected object types and union type. Maybe it's because of outdated dependencies or some config issue.

**Comment by rebirthtobi** [comment]
Okay,I will do.

I'm using graphql-modules with this package though

**Comment by MichalLytek** [comment]
I bet it's the issue in `graphql-modules` if you merge `User` object type from different modules - it has to create then a new `GraphQLObjectType` instance, so returning the original one in `createUnionType` fails to determine the correct final schema type.

There are also other issues with GraphQL Modules reported:
https://github.com/Urigo/graphql-modules/issues/1214

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
