### ISSUE TITLE
Resolver thrown errors not caught when no source maps are generated

### ISSUE THREAD

**Issue by rlxu** [MichalLytek/type-graphql#721]
**Describe the Bug**
When calling a query/mutation on a resolver that throws an error, the corresponding error is not captured. Instead we get the error response "ENOENT: no such file or directory, open '.next/server/pages/api/graphql.js.map'". This happens when Next.js source maps are not generated.

**To Reproduce**
Given a simple query resolver like this:
```
@Resolver()
class ExampleResolver {
  @Query(() => String)
  example() {
    throw new Error("This is the error I want to receive");
  }
}
```
And a middleware that catches and re-throws errors:
```
export const ErrorInterceptor: MiddlewareFn<any> = async ({}, next: NextFn) => {
  try {
    console.log("middleware before next");
    const response = await next();
    console.log("middleware after next");
    return response;
  } catch (err) {
    console.log("middleware catch");
    throw err;
  }
};
```
When running a query on `example`, the only line that gets logged is "middleware before next" (`next()` never returns nor gets caught). Instead, by the time we get to ApolloServer's `formatError`, we just the ENOENT error above.

Here is an example with our actual app in playground:
![Screen Shot 2020-10-07 at 4 18 15 PM](https://user-images.githubusercontent.com/25339083/95398200-070a8000-08ba-11eb-92af-72972336e75b.png)

**Expected Behavior**
The error thrown in the resolver should be caught by the middleware, and reflected in the ultimate graphql query response, regardless of whether source maps are generated by Next.js or not.

**Logs**
In "To Reproduce" section above.

**Environment (please complete the following information):**

- OS: MacOS Catalina
- Node: v12.17.0
- Package version: ^1.0.0
- TypeScript version: ^3.9.3
- Next: ^9.5

**Additional Context**
We have source map generation in development, and there, the error is caught properly. But in production build, we don't generate source maps for build performance reasons, and this issue occurs. Thank you in advance for any insight you can provide!

**Comment by MichalLytek** [comment]
TypeGraphQL doesn't use map files. Please report your issue in Next repository.
