### ISSUE TITLE
Next.js reflection fails to destructure @Arg() decorator InputType variables

### ISSUE THREAD

**Issue by redbaron76** [MichalLytek/type-graphql#722]
**Describe the Bug**
I don't understand if it's an issue related to TypeGraphQL or it involves some Babel plugins used to transpile my Next.js application. But when I use `@Arg("input") { var1, var2 }: MyInputType` as a single parameter in a `@Mutation()` method in a `@Resolver()` class and I try to inline destructure my Input type, TypeGraphQL reflection seems to crash with `Cannot read property '0' of undefined`.

**To Reproduce**
This is my method that generates the error (and my workaround to fix it):
```
@Resolver((of) => User)
export class UserResolver {
  
  .....

  @Mutation((returns) => User)
  async register(
    // @Arg("input") { firstName, lastName, email, password }: RegisterInput ---> ERROR!!!
    @Arg("input") registerInput: RegisterInput ---> IT WORKS
  ): Promise<User> {
    const { firstName, lastName, email, password } = registerInput;
    const hashedPassword = await bcrypt.hash(password, 12);

    const user = await User.create({
      firstName,
      lastName,
      email,
      password: hashedPassword,
    }).save();

    return user;
  }
}

```
**.babelrc file in my Next.js project root**
```
{
  "presets": ["next/babel"],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "babel-plugin-parameter-decorator"
  ]
}
```

**Expected Behavior**
It should work as expected also destructuring variables from the incoming input type.

**Environment**

- OS: OSX 10.15.7 Catalina
- Node 10.22.0
- Package version 1.0.0
- TypeScript version 4.0.3

**Additional Context**
- Next.js 9.5.4
- TypeORM 0.2.28
- Postgres

**Comment by MichalLytek** [comment]
It's related to the babel plugin as it looks like the reflection plugin couldn't handle the destructuring syntax.

All the babel and JS discussion in happening in #55, so closing this one as duplicate 🔒
