### ISSUE TITLE
Need a way to return a response right after when there's a new subscription request.

### ISSUE THREAD

**Issue by rkdrnf** [MichalLytek/type-graphql#723]
I'm using the Subscription feature to track the progress of a task.
But sometimes when the task is completed while a client is sending a request to subscribe progress, it can't receive any events from the server because on the server, the task is already completed and there would be no events anymore. Therefore, the client just stays on the incomplete state without knowing that the task is already completed.

**Describe the solution you'd like**
If the server can send an immediate response to the client right after receiving a subscription request, it would be able to send a response that the task is already completed.

**Comment by MichalLytek** [comment]
Please open a feature request in `graphql-subscriptions` repo:
https://github.com/apollographql/graphql-subscriptions

TypeGraphQL is only a wrapper around that and `graphql-js` so it's limited to their capabilities.
