### ISSUE TITLE
Interface implementations are missing

### ISSUE THREAD

**Issue by HitkoDev** [MichalLytek/type-graphql#726]
**Describe the Bug**
Interface implementations are stripped by https://github.com/MichalLytek/type-graphql/blob/cd908565961b3325d798348690a454cb6d00932f/src/schema/schema-generator.ts#L591-L593

unless interface is directly used in `@Mutation` or `@Query` decorators.

**To Reproduce**
```ts
import { printSchema } from "graphql";
import "reflect-metadata";
import { buildSchema, Field, InterfaceType, ObjectType, Query, Resolver } from "type-graphql";

@InterfaceType()
export class IFace {
    @Field(() => String)
    val: string;
}

@ObjectType({ implements: IFace })
export class Foo extends IFace {
    constructor() {
        super();
        this.val = "Foo";
    }
}

@ObjectType({ implements: IFace })
export class Bar extends IFace {
    constructor() {
        super();
        this.val = "Bar";
    }
}

@ObjectType()
export class FooBar {
    @Field(() => IFace)
    iface: IFace;

    constructor() {
        this.iface = Math.random() > 0.5
            ? new Foo()
            : new Bar();
    }
}

@Resolver()
export class QueryResolver {
    // Doesn't include Foo & Bar
    @Query(() => FooBar)
    foobar() {
        return new FooBar();
    }

    // Properly includes Foo & Bar
    /* @Query(() => IFace)
    iface() {
        return Math.random() > 0.5
            ? new Foo()
            : new Bar();
    }*/
}

buildSchema({
    resolvers: [
        QueryResolver,
    ],
})
    .then(schema => console.log(printSchema(schema)))
    .catch(console.error);
```

**Actual Behavior**
Generated schema looks like
```gql
type Query {
  foobar: FooBar!
}

type FooBar {
  iface: IFace!
}

interface IFace {
  val: String!
}
```

**Expected Behavior**
Generated schema looks like
```gql
type Foo implements IFace {
  val: String!
}

interface IFace {
  val: String!
}

type Bar implements IFace {
  val: String!
}

type Query {
  foobar: FooBar!
}

type FooBar {
  iface: IFace!
}
```

**Logs**
`Runtime Object type "Foo" is not a possible type for "IFace".`

**Environment (please complete the following information):**

- OS: all
- Node: all
- Package version: since 1.0.0
- TypeScript version: all

**Additional Context**
It apereas that `usedInterfaceTypes` in `schema-generator.ts` is only properly populated after all field thunks are resolved, which doesn't happen until after we call `new GraphQLSchema` in https://github.com/MichalLytek/type-graphql/blob/cd908565961b3325d798348690a454cb6d00932f/src/schema/schema-generator.ts#L132

**Comment by MichalLytek** [comment]
The docs says:
> By default, if the interface type is explicitly used in schema definition (used as a return type of a query/mutation or as some field type), all object types that implement that interface will be emitted in schema, so we don't need to do anything.

So it looks like a bug, I'll have to cover your case by tests.
In the meantime you can use `orphanedTypes` as a workaround for now.
