### ISSUE TITLE
How to make @Query when create a schema having `refPath` field with createUnionType?

### ISSUE THREAD

**Issue by waiphyo285** [MichalLytek/type-graphql#728]
**Description about the problem**
I'm using createUnionType on a schema to reference multiple schemas that enable on mongoose. But I am unhappy getting errors `Cannot read property 'type' of undefined`.

**Here is my trying code**
```
export const RefRoomUnion = createUnionType({
  name: 'RefRoomUnion', 
  types: () => [ City, Township, RoomTopic ],
  resolveType: (value: any) => {
    if ('City'  in value) return "City"
    if ('Township' in value) return "Township"
    if ('RoomTopic' in value) return "RoomTopic"
    return undefined;
  }
});

/* ChatRoom Schema */

@ObjectType()
export class ChatRoom {
  @Field(_type => ID)
  _id: String;

  @Field(_type => RefRoomUnion,{ nullable: true })
  @Property({ required: true, refPath: "refRoom" })
  referenceid: Ref<typeof RefRoomUnion>;

  @Field(_type => RefRoomType, { nullable: true })
  @Property({ required: true, enum: Object.values(RefRoomType), index: true })
  refRoom: RefRoomType;
}

export const ChatRoomModel = getModelForClass(ChatRoom);

```

As above ChatRoom is clearly schema intend to reference multiple schemas. And imported RefRoomType enum and sample query are here.

```
export enum RefRoomType {
  City = "City",
  Township = "Township",
  RoomTopic = "RoomTopic"
};

registerEnumType(RefRoomType, {
  name: "RefRoomType", // this one is mandatory
  description: "The basic room types", // this one is optional
});

@Query(() => [ChatRoom]) // [ChatRoomModel] return schemas
    async returnAllChatRooms(){
      return await ChatRoomModel.find().populate("referenceid"); // ChatRoomModel
  };

```

 Then I can't go on to make Resolver to query ChatRoom response data. The error I can't solve easily is following.

```
query {
  	returnAllChatRooms {
    	_id
    	description
        referenceid {
          __typename
          ... on City {
            city
          }
          ... on Township {
            township
          }
          ... on RoomTopic {
            roomtopic
          }
        }
     }
  }

```

**Error response**

```
{
  "errors": [
    {
      "message": "Cannot read property 'type' of undefined",
      "locations": [
        {
          "line": 5,
          "column": 5
        }
      ],
      "path": [
        "returnAllChatRooms",
        0,
        "referenceid"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'type' of undefined",
            "    at Function.<anonymous> (C:\\Users\\HP\\Documents\\nwt\\fishadapt_chatroom\\node_modules\\type-graphql\\dist\\schema\\schema-generator.js:427:95)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (C:\\Users\\HP\\Documents\\nwt\\fishadapt_chatroom\\node_modules\\tslib\\tslib.js:112:62)",
            "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
          ]
        }
      }
    },
  ...
}
```

Can someone help me please. Many thanks for very first creating issue.

**Yeah here is environment**

OS: Window 10

Node Version: v12.13.1

TSC Version: 3.9.7

Package Version: ^1.0.0

**Comment by MichalLytek** [comment]
- if it's a question or need for help about integration with mongoose, please go on stackoverflow or gitter
- if it's a bug report, please fill the poper issue template with all required info (like library version) and a simple reproduction

**Comment by waiphyo285** [comment]
> **Description about the problem**
> I'm using createUnionType on a schema to reference multiple schemas that enable on mongoose. But I am unhappy getting errors `Cannot read property 'type' of undefined`.
> 
> **Here is my trying code**
> 
> ```
> export const RefRoomUnion = createUnionType({
>   name: 'RefRoomUnion', 
>   types: () => [ City, Township, RoomTopic ],
>   resolveType: (value: any) => {
>     if ('City'  in value) return "City"
>     if ('Township' in value) return "Township"
>     if ('RoomTopic' in value) return "RoomTopic"
>     return undefined;
>   }
> });
> 
> /* ChatRoom Schema */
> 
> @ObjectType()
> export class ChatRoom {
>   @Field(_type => ID)
>   _id: String;
> 
>   @Field(_type => RefRoomUnion,{ nullable: true })
>   @Property({ required: true, refPath: "refRoom" })
>   referenceid: Ref<typeof RefRoomUnion>;
> 
>   @Field(_type => RefRoomType, { nullable: true })
>   @Property({ required: true, enum: Object.values(RefRoomType), index: true })
>   refRoom: RefRoomType;
> }
> 
> export const ChatRoomModel = getModelForClass(ChatRoom);
> ```
> 
> As above ChatRoom is clearly schema intend to reference multiple schemas. And imported RefRoomType enum and sample query are here.
> 
> ```
> export enum RefRoomType {
>   City = "City",
>   Township = "Township",
>   RoomTopic = "RoomTopic"
> };
> 
> registerEnumType(RefRoomType, {
>   name: "RefRoomType", // this one is mandatory
>   description: "The basic room types", // this one is optional
> });
> 
> @Query(() => [ChatRoom]) // [ChatRoomModel] return schemas
>     async returnAllChatRooms(){
>       return await ChatRoomModel.find().populate("referenceid"); // ChatRoomModel
>   };
> ```
> 
> Then I can't go on to make Resolver to query ChatRoom response data. The error I can't solve easily is following.
> 
> ```
> query {
>   	returnAllChatRooms {
>     	_id
>     	description
>         referenceid {
>           __typename
>           ... on City {
>             city
>           }
>           ... on Township {
>             township
>           }
>           ... on RoomTopic {
>             roomtopic
>           }
>         }
>      }
>   }
> ```
> 
> **Error response**
> 
> ```
> {
>   "errors": [
>     {
>       "message": "Cannot read property 'type' of undefined",
>       "locations": [
>         {
>           "line": 5,
>           "column": 5
>         }
>       ],
>       "path": [
>         "returnAllChatRooms",
>         0,
>         "referenceid"
>       ],
>       "extensions": {
>         "code": "INTERNAL_SERVER_ERROR",
>         "exception": {
>           "stacktrace": [
>             "TypeError: Cannot read property 'type' of undefined",
>             "    at Function.<anonymous> (C:\\Users\\HP\\Documents\\nwt\\fishadapt_chatroom\\node_modules\\type-graphql\\dist\\schema\\schema-generator.js:427:95)",
>             "    at Generator.next (<anonymous>)",
>             "    at fulfilled (C:\\Users\\HP\\Documents\\nwt\\fishadapt_chatroom\\node_modules\\tslib\\tslib.js:112:62)",
>             "    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
>           ]
>         }
>       }
>     },
>   ...
> }
> ```
> 
> Can someone help me please. Many thanks for very first creating issue.

**Yeah here  is environment**

- OS: Window 10

- Node Version: v12.13.1

- TSC Version: 3.9.7

- Package Version: ^1.0.0

**Comment by waiphyo285** [comment]
> * if it's a question or need for help about integration with mongoose, please go on stackoverflow or gitter
> * if it's a bug report, please fill the poper issue template with all required info (like library version) and a simple reproduction

Yeah here is environment

OS: Window 10

Node Version: v12.13.1

TSC Version: 3.9.7

Package Version: ^1.0.0

**Comment by MichalLytek** [comment]
@waiphyo285 #728 should give you nice error message from `graphql-js` instead of failing due to returning `undefined` from `resolveType` so you should be able to find the mistake in your code easier.
