### ISSUE TITLE
Add dark mode option to Type graphql homepage

### ISSUE THREAD

**Issue by EdTosoy** [MichalLytek/type-graphql#729]
I always read your docs, like this XD
I change the CSS, everytime I switch topic,

![image](https://user-images.githubusercontent.com/68400105/96262601-991a3300-0ff4-11eb-8911-5bfeb3315c29.png)

**Comment by MichalLytek** [comment]
@EdTosoy 
Docs site is based on Docusaurus 1.
If you find a way to have a theme switcher there, feel free to open a PR 😉

**Comment by JipSterk** [comment]
@MichalLytek @EdTosoy i would also be interested in implementing such a feature
