### ISSUE TITLE
POJO

### ISSUE THREAD

**Issue by Fabyao** [MichalLytek/type-graphql#732]
Thanks for the great library. I would like to declare my types in simple POJOs with no decorators and define my schema separately in a strongly typed manner.

In the ORM world with TypeOrm this is called "Entity Schema" as described here: https://github.com/typeorm/typeorm/blob/master/docs/separating-entity-definition.md

@MichalLytek, you mentioned that it might be possible to achieve it with TypeGraphQL here: https://medium.com/@MichalLytek/i-would-like-to-correct-one-thing-dd4b9ad3222f

Could you elaborate and provide a sample implementation?
Also, would I incur a performance penalty if I use Field resolver?

If it can be done, it would allow me to keep my "Domain layer" free of library specific packages.
Thanks

**Comment by MichalLytek** [comment]
Simple POJO in that context means a class with only properties and decorators.
Then you add field resolvers by `@FieldResolver` as a method of `@Resolver` class.

Having classes without decorators and then some config or typedefs in separate file is clearly of out scope of this library. 

You can use standard apollo typedefs and resolvers and add graphql-code-generator to make them typesafe.
