### ISSUE TITLE
Enforcing constraints for `@ArgsType` fields of type enum

### ISSUE THREAD

**Issue by mithi** [MichalLytek/type-graphql#740]
Can the documentation include if this is possible or not?

Given an enum
```ts
enum Direction {
  UP
  DOWN
  LEFT
  RIGHT
}
```

And  I'd like to use it as a field in my `@ArgsType`, but I don't want anyone to be able to select the `DOWN` direction..
Is there a way to enforce this?  How?

```ts
@ArgsType()
class DirectionWithoutDownArgs {
  @Field(type => Direction)  
  direction: Direction; // should NOT be able to select DOWN
}
```

Thank you so much in advance!

**Comment by MichalLytek** [comment]
You just need to create enum without `DOWN` value, as simple as that 😉

**Comment by mithi** [comment]
> You just need to create enum without `DOWN` value, as simple as that 😉

Okay, thanks!

**Comment by mithi** [comment]
> You just need to create enum without `DOWN` value, as simple as that 😉

Okay. Thanks for the reply! 

### Related typescript issues:

Extending string-based enums: 
 - https://github.com/microsoft/TypeScript/issues/17592

Computed enums: 
  - https://github.com/microsoft/TypeScript/issues/37411
  - https://github.com/microsoft/TypeScript/issues/27976
  - https://github.com/Microsoft/TypeScript/issues/20440
