### ISSUE TITLE
Type-graphql uses keys of typescript enums for generating gql enums

### ISSUE THREAD

**Issue by vavra7** [MichalLytek/type-graphql#741]
**Describe the Bug**
With reference to #507, #486, #116 and [docs](https://typegraphql.com/docs/enums.html#docsNav) we know what the current behavior is. So let's open it again. The way how type-graphql handles typescritp enums is incorrect.

A simple proof:
```
enum Currency {
  Euro = 'EUR',
  CzechCrowns = 'CZK'
}

registerEnumType(Currency, {
  name: "Currency"
});

@InputType()
class PriceInput {
  @Field(() => Currency)
  currency: Currency;
}

...
@Mutation(() => Int)
public setPrice(@Arg('data') data: PriceInput): number {
  const currency = data.currency // Data typed as Currency are not of type Currency
  return 123;
}
```
Since gql generated enum looks like "Euro, CzechCrowns" they are only values you can receive in `data.currency` while none of them is type of "Currency". That is the least problem.

Considering your project is monorepo with many services throughout you share enums, you got a problem. From the rest api across gateway to the front end app you use values 'EUR', 'CZK' through enum Currency but here you must to mix in also values "Euro, CzechCrowns" because type-graphql doesn't offer any other way how to generate gql enum.

**Workaround**
For those who they are the same frustrated as me how enums work in type-graphql I came up with this workaround.

```
enum Currency {
  Euro = 'EUR',
  CzechCrowns = 'CZK'
}

enum GqlCurrency {
  'EUR',
  'CZK'
}

registerEnumType(GqlCurrency, {
  name: "Currency"
});

@InputType()
class PriceInput {
  @Field(() => GqlCurrency)
  currency: Currency;
}

...
@Mutation(() => Int)
public setPrice(@Arg('data') data: PriceInput): number {
  const currency = data.currency // Now currency is type of Currency
  return 123;
}
```
You must duplicate every enum you use with type-graphql and use duplicated version for generating gql enum and defining Fields in InputType. Only then you have consistent data.

**Expected Behavior**
Graphql enums are lists of values not keys. Consistent data without duplicating enums.

GraphQL Spec:
> Enums are not references for a numeric value, but are unique values in their own right. They may serialize as a string: the name of the represented value.

Gql enums must be strings. Ok so throw for example error in attempt to convert typescript enum with implicit numeric values, but gql enums are still values. Not keys.

Please change this behavior. Just not this.

**Comment by MichalLytek** [comment]
> Since gql generated enum looks like "Euro, CzechCrowns" they are only values you can receive in data.currency while none of them is type of "Currency". That is the least problem.

`graphql-js` runtime, as well as popular apollo typedefs-resolvers architecture, allows for something called enums members resolvers.

TypeGraphQL leverages that mechanism and uses enum keys as enum member names in GraphQL. However, the enum members values are used for the resolvers, so it will ALWAYS map the `"Euro"` string from GraphQL into `'EUR'` value injected into resolvers as args or inputs. The same goes to returning data from resolvers - if you return `'EUR'` (`Currency.Euro`) from resolver, it will appear in GraphQL JSON response as `"Euro"` string.

The behavior is intended as TypeScript enum can be number based while GraphQL enum has to have string member names. It won't be changed. If you need interoperability between clients and server, you have to use the direct mapping of the enum member names with values:
https://typegraphql.com/docs/enums.html#interoperability

However tools like GraphQL Code Generator can easily generate proper client TS typings from server schema file, so you can use correct enums on client side. It's my recommended approach. Server-side artifacts like classes or enums are not intended to be used as client-side typings, please remember about this.
