### ISSUE TITLE
Error when using Typegraphql with webpack

### ISSUE THREAD

**Issue by cjnoname** [MichalLytek/type-graphql#743]
Hi,

I got this error when using Typegraphql 1.1 with apollo server 2, graphql 15.4 and webpack 3.

```"    at assertSchema (/var/task/src/lambda.js:55464:11)",         "    at validateSchema (/var/task/src/lambda.js:83106:28)",         "    at assertValidSchema (/var/task/src/lambda.js:83130:16)",         "    at assertValidExecutionArguments (/var/task/src/lambda.js:129187:35)",         "    at executeImpl (/var/task/src/lambda.js:129135:3)",         "    at Object.execute (/var/task/src/lambda.js:129097:63)",         "    at Object.generateSchemaHash (/var/task/src/lambda.js:280278:32)",         "    at Server.generateSchemaDerivedData (/var/task/src/lambda.js:274214:41)",         "    at new ApolloServerBase (/var/task/src/lambda.js:274106:38)",         "    at new ApolloServer (/var/task/src/lambda.js:302986:1)",         "    at new Server (/var/task/src/lambda.js:271047:9)",         "    at createServer (/var/task/src/lambda.js:186602:20)",       ```

Does this library support webpack or not?

Thanks
CJ

**Comment by MichalLytek** [comment]
I don't see any TypeGraphQL stacktrace, is it really a TypeGraphQL error?

> Does this library support webpack or not?

What the library author has to do to support webpack? Isn't it just require a code that can be compiled by `tsc`?

**Comment by cjnoname** [comment]
> I don't see any TypeGraphQL stacktrace, is it really a TypeGraphQL error?
> 
> > Does this library support webpack or not?
> 
> What the library author has to do to support webpack? Isn't it just require a code that can be compiled by `tsc`?

Thanks for your reply. I cannot tell but actually created a post on there side too.  :) 

Hope someone who got the same issue can give me some help.

**Comment by huiliuliuhui** [comment]
We used webpack to build our project using typegrapql, and it work well. It seems that your error comes from apollo server.

**Comment by cjnoname** [comment]
Hi @huiliuliuhui 

We used webpack to build our project too but the issue only came out with the latest version of Graphql (15+).

I upgraded the version on both Graphql and Typegraphql then it stops working, not sure which side is wrong.

Could you tell me the version you are using right now? If it's Graphql 15+ and Typegraphql 1.0.0+ then I'll close this ticket and track on the Apollo side.

Thanks

**Comment by cjnoname** [comment]
@MichalLytek 

Here is a workaround: 
https://github.com/apollographql/apollo-server/issues/4637#issuecomment-706813287

Can close now.
Thanks
