### ISSUE TITLE
apollo-federation example issue and not listed in tree/v0.16.0.

### ISSUE THREAD

**Issue by sa-webb** [MichalLytek/type-graphql#747]
I am trying to explore the apollo-federation example and I'm getting TypeErrors from the new keyword in the data.ts files.

**Logs**
type-graphql/examples/apollo-federation/accounts/data.ts:19
  return Object.assign(new User(), userData);
                       ^
TypeError: user_1.default is not a constructor

**To Reproduce**
1. Clone the repository
2. npm install
3. dev.js uncomment the example
4. npm run dev

Assuming this is a tsconfig issue - I've tried altering target and lib in the tsconfig.json but to no avail and I've not had any success navigating the repository to find the version of the codebase when this example was added. 

I have restored my clone to its original version or as is from the master branch.

**Comment by MichalLytek** [comment]
Sorry, I'm afraid I don't have enough time capacity to dig in and fix examples issues in a super old branch/tag.

**Comment by sa-webb** [comment]
I understand, could you point me in the right direction to find the version
of the code base when it was added?

**Comment by MichalLytek** [comment]
> could you point me in the right direction to find the version
of the code base when it was added?

https://github.com/MichalLytek/type-graphql/commit/20c81f4f7ee82779595002d25784fce3a8ff8b9b

> I am on the master branch.*

So why did you mention the `tree/v0.16.0` in the issue title?

**Comment by sa-webb** [comment]
I apologize for not explaining that I mentioned it because in the examples
README it says to browse the files for a compatible version.

**Comment by MichalLytek** [comment]
No, it says that some examples describes features available from selected version, so you can't use 0.16.0 and browse master examples, it won't work. 

You should go to website and check the examples tab for selected version:
https://typegraphql.com/docs/0.17.4/examples.html

**Comment by MichalLytek** [comment]
Closing via 2b59bbe 🔒
