### ISSUE TITLE
Using typegraphql with aws appsync 

### ISSUE THREAD

**Issue by himanshu199728** [MichalLytek/type-graphql#750]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
You can also propose how the new API should looks like.

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalLytek** [comment]
Please fill the template, otherwise I'll close this issue.

**Comment by MichalLytek** [comment]
Closing for housekeeping purposes as I have no idea what the feature request is about 🔒 

If you have questions how to achieve something, like how to use TypeGraphQL with AWS AppSync, please ask on stackoverlow or gitter chat.
