### ISSUE TITLE
An overview of all decorators

### ISSUE THREAD

**Issue by reilem** [MichalLytek/type-graphql#752]
**Describe the issue**
It would be nice to have a list of all decorators available, similar to class-validator has: https://github.com/typestack/class-validator#validation-decorators

This offers a good quick overview of everything that is possible, and could contain links to the actual docs with more info.

**Are you able to make a PR that fix this?**
It would be nice to first know if this is something that will be added, and where (README or docs site). But if it's not too much work I could give it a go 😄 

**Additional context**
Overall this project feels like it is lacking a formal "API Reference" docs. The documentation right now is nicely formatted and a good read when you have time, but not a great way to quickly find what you are looking for. This is maybe for another time though. For now just a list of all supported decorators would probably help both newcomers and regular users refresh their knowledge and find what they are looking for.

**Comment by MichalLytek** [comment]
@reilem Thanks for reporting this 😉 

I will close this issue in favor of #17 where I'll track the progress.
In the meantime you can explore `d.ts` file to know about all available decorators. There are not so many like with `class-validators` and they all are described in the docs text.
