### ISSUE TITLE
Argument of type 'string | undefined' is not assignable to parameter of type 'QueryDeepPartialEntity<User>

### ISSUE THREAD

**Issue by petvi** [MichalLytek/type-graphql#753]
**Describe the Bug**
`Argument of type 'string' is not assignable to parameter of type 'QueryDeepPartialEntity<User>'.`
`Type 'string' has no properties in common with type 'QueryDeepPartialEntity<User>'.`

**To Reproduce**

```
  @Mutation(() => Boolean)
  async updateUser(
    @Arg('id', () => Int) id: number,
    @Arg('firstName', () => String) firstName: string,
    @Arg('lastName', () => String) lastName: string
  ): Promise<boolean> {
    await User.update({ id }, firstName, lastName)
    return true
  }
```

```
@ObjectType()
@Entity()
export class User extends BaseEntity {
  @Field(() => Int)
  @PrimaryGeneratedColumn()
  id?: number

  @Field()
  @Column()
  firstName?: string

  @Field()
  @Column()
  lastName?: string
}
```

**Expected Behavior**
No problems compiling

**Environment (please complete the following information):**

- OS: Win 10
- Node 10.19
- Package version ^1.1.1
- TypeScript version 4.2

**Comment by MichalLytek** [comment]
GitHub issues are not a helpdesk where users will fix type errors in your code. 
Please ask on Gitter or use Stackoverflow.

Open an issue if you find a real bug in the project, like wrong behavior (#751).
