### ISSUE TITLE
Unable to find type metadata for input type or object type named ''

### ISSUE THREAD

**Issue by xinghul** [MichalLytek/type-graphql#755]
**Describe the Bug**
Everything works great if I'm running the code with `ts-node`, however, if I try to compile the code to javascript, and will hit the error for any `FieldResolver`.

I guess this is somewhat related to https://github.com/MichalLytek/type-graphql/issues/55, and my question is, should we compile a typescript project containing `type-graphql` down to javascript? Because that's what I normally do in the production environment for better performance.

I tried to set up babel with `@babel/preset-typescript`, `babel-plugin-transform-typescript-metadata` and `@babel/plugin-proposal-decorators`, still no lock.

Thank you!

**Comment by MichalLytek** [comment]
> should we compile a typescript project containing type-graphql down to javascript? Because that's what I normally do in the production environment for better performance.

You can compile using `tsc`, you don't need to use babel if you don't know how to configure that 😉

**Comment by xinghul** [comment]
yes `tsc` works, I was using babel because I have some alias set up, and `tsc` does not handle that https://github.com/microsoft/TypeScript/issues/10866

Anyway, I went back to use `module-alias` with `tsc`.

Closing this now as it's resolved. Thank you!
