### ISSUE TITLE
Be able to run a `FieldResolver` at the same time as a `Query` resolver

### ISSUE THREAD

**Issue by aleccool213** [MichalLytek/type-graphql#759]
**Is your feature request related to a problem? Please describe.**

A problem I'm facing is that I have some `FieldResolver`s which are not dependant on the data that the base `Query` resolver returns and I would like these to run in parallel. 

For example, I have a query `getUser`:

```typescript
import { Inject } from "typedi";
import { Resolver, Ctx, FieldResolver, Root, Args, ResolverInterface } from "type-graphql";
import { Context } from "@live-platform/shared";

import { User } from "./user.type";
import { UserService, OrganizationService } from "../../service";
import { UserOrganizationsArgs } from "../organization";

@Resolver(() => User)
export class UserResolver implements ResolverInterface<User> {
  @Inject(() => UserService) private readonly userService!: UserService;
  @Inject(() => OrganizationService) private readonly organizationService!: OrganizationService;

  @Query(() => User, {
    description: "Get the Authenticated User profile and the associated resources.",
  })
  public async getUser(@Ctx() ctx: Context) {
    return this.userService.getUserProfile(ctx);
  }

  @FieldResolver()
  public async organizations(
    @Root() _user: User,
    @Ctx() ctx: Context,
    @Args({ validate: true }) args: UserOrganizationsArgs
  ) {
    return await this.organizationService.getUserOrganizations(ctx, args);
  }
}
```

This is what a sample query would look like:

```graphql
query getUser {
  getUser {
    id
    username
    organizations {
      id
      name
    }
  }
}
```

**Describe the solution you'd like**

Calling `this.organizationService.getUserOrganizations` is expensive and I would like this call to be run at the same time as the Query `getUser`. 

A proposed API for this:

```typescript
@Resolver(() => User)
export class UserResolver implements ResolverInterface<User> {
  ...

  @FieldResolver({ independent: true })
  public async organizations(
    @Root() _user: User,
    @Ctx() ctx: Context,
    @Args({ validate: true }) args: UserOrganizationsArgs
  ) {
    return await this.organizationService.getUserOrganizations(ctx, args);
  }
}
```

**Describe alternatives you've considered**

I know this isn't the case usually as `FieldResolver`s are usually dependant on the base query being resolved first. Maybe its an `id` which needs to be resolved so that the `FieldResolver` has the right `id` to go make another API call or DB query. In my case, the `FieldResolver` has all the information it needs as the user token to make the API request is attached to the context object.

**Additional context**

There may be a way to do this, I read all of the `FieldResolver` docs and saw nothing there about this.

**Comment by MichalLytek** [comment]
Thanks for opening this feature request and sharing your idea 😉 

However, it's not possible no call field resolvers before resolving the root object from the query.
It's how the GraphQL spec is designed and how `graphql-js` calls resolvers during query execution.
TypeGraphQL is based on `graphql-js` so it can't escape that.

According to your use case, it looks like `organizations` are independent from user.
So I would recommend moving that to the query level, so you can run them in parallel at the same time: 

```graphql
query getUser {
  getUser {
    id
    username 
  }
  organizations {
    id
    name
  }
}
```

**Comment by aleccool213** [comment]
@MichalLytek Thanks for the great answer. I'll consider this when designing my next GraphQL schema :)

**Comment by moralesmx** [comment]
@aleccool213 You can call `this.organizationService.getUserOrganizations` in your `getUser` query and store it in the context.

**Comment by aleccool213** [comment]
@moralesmx Thanks for the suggestion. The issue with that solution is that the query may not always include `organizations` so query analysis is needed.

**Comment by vespertilian** [comment]
@aleccool213 

I have a similar requirement of knowing if a field is being requested. I am using Dynamo DB with an adjacency list pattern. While I still need to get each subscriber (User) separately (or in a batch). If I know I need them in the root query I can get the user ids back in my initial request.

My solutions was to use `graphql-parse-resolve-info` 

It lets you check if specific params were requested on your query, in my case if I have subscribers on my query I can do a more effective initial query and get the user ids with one read. Useful for a DB like Dynamo. Not as applicable for SQL. 

This would allow you to do what you want I think @aleccool213, but maybe @MichalLytek is right and a better query is the real solution. 

Adding this here for anyone else using Dynamo. Feels like a reasonable solution. 

```ts
    const resolveInfo = parseResolveInfo(info) as ResolveTree

    // I added my schema to my context object as the simplify function wants the GraphQL type
    const result = context.schema.getType('ProgramSubscription')
    const { fields } = simplifyParsedResolveInfoFragmentWithType(
      resolveInfo,
      result
    );

    const getSubscribers = Object.keys(fields).includes('subscribers')

    if (!getSubscribers) {
      const programSubscriptionData = await this.programSubscriptionService.getProgramSubscription(id)
      return programSubscriptionData
    }

    const programSubscriptionData = await this.programSubscriptionService.getProgramSubscriptionWithSubscribers(id)
    return programSubscriptionData
```


Full sample 
```ts
@Injectable()
@Resolver(of => ProgramSubscription)
export class ProgramSubscriptionResolver {

  constructor(
    private programSubscriptionService: ProgramSubscriptionService,
    private programService: ProgramService,
    private userService: UserService
  )
  {}

  @Query(type => ProgramSubscription)
  async programSubscription(@Args() {id}: ProgramSubscriptionArgs, @Root() root, @Ctx() context: Context, @Info() info): Promise<ProgramSubscriptionData> {
    const resolveInfo = parseResolveInfo(info) as ResolveTree
    const result = context.schema.getType('ProgramSubscription')
    const { fields } = simplifyParsedResolveInfoFragmentWithType(
      resolveInfo,
      result
    );

    const getSubscribers = Object.keys(fields).includes('subscribers')

    if (!getSubscribers) {
      const programSubscriptionData = await this.programSubscriptionService.getProgramSubscription(id)
      return programSubscriptionData
    }

    const programSubscriptionData = await this.programSubscriptionService.getProgramSubscriptionWithSubscribers(id)
    return programSubscriptionData
  }

  @FieldResolver()
  async program(@Root() programSubscription: ProgramSubscriptionData): Promise<Program> {
    const {programId} = programSubscription;
    const program = await this.programService.getProgramBySlug({slug: programId})
    return program
  }

  @FieldResolver()
  async subscribers(@Root() programSubscriptionAndSubscribersData: ProgramSubscriptionWithSubscribersData): Promise<CoreUser[]> {
    const userIds = programSubscriptionAndSubscribersData.programSubscribersData.map((v) => v.uid)
    const userData = this.userService.getUsers(userIds)
    return userData
  }
}

```

**Comment by MichalLytek** [comment]
@vespertilian Getting requested fields is tracked by #10
