### ISSUE TITLE
Parameterizing Fields with Arguments 

### ISSUE THREAD

**Issue by tusharchutani** [MichalLytek/type-graphql#762]
I am not quite sure if this is possible at all right now. But looking at the docs I couldn't find anything or any example
I am trying to add parameters in the nested fields. For example I want to be able to have querry like this 

```
query {
    getUser(id: "1"){
        name,
        posts(startIndex: 10, endIndex: 20){
           name
           id
       }
    }
}

```

**Describe the solution you'd like**
You can also propose how the new API should looks like.

**Describe alternatives you've considered**
I could potentially pass the params in the top level query but that would just make the query very complicated and unreadble (we have a very complicated data model)

**Comment by MichalLytek** [comment]
https://typegraphql.com/docs/resolvers.html#field-resolvers
