### ISSUE TITLE
Cannot generate argument in schema without using @Arg or @Args decorators

### ISSUE THREAD

**Issue by nathanle89** [MichalLytek/type-graphql#765]
I'm running into performance issue with @Arg decorator and want to use simple resolvers for the whole object type. It looks like without the @Arg decorator, the schema is not generated correctly.

```
@ObjectType({simpleResolvers: true})
class SampleObject {
      @Field(() => String)
      field
}

```

in Schema, I want field to have an argument

`field(type: ValueType)`

**Comment by MichalLytek** [comment]
1) Simple resolvers are for disabling middlewares and auth guard
2) you're missing field type in your snippet
3) you need to define arg to have arg in schema

**Comment by nathanle89** [comment]
I updated the snippet to include field type. I notice a performance hit when returning a large array (500+ element) for `SampleObject` when I define @FieldResolver for field with Arg

Here is how I currently define my resolver and want to get away from it.

```
enum ValueType {
    A,
    B
}

@Resolver(() => SampleObject)
class SampleObjectResolver {
    @FieldResolver()
    field(
        @Root() parent: Record<string, any>,
        @Arg('type', () => ValueType, { defaultValue: ValueType.A }) _type: ValueType) {
        return parent.deepLink
    }
}
```

**Comment by MichalLytek** [comment]
Nope, if your field needs arg, it's dynamic so it needs field resolver.

If you precalculate all the data in the query/mutation resolver, just move the arg to its level, instead of reading graphql resolve info to read args ahead.

**Comment by nathanle89** [comment]
I was trying to precompute to confirm the performance issue. The argument only makes sense at the field level not at the parent node. I'm not sure what causes the extract latency with @FieldResolver but are we able to turn off TypeGraphql for individual resolver and simply use the default `{root, args, ctx, info}`

**Comment by nathanle89** [comment]
Ah, I actually missed a use case from documentation where what I want to do is supported via inline resolvers. Interestingly, the performance issue seems to come from @Root() rather than @Arg().

```
@ObjectType()
class SampleObject {
    @Field(() => String)
    field(@Arg('myArg', () => ValueType, { validate: false, defaultValue: ValueType.A }) _type: ValueType) {
        return this.field
    }
}
```

**Comment by MichalLytek** [comment]
> I notice a performance hit when returning a large array (500+ element) for SampleObject when I define @FieldResolver for field with Arg

Because it has to run the class method for 500+ times, with inputs (args) validation, root object transforming, calling middlewares and all the TypeGraphQL features.

> I was trying to precompute to confirm the performance issue.

Still don't understand the use case of declaring args but not defining field resolvers thus not able to use the args. If you perform the calculation on the query level, move the args to query level. Reading GraphQL request info to precompute fields or use other field args is against GraphQL and TypeGraphQL goals.

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
