### ISSUE TITLE
Pass in arguments from query into FieldResolver's method

### ISSUE THREAD

**Issue by tusharchutani** [MichalLytek/type-graphql#767]
I am not even sure if this is a viable feature or not. However I have a tree like structure that needs to be queried. It looks something like this:

```
import { Field, ObjectType } from "type-graphql";

@ObjectType({ description: "Lense data"})
export class Lens {
  @Field()
  id: string;
  @Field()
  name: string;
  @Field(type => Lens)
  childrenLenses?: Array<Lens> // <-----
}
```

And my resolvers look like this:

```
@Service()
@Resolver(()=>Lens)
export class LensResolver {
  @Inject("LENS_SERVICE")
  private readonly lensService: LensService


  @Query(returns => [Lens])
  async lense(@Arg("id") id: string, @Arg("startDate") startDate: Date,
  @Arg("endDate") endDate: Date){
    return this.lensService.getLens(id, startDate, endDate)
  }

  @FieldResolver( returns => [Lens])
  childrenLenses(@Root() lens: Lens, @Arg("startDate") startDate: Date,
  @Arg("endDate") endDate: Date): Array<Lens> {
    console.log("startDate:", startDate)
    return [];
  }
}
```

- I want to be able to pass in the startDate and endDate - which are passed in from the `lens` query into the fieldResolver's method. Is there a support for this?

**Comment by MichalLytek** [comment]
In GraphQL, field resolvers has to be independent from query, as different queries or mutations can return `Lens` object type. 

So that's why GraphQL doesn't have any mechanism to retrieve parent args as the field resolver should rely only on the parent object (`@Root() lens: Lens`).

So looks like something is wrong with your model - why childrenLenses depends on filtering by parent query arg, not only by the lens id? Why `getLens` needs startDate and endDate if it has unique id already?

**Comment by tusharchutani** [comment]
Thanks for the response. The more I think about this model I have the less it makes sense. The idea was to get another data point (totalCost - I haven't mentioned that here for brevity) that from the start and end date. I think it would make more sense to have to pass in arguments in the fieldResolver. I am going to close this issue since this way of doing thing is not in line with how things should be modeled in graphQL

**Comment by MichalLytek** [comment]
Your question is not strictly connected to TypeGraphQL, so you can ask community on GraphQL Slack or stackoverlow, how to model and structure your resolvers 😉
