### ISSUE TITLE
@Schema() decorator for resolvers 

### ISSUE THREAD

**Issue by vespertilian** [MichalLytek/type-graphql#769]
**Is your feature request related to a problem? Please describe.**

I commented in this issue 
https://github.com/MichalLytek/type-graphql/issues/759

But basically I am using `graphql-parse-resolve-info` and I need to pass in the GraphQL type instance
The way I made that happen was to attach the schema to the context and the get the type.

```
    const resolveInfo = parseResolveInfo(info) as ResolveTree
    // I added my schema to my context object as the simplify function wants the GraphQL type
    const result = context.schema.getType('ProgramSubscription')
    const { fields } = simplifyParsedResolveInfoFragmentWithType(
      resolveInfo,
      result
    );
```

**Describe the solution you'd like**

Would be nice to be able to inject something like @Schema() with a built in decorator. Also, I use a string to get the type, it would be nice to be able to pass the class. 

Not sure if there is already a better way to do this. 

Thanks for the great library.

**Comment by MichalLytek** [comment]
> But basically I am using graphql-parse-resolve-info and I need to pass in the GraphQL type instance

Try to use `graphql-fields` as described in #10 😉 

> The way I made that happen was to attach the schema to the context and the get the type.

That's the correct approach - TypeGraphQL builds the schema, so it can't inject itself magically.
You can always create a custom param decorator that will hide the complexity of transforming data from schema object:
https://typegraphql.com/docs/custom-decorators.html#parameter-decorators

**Comment by vespertilian** [comment]
@MichalLytek Thanks.

That thread is helpful. The custom decorator approach looks good. Just FYI I was looking at `graphql-fields` but chose `graphql-parse-resolve-info` as it seems to better handle edge cases better, and the `graphql-fields` author recommends it. 

https://github.com/robrichard/graphql-fields/issues/27#issuecomment-577412938
