### ISSUE TITLE
authChecker error

### ISSUE THREAD

**Issue by mariusflorescu** [MichalLytek/type-graphql#771]
**Describe the Bug**
TS COMPILE ERROR
Argument of type '{ resolvers: (typeof RegisterResolver | typeof LoginResolver | typeof FetchResolver)[]; authChecker: AuthChecker<MyContext, string>; }' is not assignable to parameter of type 'BuildSchemaOptions'.
  Object literal may only specify known properties, and 'authChecker' does not exist in type 'BuildSchemaOptions'.

**To Reproduce**
I was trying to implement my custom authChecker function (tried in 2 ways, they both fail)

**Environment (please complete the following information):**

- OS: MacOSX Big Sur
- Node 15.0.1
- Package version: 1.1.1
- TypeScript version 3.1.333

This is my authChecker.ts file:
```
export const authChecker : AuthChecker<MyContext> = ({context : {req}}) => {
  return !!req.session.uuid
};
```

Context.ts file:
```
export interface MyContext {
  req: Request;
}
```

And in the index.ts (the relevant part):
```
const schema = await buildSchema({
        resolvers: [someResolvers],
        authChecker,
      });

    const apolloServer = new ApolloServer({schema, context: ({req}:any) => ({req})});
```

and the uuid is implented by me:
```
declare module 'express-session' {
  interface SessionData {
    userId: number
  }
}
```

However, i tried it also like this(in the index.ts file, in the buildSchema):
```
authChecker: ({ context: {req} }) => {

        return !!req.session.uuid;
      }
```
but it throws the next error: Binding element 'req' implicitly has an 'any' type.

Thank you!

**Comment by MichalLytek** [comment]
> `Object literal may only specify known properties, and 'authChecker' does not exist in type 'BuildSchemaOptions'.`

See #653

**Comment by mariusflorescu** [comment]
Sorry, my bad. I thought my TypeScript was 4.1.3 but i was 3.1.333.
Once upgraded the problem was solved.
