### ISSUE TITLE
Website down? (DNS_PROBE_FINISHED_NXDOMAIN)

### ISSUE THREAD

**Issue by tomasstrejcek** [MichalLytek/type-graphql#774]
**Describe the issue**
Looks like website is down, probably expired domain registration or DNS problem?

**Are you able to make a PR that fix this?**
No  :)

**Comment by MichalLytek** [comment]
```
> nslookup typegraphql.com

Server:  dns.google
Address:  8.8.8.8

Non-authoritative answer:
Name:       typegraphql.com
Addresses:  185.199.109.153
            185.199.110.153
            185.199.108.153
            185.199.111.153
```

Everything looks ok, please check your DNS provider

![image](https://user-images.githubusercontent.com/10618781/105162774-56945500-5b13-11eb-9ab2-af6698ddb6f3.png)
