### ISSUE TITLE
New Issue on v1.1.1 : input types failed

### ISSUE THREAD

**Issue by jeromeSH26** [MichalLytek/type-graphql#777]
Have upgraded to V1.1.1 and did some basic refactoring while upgrading to V1.1.1, but now all fields in @InputType classes, are failing.
Was OK before for many months in v1.0.0

Wondering what is wrong now... I should miss some installation..

```

@ArgsType()
@InputType()
export class RefCalendarEntityInputType implements Partial<RefCalendarEntity> {
  @Field(()=>ID, { nullable: false })
  id: string;

  @Field(() => Int!)
  monthNum: number;

 @Field({ nullable: false })
  monthShortChar: string;

```

errors
**Cannot determine GraphQL input type for 'monthNum' of 'RefCalendarEntityInputType' class**
**Error: Cannot determine GraphQL input type for 'id' of 'RefCalendarEntityInputType'**

for monthShortChar field, no error...

thlks

**Comment by MichalLytek** [comment]
Sorry but I cannot reproduce the reported issue 😕 

Please create a repository with a minimal reproducible code example 😉

**Comment by seawatts** [comment]
I'm seeing the same thing but with a custom scalar.

**Comment by seawatts** [comment]
I'm actually seeing the same error on 1.0.0 as well

**Comment by seawatts** [comment]
This might be an issue with Graphql actually. I realized I also updated from 15.4.0 to 15.5.0

**Comment by seawatts** [comment]
Found the issue for me. It turns out I had multiple different versions of `graphql` installed so when it was doing a type check here https://github.com/MichalLytek/type-graphql/blob/master/src/helpers/types.ts#L18 it would return false. I removed the other versions of graphql in my monorepo project and now it works

**Comment by jeromeSH26** [comment]
unfortunatly didn't change for me. have only one installation of graphql in  my repo, I'm using links between packages, and still got the issue. Tried to downgrade both grpahql to v15.3.0 and type-graphql to v1.0.0, still issue

**Comment by MichalLytek** [comment]
If you replace `ID` scalar with `String` and it works, it must be an issue with duplicated `graphql-js` module.

**Comment by jeromeSH26** [comment]
Yes I found this workaround.
Finally I do a full reinstall of the yarn workspace, including the upgrade of all dependencies. And now, all is fine.
So I guess there was somewhere a duplicated graphql installation. Maybe..
Thks for your help guys
