### ISSUE TITLE
Mutation returning payload and clientMutationId

### ISSUE THREAD

**Issue by mmahalwy** [MichalLytek/type-graphql#780]
**Describe the issue**
Noticed in the Apollo docs that the suggestion is to return a mutation `payload` for mutations. See:
![image](https://user-images.githubusercontent.com/3749095/106860593-7716f000-6679-11eb-84dd-388b8dcfad61.png)
(source: https://www.apollographql.com/blog/designing-graphql-mutations-e09de826ed97/).

I don't see a way to make this happen without creating a custom type for each resolver. Is that correct? 

**Are you able to make a PR that fix this?**
No

**Additional context**
None

**Comment by MichalLytek** [comment]
> I don't see a way to make this happen without creating a custom type for each resolver. Is that correct?

Yes, and next time use Gitter or Discussion for asking questions.
https://github.com/MichalLytek/type-graphql/discussions

**Comment by mmahalwy** [comment]
@MichalLytek sounds good! Discussions it is :)
