### ISSUE TITLE
Wrong documentation / missing overload

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MichalLytek/type-graphql#782]
Hello,

in documantation i see that i can use empty Args and split operation. However empty Args decorator shows an error

From doc:
```
@Resolver()
class RecipeResolver {
  // ...
  @Query(returns => [Recipe])
  async recipes(@Args() { title, startIndex, endIndex }: GetRecipesArgs) {
    // sample implementation
    let recipes = this.recipesCollection;
    if (title) {
      recipes = recipes.filter(recipe => recipe.title === title);
    }
    return recipes.slice(startIndex, endIndex);
  }
}
```

Actual:

![image](https://user-images.githubusercontent.com/3918999/107116418-6336de00-6873-11eb-8e4b-d760e5fb99dd.png)

**Comment by MichalLytek** [comment]
It's `Args`, not `Arg` 😅 

`@Arg` is for single argument, `@Args` is for `@ArgsType` classes with multiple arguments (fields).
