### ISSUE TITLE
How to do an union of an array and a plain object

### ISSUE THREAD

**Issue by felipellrocha** [MichalLytek/type-graphql#783]
**Describe the issue**
Sorry, but I can't seem to find documentation on this. I want to do an union that will either reply with an array, or a plain object:

```
const GetRequestsResult = createUnionType({
  name: 'GetRequestsResult',
  types: () => [CoiRequest[], ServerError] as const,
});

  @Query(() => GetRequestsResult)
  async requests(): Promise<typeof GetRequestsResult[]> {
    try {
      const { data } = await this.monolithService
        .get('/v1/member')
        .toPromise();
      return data;
    } catch(e) {
      return new ServerError();
    }
  }
```

Is the api I'm looking for. In essence. I want to either receive a list if my request is successful, but a plain error object if my requests fails. Nothing I do seems to support that pattern. Is it missing from `type-graphql` or am I trying to do something that is not a good practice here?

**Comment by MichalLytek** [comment]
> reply with an array, or a plain object

Sorry but it's not possible as it's not allowed by GraphQL spec.
