### ISSUE TITLE
[Issue] Data is sent but graphql says one of its field is null

### ISSUE THREAD

**Issue by hitech95** [MichalLytek/type-graphql#785]
**Describe the Bug**
`Cannot return null for non-nullable field User.email.`
Data is provided all the fields seems to be working except the email one.

**To Reproduce**
Call the mutation with the required args, the error is thrown.
The graphql mutation is:
 ```
 mutation{
  login(email: "mymail@example.com", password: "my-insecurepassword"){
    user{
      id
      firstName
      lastName
      email
    }
    
    accessToken
    refreshToken
  }
}
```

**Expected Behavior**
Data should be correctly parsed and visualized on graphql console

**Logs**
This is the full log of the mutation.
As you can see the data I send contains the email field:

```
Server started at http://localhost:5555 �
query: SELECT * FROM "shema"."User" "User" WHERE "User"."email" = $1 LIMIT 1 -- PARAMETERS: ["mymail@example.com"]
User {
  id: 'redactedID',
  createdAt: 2020-04-09T20:37:17.282Z,
  updatedAt: 2020-08-31T08:20:19.820Z,
  firstName: 'Nicolò',
  lastName: 'Veronese',
  email: 'mymail@example.com',
  password: 'password-hash',
  confirmedEmail: true,
  blocked: null,
  forgotPasswordLocked: false,
  isAdmin: true,
}
{
  user: User {
    id: 'redactedID',
    createdAt: 2020-04-09T20:37:17.282Z,
    updatedAt: 2020-08-31T08:20:19.820Z,
    firstName: 'Nicolò',
    lastName: 'Veronese',
    email: 'mymail@example.com',
    password: 'password-hash',
    confirmedEmail: true,
    blocked: null,
    forgotPasswordLocked: false,
    isAdmin: true,
  },
  accessToken: 'myaccesstoken',
  refreshToken: 'refreshToken'
}
POST /graphql 200 692.835 ms - 1999
Broadcast on REDIS: event.auth.login
```

**Environment (please complete the following information):**

- OS: Windows
- Node 12.18.03
- Package version 1.1.1
- TypeScript version 4.1.3

**Additional Context**
This is the code that run for the mutation:
```
@Resolver(() => AuthResponse)
export class AuthResolver {
@Mutation(() => AuthResponse)
  async login(
    @Ctx() { res }: ResolverContext,
    @RequestIP() requestIP: string,
    @Args() data: LoginInput
  ): Promise<AuthResponse> {
    const user = await this.authService.login(requestIP, data);
    const roles = await user.roles();
    const accessToken = this.authService.createAuthToken(user, roles);
    const refreshToken = this.authService.createRefreshToken(user);

    console.dir(user);
    console.dir({ user, accessToken, refreshToken });

    return { user, accessToken, refreshToken };
  }
}
@ObjectType()
export class AuthResponse {
  @Field()
  user: User;

  @Field()
  accessToken: string;

  @Field()
  refreshToken: string;
}
```

**Comment by MichalLytek** [comment]
Please create a repository with a minimal reproducible code example - one resolver, one method, one type, no database nor business logic.

**Comment by hitech95** [comment]
Iàm working on a mockup right now!
Thanks for the help!

**Comment by hitech95** [comment]
Here it is:
https://github.com/hitech95/typegql_issue_mockup

The important files are:
https://github.com/hitech95/typegql_issue_mockup/blob/master/src/modules/auth/auth.resolver.ts
https://github.com/hitech95/typegql_issue_mockup/blob/master/src/modules/auth/responses/auth.response.ts
https://github.com/hitech95/typegql_issue_mockup/blob/master/src/modules/user/user.entity.ts
https://github.com/hitech95/typegql_issue_mockup/blob/master/src/modules/shared/base.entity.ts

ME Query Works
Login Mutation does not

**Comment by MichalLytek** [comment]
> The other files are boilerplate.

I said:
> one resolver, one method, one type, no database nor business logic

I don't have time to find a bug in your codebase. I can fix bugs in TypeGraphQL when you prooe something is not working because of my fault, e.g. by reproducing with a failing test case.

**Comment by hitech95** [comment]
I've celaned up more the mockup, there are a couple of types just to keep the examle above equal.
No more boilerplate. (I just removed the dirs).

Direct take from your examples.
https://github.com/hitech95/typegql_issue_mockup/tree/master/src

**Comment by MichalLytek** [comment]
Does your `email` field use `@Authorized` and you have set `authMode: "null"` but forgot to setup the `context` in ApolloServer so it silently fails when accessing that property thus returning null? 🤔

**Comment by hitech95** [comment]
Oh... right! My bad!

So is there a way to forcethe context so it get correctly resolved on my login mutation?

**Comment by MichalLytek** [comment]
> adding the user to the context after the call to database?

Please ask community for support but first start with reading about context in GraphQL cause you have big gaps of knowledge and decided to jump right into the framework which requires basic GraphQL knowledge 😉
