### ISSUE TITLE
Unable to set null properties to database

### ISSUE THREAD

**Issue by nadaru-fr** [MichalLytek/type-graphql#786]
**Describe the Bug**
I try to update a property of an entity to null.
Typeorm only updates property fields when they are set to null (does not work with entity.prop = undefined)

However nullable fields are declared as below:
```
@Field({ nullable: true })
prop?: number
```

This will generate a typescript error if you want to do entity.prop = null and will not update database if you do entity.prop = undefined

And setting 
```
@Field({ nullable: true })
prop?: number | null
```
Will generate a typescript type issue as you can see below in the logs

The solution currently is to explicitly return field type and set the column type as below
```
  @Field((type) => Number, { nullable: true })
  @Column({ type: 'float', nullable: true })
  prop?: number | null
```

**To Reproduce**
Try to set to null any field that has a value in database

**Expected Behavior**
Either:
- Setting property to undefined should set the property to null in database
OR
- Do not throw an error when setting explicitly null type

**Logs**
```
NoExplicitTypeError: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for 'customerName' of 'Order' class.
    at Object.findType ([...]/gql-server/node_modules/type-graphql/dist/helpers/findType.js:19:15)
    at [...]/gql-server/node_modules/type-graphql/dist/decorators/Field.js:16:53
    at DecorateProperty ([...]/gql-server/node_modules/reflect-metadata/Reflect.js:553:33)
    at Object.decorate ([...]/gql-server/node_modules/reflect-metadata/Reflect.js:123:24)
    at __decorate ([...]/gql-server/dist/entities/order/order.entity.js:4:92)
```

**Environment (please complete the following information):**
- OS: MacOS Mojave
- Node: 12.10.0
- Package version: 1.1.0
- TypeScript version: 4.0.5
- Postgres database

**Additional Context**

**Comment by MichalLytek** [comment]
> The solution currently is to explicitly return field type and set the column type as below

Working as designed 🔒
