### ISSUE TITLE
Allow full type-graphql `buildSchema` in a browser environment (e.g. Chrome Extension background page)

### ISSUE THREAD

**Issue by vjpr** [MichalLytek/type-graphql#789]
**Is your feature request related to a problem? Please describe.**

I want to run a graphql api from a Chrome Extension background page.

Motivation: Connecting from an external webpage to a Chrome extension https://developer.chrome.com/docs/extensions/mv2/messaging/#external-webpage

**Describe the solution you'd like**

All the Node.js-specific code isolated somewhere in codebase to easily ignore in a webpack build.

For example, `buildSchema` imports `glob`, `path`, etc. It really doesn't need these to function.

**Describe alternatives you've considered**

Browser shim, and webpack config.

**Additional context**

https://github.com/MichalLytek/type-graphql/issues/100
https://typegraphql.com/docs/browser-usage.html
https://github.com/MichalLytek/type-graphql/issues/673

Is there any working instructions for doing this?

---

Is there an easy way to ignore `type-graphql/dist/helpers/filesystem.js` in webpack...maybe that will fix it.

---

When using 

```
      alias: {
        // `type-graphl/loadResolversFromGlob`
        glob: false,
        fs: false,
        tls: false,
        net: false,
        path: false,
        zlib: false,
        http: false,
        https: false,
        stream: false,
        crypto: false,
        process: 'process/browser',
      },
```

...promisify is causing issues:

```
exports.fsMkdir = util_1.promisify(fs.mkdir);
```

```
util.js:614 Uncaught TypeError: The "original" argument must be of type Function
    at Object.promisify (util.js:614)
    at Object.../../../../../../node_modules/.pnpm/type-graphql@1.1.1/node_modules/type-graphql/dist/helpers/filesystem.js (filesystem.js:7)
```

**Comment by MichalLytek** [comment]
> I want to run a graphql api from a Chrome Extension background page.

TypeGraphQL is designed as a Node.js framework. Without refactoring to monorepo, it's hard to create a separate package without the Node dependencies.

> Is there any working instructions for doing this?

I don't have a ready-to-use Webpack config but you can take inspiration from the examples using Parcel to mock node dependencies:
https://github.com/MichalLytek/type-graphql/tree/v1.1.1/examples/apollo-client

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
