### ISSUE TITLE
Allow disabling inferring the default values from properties initializers

### ISSUE THREAD

**Issue by MichalLytek** [MichalLytek/type-graphql#793]
Extracted from https://github.com/MichalLytek/type-graphql/issues/787#issuecomment-786507512

> ```ts
> @InputType("ArchiveInput")
> @ObjectType()
> export class Archive {
> 	@Field(is => Date)
> 	created = new Date();
> }
>```
> This behavior is unexpected, as I had no intention to even affect the API in this manner. All I wanted to achieve, was that I have a default value when I locally construct an instance of the class, like in a test. There is a specific defaultValue setting that I can and do use when I want to set default values. I didn't expect any magic to happen beyond that.
>
> Type-GraphQL, by applying this default value detection magic, prevents this use case entirely. I end up declaring an input schema (where the input value is nullable and then set in a resolver), an output schema (where the value isn't nullable) and a class to internally represent the same schema, but which sets default values upon construction. This is something I was hoping to avoid by using the library in the first place.
>
> I'm happy to accept that this 3-model-approach is ultimately the correct one for what I'm trying to achieve. I just wasn't expecting this and the root cause is unsettling. I don't feel in control of what's happening. I'd much rather like to disable this default value detection entirely.

In some cases, the default value should be only internally, like current date for some optional date filer input field.

In order to not introduce a breaking change, a schema option should be introduced to disable that mechanism.

**Comment by MichalLytek** [comment]
Closing by e8e164d 🔒

**Comment by oliversalzburg** [comment]
Upgraded to 1.2.0-rc.1 today and this seems to work really well for me. Thanks 👍
