### ISSUE TITLE
Allow interfaces on ArgsType

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MichalLytek/type-graphql#797]
Hi,

I see type-graphql can extend interface but only on ObjectType. It would be good to have same functionaity on ArgsType. This would be useful for situations where for example I different endpoints which returns paged list and as an argument **always** takes **filter** and **currentPage** + some other params. This way we can avvoid code duplication.

**Comment by MichalLytek** [comment]
Sorry but `ArgsType` is purely virtual type and it disappears in GraphQL SDL. Input Types also can't implement interfaces, they are described in the GraphQL spec as purely object type related thing.

**Comment by MichalLytek** [comment]
> This way we can avvoid code duplication.

You can create `BasePaginationArgs` class and then extend in while creating specific args classes your your queries.

**Comment by vytautas-pranskunas-** [comment]
Should i mark base args class with ArgsTyoe also?
