### ISSUE TITLE
Typescript gives error when using PagedResponse example

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MichalLytek/type-graphql#798]
Hi,

I am implementing page response accoring to this:
https://typegraphql.com/docs/generic-types.html

but i am getting this error:
![image](https://user-images.githubusercontent.com/3918999/109478466-938c2980-7a79-11eb-826c-f2285b8c5f2c.png)

**Comment by MichalLytek** [comment]
https://typegraphql.com/docs/inheritance.html#resolver-inheritance
> Be aware that with some tsconfig.json settings (like declarations: true) we might receive a [ts] Return type of exported function has or is using private name 'BaseResolver' error - in this case we might need to use any as the return type or create a separate class/interface describing the class methods and properties

Use `declarations: false` or you will need to create interfaces describing the shape of the base class.

**Comment by vytautas-pranskunas-** [comment]
Can you give me an example of interface?

**Comment by MichalLytek** [comment]
> disabling declarations might not be good idea from debuging point of view.

`*.d.ts` files are not source maps. They are not for debugging purposes but for library authors to publish transpiled js code with typescript declarations.
