### ISSUE TITLE
Failure while deserializing an input type with a nested array field

### ISSUE THREAD

**Issue by pablojmp** [MichalLytek/type-graphql#801]
**Describe the Bug**
While trying to pass an input with a nested array field, the object comes up empty on the resolver

**To Reproduce**
```
@ObjectType()
@InputType('InnerInput')
export class Inner {
  @Field((type) => String)
  aString: string

  @Field((type) => Int)
  aNumber: number
}
```
```
@InputType()
export class Outer {
  @Field((type) => [[Inner]])
  nested: Inner[][]
}
```
```
@Resolver()
export class TestResolver {
  @Query((type) => Inner)
  test(@Arg('input', (type) => Outer) input: Outer) {
    return input[0][0].nested
  }
}
```

GraphQl query:
```
{
  test(input: {nested: [[{aString: "test", aNumber: 90}]]}) {
    aString
    aNumber
  }
}
```

**Expected Behavior**
The query should return the object `{aString: "test", aNumber: 90}`. Instead, it returns the error "Cannot read property '0' of undefined"

**Environment (please complete the following information):**

- OS: Windows 10 build 19042.844
- Node 14.15.5
- Package version 1.1.1
- TypeScript version 4.2.2

**Comment by MichalLytek** [comment]
@pablojmp Sorry but unable to reproduce:
https://github.com/MichalLytek/type-graphql/blob/v1.1.1/tests/functional/resolvers.ts#L1414-L1420
https://github.com/MichalLytek/type-graphql/blob/v1.1.1/tests/functional/resolvers.ts#L1767-L1787

Please create a PR with a failing test case 😉

**Comment by pablojmp** [comment]
Yes, I know that test passed, but this is not the same:

**Comment by pablojmp** [comment]
Yes, I know the nested array on Arg passed, but this is not the same:
```
@Arg('input', (type) => Outer)
```
this is a nested array *inside* the InputType class
vs
```
@Arg("inputs", type => [[[SampleInput]]])
```
here the input is a nested array

**Comment by pablojmp** [comment]
I'll create a test case shortly

**Comment by MichalLytek** [comment]
Thanks 😉

**Comment by pablojmp** [comment]
here: https://github.com/MichalLytek/type-graphql/pull/802

**Comment by MichalLytek** [comment]
Fixed by f9499e2 🔒

**Comment by pablojmp** [comment]
thanks for the quick fix @MichalLytek!

**Comment by vavra7** [comment]
Sorry I am confused from github workflow. In what version this is fixed? I am experiencing the bug in version 1.1.1.

**Comment by MichalLytek** [comment]
In next upcoming release. You can build the master branch by yourself in the meantime.

**Comment by vavra7** [comment]
Ok that did the trick. It's working, thanks.
