### ISSUE TITLE
Allow interfaces on InputType

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MichalLytek/type-graphql#804]
Hi,

I see type-graphql can extend interface but only on ObjectType. It would be good to have same functionaity on InputType.

**Comment by MichalLytek** [comment]
@vytautas-pranskunas- Already answered in your last ticket (#797), so please read my answers more carefully:

> Input Types also can't implement GraphQL Interfaces - they are described in the GraphQL spec as purely object type related thing.

**Comment by vytautas-pranskunas-** [comment]
You are right - missed that. Thanks
