### ISSUE TITLE
Cannot determine GraphQL output type error when models are in a symlinked directory

### ISSUE THREAD

**Issue by jazzfog** [MichalLytek/type-graphql#833]
**Describe the Bug**

When `@ObjectType()` files are located outside of the project and the model folder linked into the project via symlink - `type-graphql` is not able to detect types of fields that were explicitly given a Graphql Scalar Type (ID, Float, Int):

```
@Field(() => ID)
uuid: string = '';
```

This results in the error: 
```
(node:15377) UnhandledPromiseRejectionWarning: Error: Cannot determine GraphQL output type for 'uuid' of 'Base' class. Is the value, that is used as its TS type or explicit type, decorated with a proper decorator or is it a proper output value?
    at Function.getGraphQLOutputType (/home/user/www/type-graphql-links-issue/app/node_modules/type-graphql/dist/schema/schema-generator.js:519:19)
    at /home/user/www/type-graphql-links-issue/app/node_modules/type-graphql/dist/schema/schema-generator.js:175:47
    at Array.reduce (<anonymous>)
    at fields (/home/user/www/type-graphql-links-issue/app/node_modules/type-graphql/dist/schema/schema-generator.js:166:53)
    at resolveThunk (/home/user/www/type-graphql-links-issue/app/node_modules/graphql/type/definition.js:480:40)
    at defineFieldMap (/home/user/www/type-graphql-links-issue/app/node_modules/graphql/type/definition.js:692:18)
    at GraphQLObjectType.getFields (/home/user/www/type-graphql-links-issue/app/node_modules/graphql/type/definition.js:633:27)
    at Object.getFieldMetadataFromObjectType (/home/user/www/type-graphql-links-issue/app/node_modules/type-graphql/dist/schema/utils.js:20:28)
    at fields (/home/user/www/type-graphql-links-issue/app/node_modules/type-graphql/dist/schema/schema-generator.js:203:66)
    at resolveThunk (/home/user/www/type-graphql-links-issue/app/node_modules/graphql/type/definition.js:480:40)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15377) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15377) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is especially inconvenient because `ID` type is not available.

This errors goes away when you replace the linked folders with real ones so it is clearly related to the linking.

**To Reproduce**
Minimal example with instruction:
https://github.com/jazzfog/type-graphql-links-issue

**Expected Behavior**
- Type-Graphql should recognize the ID type and other Graphql scalar types

**Logs**
Provided in the example

**Environment (please complete the following information):**

- OS: Tried on Linux and Windows, same results
- Node: v14.8.0
- Package version: 1.1.1
- TypeScript version: 4.2.3

**Comment by MichalLytek** [comment]
You need to have only one `graphql-js` dependency in your project. Symlinking nor `npm link` does not work well with peer dependencies. You need to use alternative solution like yarn workspaces.

**Comment by jazzfog** [comment]
I see, thank you for looking into it.

I was actually curious why does the app care about the fact that linked directory is outside of the project and it would not run without another `node_modules` in it. I am clearly not understanding something about how things work but I'd expect that the app would treat the files in the linked folder the same way as the rest of the project files and apply the same logic to them (meaning app's package dependencies).

I know it is off topic but would you be able to point me at the right direction where I can read more about it or what keywords I should google?
Thank you!

**Comment by MichalLytek** [comment]
> I was actually curious about why does the app care about the fact that linked directory is outside of the project and it would not run without another node_modules in it.

Because it does `type instance of GraphQLScalarType` check, so when you have different instances of `graphql-js`, this check fails.

**Comment by jazzfog** [comment]
Right, that's what causes the error I see...
But I was wondering why node is not treating linked folder as just regular folder with files and requires a separate `node_modules` for for it. If it did treat it as a regular folder and just read model files from there - the problem would not exist on the first place.
