### ISSUE TITLE
Is this still a valid TODO

### ISSUE THREAD

**Issue by theseyi** [MichalLytek/type-graphql#862]
Interested in the context around this TODO and if it is still valid or going to be worked on? I see it's a comment from... 2018 😅 
https://github.com/MichalLytek/type-graphql/blob/3733b1e57cb7ea8432420a17b3660c69187e0a09/src/metadata/metadata-storage.ts#L124

**Comment by MichalLytek** [comment]
Nope 😅 
We now support multiple build attempts because you can provide different `resolvers` array and build a different GraphQL schema. Side effects were minimalized so there's no need to prevent next build attempts.

Feel free to create a PR o remove that 😜

**Comment by theseyi** [comment]
removed in #864
