### ISSUE TITLE
Missing field names in validation errors when integrating with mercurius

### ISSUE THREAD

**Issue by lewispham** [MichalLytek/type-graphql#863]
When I tried to integrate typegraphql with mercurius, validation errors thrown by class validator do not include the related field name.

```
Error: Argument Validation Error
    at Object.validateArg (/app/node_modules/type-graphql/dist/resolvers/validate-arg.js:29:15)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 0)
    at Object.fastifyGraphQl [as graphql] (/app/node_modules/mercurius/index.js:516:23) {
  locations: [ { line: 2, column: 3 } ],
  path: [ 'createUser' ]
}
```

This issue is not happening with apollo server. This is a respective log on apollo server.

```javascript
{
                message: "Argument Validation Error",
                extensions: {
                    exception: {
                        validationErrors: [
                            {
                                property: "field 1",
                                value: input
                            },
                            {
                                property: "field 2",
                                value: input
                            }
                        ]
                    }
                }
            }
```

- OS: MacOs
- Node v15.10.0
- Package version v1.1.1
- TypeScript version v4.2.2
- Mercurius v7.4.0

**Comment by MichalLytek** [comment]
@lewispham Go ask on Mercurius repo about how to print `originalError` details. Apollo Server does that automatically.

**Comment by lewispham** [comment]
@MichalLytek Thanks for the hint. I've just created an issue on mercurius repo.

**Comment by lewispham** [comment]
Closing this issue as this is a mercurius bug.

**Comment by gilach** [comment]
@MichalLytek The problem is that `originalError` field of GraphQLError class is non-enumerable, which means it won't get serialized or logged. It would make things a lot easier if the validation error details could be exposed via the `extensions` field.
