### ISSUE TITLE
Cast to ObjectId failed for value "FooInput"

### ISSUE THREAD

**Issue by noudadrichem** [MichalLytek/type-graphql#880]
**Describe the Bug**
When I try to add a field on my InputType called _id with the field option `nullable: true`. For some reason the field is not nullable. Either with ObjectId type and/or String type.

**To Reproduce**
Nested input type:
```ts
@InputType()
export class FooInput {
    @Field(type => ID, { nullable: true })
    _id: ObjectId
}
```

The actual input:
```ts
@InputType()
export class Input {
    @Field(() => ID)
    _id: ObjectId

    @Field(() => [FooInput ])
    foos: FooInput []
}
```

The actual data:
```json
{
  "_id": "609189b06d384e4eeec54713",
  "foos": [
    {
      "_id": "609189b06d384e4eeec54712",
      "title": "foo"
    },
    {
      "title": "bar"
    }
  ]
}
```

**Expected Behavior**
I expected the `_id` in `FooInput` to be optional so I could make a distinction between actions based the a attribute.

**Logs**
```
 Cast to ObjectId failed for value "FooInput{
      "title": "bar"
}" at path "foos"
```

**Environment (please complete the following information):**

- OS:  WSL (but also happens on Mac)
- Node: v14.16.0
- Package version: "type-graphql": "^1.1.1"
- TypeScript version: ^4.0.2"

**Additional Context**
Wasn't able to find help on this 'bug' via other issues or SO.

**Comment by MichalLytek** [comment]
> Cast to ObjectId failed for value 

This is not TypeGraphQL error. Check your ObjectId implementation if it support null.
Your `FooInput` is missing `title` field.

**Comment by noudadrichem** [comment]
I tried using 'string' instead of ObjectId. Also tried another name attribute. Still does not work.

**Comment by noudadrichem** [comment]
Tried these, all do not work. Not sure if it. Not sure why it would not be a TypeGraphQL issue if these won't work. Even reduced the logic of the resolver to only 'log' the body.

```ts
    @Field(type => ID, { nullable: true })
    _id: ObjectId
```

```ts
    @Field(() => String, { nullable: true })
    _id: string
```

```ts
    @Field({ nullable: true })
    _id: string
```

**Comment by MichalLytek** [comment]
Please create a minimal reproducible code example, maybe the one with string to not complicate with object id scalar.

**Comment by noudadrichem** [comment]
I copied my repo and extracted all the thing that aren't needed. The weird thing is that it does not give the error now.. Weird stuff but yey... Not sure what to do now as my code is the, just has a service layer in between. https://wormhole.app/V0pPx#Edtm4yKHVH-QKS5GomYnlA

**Comment by MichalLytek** [comment]
Uploading codebase zip to file hosting service while reporting issue on git hosting platform 😅 
Please create a github repository in order to browse the files and give you the link to faulty lines.

> The weird thing is that it does not give the error now..

So I cannot do anything as it looks some other layer breaks your stuff and it's not TypeGraphQL fault.
May I close the issue?

**Comment by noudadrichem** [comment]
Sure
