### ISSUE TITLE
Mutation doesn't seem to support async/await

### ISSUE THREAD

**Issue by verikono** [MichalLytek/type-graphql#884]
**Describe the Bug**
When a Mutation in the Resolver is asynchronous I'm getting this error: ```Error: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for 'addRecipe' of 'RecipeResolver' class.```

Am I doing something wrong?

**To Reproduce**
Take our recipe example in the tutorial under Input types:

```
@Resolver()
class RecipeResolver {
  // ...
  @Mutation()
  addRecipe(@Arg("data") newRecipeData: AddRecipeInput, @Ctx() ctx: Context): Recipe {
    // sample implementation
    const recipe = RecipesUtils.create(newRecipeData, ctx.user);
    this.recipesCollection.push(recipe);
    return recipe;
  }
}
```

and change to (so the function is async and the return type includes the Promise>

```
@Resolver()
class RecipeResolver {
  // ...
  @Mutation()
  async addRecipe(@Arg("data") newRecipeData: AddRecipeInput, @Ctx() ctx: Context): Promise<Recipe> {
    // sample implementation
    const recipe = RecipesUtils.create(newRecipeData, ctx.user);
    this.recipesCollection.push(recipe);
    return recipe;
  }
}
```

**Expected Behavior**
We dont receive an error and the mutation works asynchronously.

**Environment (please complete the following information):**

- OS: Ubuntu 20.04
- Node v14.3.1
- Package version 1.1.1
- TypeScript version 3.3.3

**Comment by MichalLytek** [comment]
> Am I doing something wrong?

Yes, you're not reading the docs.

https://typegraphql.com/docs/types-and-fields.html
> due to a limitation in TypeScript's reflection

**Comment by verikono** [comment]
Thank you.

For anyone who skipped over this part of the documentation. We need to indicate the type being returned and the following will work:

```
@Resolver()
class RecipeResolver {
  // ...
  @Mutation(**type => Recipe**)
  async addRecipe(@Arg("data") newRecipeData: AddRecipeInput, @Ctx() ctx: Context): Promise<Recipe> {
    // sample implementation
    const recipe = RecipesUtils.create(newRecipeData, ctx.user);
    this.recipesCollection.push(recipe);
    return recipe;
  }
}```
