### ISSUE TITLE
Decorators to generate Fields

### ISSUE THREAD

**Issue by MentalGear** [MichalLytek/type-graphql#886]
First: Thank you @MichalLytek for all your work, the guide and all the examples! I guess I speak for most, that we are really appreciating your hard work.

**Is your feature request related to a problem? Please describe.**
I know about the limited TS reflection system, and why Properties and @Decorators Fields require redundant type definition. Yet, without a SPOT, there's more room for error.

**Describe the solution you'd like**
I was wondering if the ts properties could be generated from the @Field decorator?
Than we would need to define types only once, e.g.
Instead of:
```js
  @Field((type) => String)
  title!: string
```

```js
  @Field((type) => String, { name: title, required: true })
```

**Describe alternatives you've considered**
TS reflection

**Comment by MichalLytek** [comment]
Short answer: no 😅 

Wait for #296
