### ISSUE TITLE
@Root should support `returnTypeFunction`

### ISSUE THREAD

**Issue by proteriax** [MichalLytek/type-graphql#889]
**Is your feature request related to a problem? Please describe.**
I’m using esbuild with `type-graphql` so I need to annotate types explicitly. Most decorators allow the pattern of providing a class factory such as `() => [Recipe]` in case `emitDecoratorMetadata` doesn’t emit enough information, but not `@Root`.

**Describe the solution you’d like**
`@Root(() => Recipe)` should be supported.

**Describe alternatives you’ve considered**
Manually importing `__metadata` from `tslib` and annotate the type with a decorator myself.

**Additional context**
N/A

**Comment by proteriax** [comment]
I have a working fork that implements this. Let me know if you are interested in a pull request.

**Comment by MichalLytek** [comment]
`returnTypeFunction` is used to provide type info for GraphQL schema.

Root is not visible or reflected in the schema. It's just the object you return from resolvers (queries and mutations). Hence there's completely no need to provide info which won't be used anywhere 😝 

You can put whatever type you need as a type of `@Root` argument, it's not used for schema building.

> I have a working fork that implements this.

Now I wonder what do you do with those type info 😅

**Comment by proteriax** [comment]
@MichalLytek The problem is `@Root()` will throw if there is no parameter metadata for the decorated method. If it’s not used, then it shouldn’t check the type.

**Comment by MichalLytek** [comment]
You mean all the types are erased? So how the decorators works at all in your setup?

Please refer to #55 to get more details how to configure babel, webpack and other tools.

**Comment by proteriax** [comment]
Decorators and type metadata are two separate things. `esbuild` supports transforming decorators but not type metadata. I annotate all types manually. Anyway the point is, if it doesn’t need the type information, it shouldn’t ask for it.

**Comment by MichalLytek** [comment]
@proteriax TypeGraphQL is designed to work with TypeScript. JS support is not official and you need some workaround and plugins to make it work, as stated in #55.

**Comment by proteriax** [comment]
I’m confused. You first said

> info which won't be used anywhere

but also

> The root type info is used to create an instance of the object type class.

So does `@Root()` require runtime type information of the parameter it is decorating?

**Comment by MichalLytek** [comment]
`returnTypeFunction` is used to override reflected type to be used in schema. Root is not displayed in schema, hence it doesn't have `returnTypeFunction`.
