### ISSUE TITLE
FieldResolver decorator is not working at all

### ISSUE THREAD

**Issue by tareksalem** [MichalLytek/type-graphql#899]
**Describe the Bug**
honestly I am new to this library, I am trying to use `FieldResolver` decorator inside my resolver to pre-process a specific field for the incoming input of mutation, but it semms not working at all, not even called, I defined my ts config compilation configuration to es2020 and mad sure that I am using everything as described in the configuration

**To Reproduce**
Here is an example code that I am trying to achieve

Resolver
```typescript
import {
  Query,
  Resolver,
  Mutation,
  Arg,
  FieldResolver,
  Root
} from "type-graphql";
import { Todo, TodoInput } from "../schemas/Todo";

@Resolver((of) => Todo)
export class TodoResolver {
  private todos: Todo[] = [];

  @Query((returns) => [Todo], { nullable: true })
  async getTodos(): Promise<Todo[]> {
    return await this.todos;
  }

  @Mutation((returns) => Todo)
  async addTodo(
    @Arg("todoInput") { title, description }: TodoInput
  ): Promise<Todo> {
    const todo = {
      id: Math.random(), // not really unique
      title,
      description,
      status: false
    };
    await this.todos.push(todo);
    return todo;
  }
  @FieldResolver()
  async description(@Root() parent: TodoInput): Promise<string> {
    console.log(parent);
    return "hello world";
  }
}
```
Schema
```typescript
import { Field, ObjectType, InputType } from 'type-graphql'

@ObjectType()
export class Todo {
  @Field()
  id: number

  @Field()
  title: string

  @Field()
  description: string

  @Field()
  status: boolean
}

@InputType()
export class TodoInput implements Partial<Todo> {
  @Field()
  title: string

  @Field()
  description: string
}
```
Here is a full example on codesandbox
https://codesandbox.io/s/typegraphql-api-forked-0qqry

**Expected Behavior**
I expect that the fieldResolver work as described in the documentation

**Logs**
no error logs but also the field resolver is not executed

**Environment (please complete the following information):**

- OS: [e.g. linux]
- Node (14.17.0)
- Package version [1.1.1] 
- TypeScript version (4.0.5)

**Comment by MichalLytek** [comment]
> codesandbox.io/s/typegraphql-api-forked-0qqry

> (node:76) UnhandledPromiseRejectionWarning: Error: Some errors occurred while generating GraphQL schema:
  String cannot represent value: [function descriptions]

```ts
@InputType()
export class TodoInput implements Partial<Todo> {
  // ...

  @Field((type) => String)
  descriptions(@Root() parent: Todo): string {
    console.log(parent);
    return "hello world";
  }
}
```

@tareksalem `@InputType` does not have field resolvers capabilities like `@ObjectType`. 

> I expect that the fieldResolver work as described in the documentation

Show me where in documentation you can see an example of field resolver for input type.

> honestly I am new to this library, 

Have you learned already GraphQL basics? TypeGraphQL is abstraction on top of that, it's not a good idea to learn GraphQL by jumping straight to TypeGraphQL.

**Comment by tareksalem** [comment]
sorry for mistake, Ihave updated the codesandbox example,
the main issue is that fieldResolver is not working inside my resolver
https://codesandbox.io/s/typegraphql-api-forked-0qqry

**Comment by MichalLytek** [comment]
![image](https://user-images.githubusercontent.com/10618781/120072193-d4083d00-c092-11eb-9f38-7ab1a81cd928.png)

**Comment by tareksalem** [comment]
after testing the functionality of this decorator I found the following
- this decorator resolve the field when the field is returned in mutation response or in query response
Example:
```gql
mutation{
  addTodoSecond(todoInput: {title: "test", description: "qqq"}) {
    title,
    # description
  }
}
```
the above mutation will not call the field resolver, but if I specified the description to be returned then the resolver will work
- also noticed that the fieldResolver works after executing the resolver mutation, however, I was expecting that this field resolver will work for my mutation to update the field before sending it to a database or saving it but this actually is not working
Actually, I don't know if I misunderstood the behavior of this functionality or not, but in other words I expected that this decorator will work as a middleWare specified to this field that will process this field before executing the final resolver

**Comment by MichalLytek** [comment]
> the above mutation will not call the field resolver, but if I specified the description to be returned then the resolver will work

That's the behavior defined in `graphql-js`. Field resolvers are lazy handler that are evaluated when you select that field in your query. 

> I was expecting that this field resolver will work for my mutation to update the field before sending it to a database or saving it 

Field resolvers are not a validation/transform step independent from the GraphQL query.

That's GraphQL basics. Please read some introduction to GraphQL before reporting such issues 🔒
