### ISSUE TITLE
Types doesn't implement interface when interface contains a union

### ISSUE THREAD

**Issue by StarpTech** [MichalLytek/type-graphql#944]
**Describe the Bug**
As titled.

**To Reproduce**

```ts
@ObjectType(})
export class Seasons {
	@Field(() => Int)
	amount: number;
}
@ObjectType()
export class Years {
	@Field(() => [Year])
	years: [Year];
}
export const PeriodicalInformation = createUnionType({
	name: 'PeriodicalInformation',
	types: () => [Years, Seasons] as const,
	resolveType: (value) => {
		if ('years' in value) {
			return 'Years';
		}
		if ('amount' in value) {
			return 'Seasons';
		}
		return undefined;
	},
})

@InterfaceType()
export abstract class Media {
	@Field(() => ID)
	id: string;
	@Field(() => PeriodicalInformation)
	periodicalInformation: typeof PeriodicalInformation;
}

@ObjectType({ implements: Media })
export class Movie implements Media {
	@Field(() => ID)
	id: string;
	@Field(() => PeriodicalInformation)
	periodicalInformation: typeof PeriodicalInformation;
}

@ObjectType({ implements: Media })
export class Series implements Media {
	@Field(() => ID)
	id: string;
	@Field(() => PeriodicalInformation)
	periodicalInformation: typeof PeriodicalInformation;
}
```

Result in:

```graphql
type Movie implements Media {
  id: ID!
  periodicalInformation: PeriodicalInformation!
}
type Series {
  id: ID!
  periodicalInformation: PeriodicalInformation!
}
```

Removing the `periodicalInformation` field from the interface will produce the correct schema.

**Expected Behavior**
According to https://spec.graphql.org/June2018/#sec-Interfaces interfaces can contain unions.
Both types should implement the interface.

```graphql
type Movie implements Media {
  id: ID!
  periodicalInformation: PeriodicalInformation!
}
type Series implements Media {
  id: ID!
  periodicalInformation: PeriodicalInformation!
}
```

**Environment (please complete the following information):**

- OS: Linux
- Node: 14
- Package version: 1.1.1
- TypeScript version: 4.3.4

**Comment by MichalLytek** [comment]
You have a circular reference in your schema:

`Series -> Media -> PeriodicalInformation -> Seasons`

This breaks Node and that's why TypeGraphQL uses `() => Type` syntax.

`mplements` is the one that that is missing it, thus causing such problems.

**Comment by StarpTech** [comment]
Hi @MichalLytek, I don' see a circular reference? Could you elaborate?

**Comment by MichalLytek** [comment]
Sorry, I was seeing that `Seasons` is `Series` 😅 

I have no idea why the first one "sees" interface and the second one is not.
You have a typo in your code - are you sure this is a minimal reproducible code example?
```
@ObjectType({ implements: Media })
type Movie implements Media {
```

Maybe you have circular reference somewhere else in the code?

**Comment by StarpTech** [comment]
> You have a typo in your code - are you sure this is a minimal reproducible code example?

Yes, this was only a typo in the issue description.

As mentioned in the issue. Everything works without the union and there is no circular reference in the union.

**Comment by StarpTech** [comment]
@MichalLytek indeed, it was a circular reference issue across ts files! The fact that no error is thrown is super weird. We detected it with https://github.com/pahen/madge. Thank you for your help!

`madge --circular src/index.ts`

**Comment by StarpTech** [comment]
I think we can close it.
