### ISSUE TITLE
Type-graphql decoration 2 types

### ISSUE THREAD

**Issue by robenson-dev** [MichalLytek/type-graphql#951]
**Is your feature request related to a problem? Please describe.**
because i want to return 2 types
ex:
**@Mutation(() => (User||String), {nullable: true})
    async signin(
        @Arg("email") email: string,
        @Arg("password") password: string,
        @Ctx() ctx: Context
    ): Promise<User | string> {}**

**Describe the solution you'd like**
You can also propose how the new API should looks like.

**Describe alternatives you've considered**

**Additional context**

**Comment by MichalLytek** [comment]
Not possible by GraphQL spec.
To return two types, you need to use unions:
https://typegraphql.com/docs/unions.html

And unions do not accept scalars, so you need to create wrappers like `StringBox -> { value: string }`
