### ISSUE TITLE
Provide a mechanism to pre-generate schema at design time

### ISSUE THREAD

**Issue by mdesousa** [MichalLytek/type-graphql#963]
Thanks for this great package, we have found it very useful!

We are using aws lambda to run our graphql service (we use `apollo-server-lambda`, and `typegraphql-prisma`).
We are noticing a couple of challenges with this setup:
* lambdas are slow on cold-start. we've noticed that they take about 6 seconds to run tq.buildSchema({ resolvers })
* we cannot minify our code to reduce the size of the bundle. minification results in issues with the schema generation (classes and functions get renamed and the schema that is generated is incorrect)

**Describe the solution you'd like**
We would like to be able to emit files necessary for both the schema definitions (already done today) and the resolver definitions (e.g. their names and types). Then at runtime, we would like to create an executable schema from the schema/resolver definitions and the array of resolver classes (which may have been mininified, but their order in the array should be consistent with the order at design time).

**Describe alternatives you've considered**
I have considered extracting the resolver metadata at design time, and store in a json. Then using [makeExecutableSchema](https://www.graphql-tools.com/docs/generate-schema/) at runtime to quickly create the schema. This should be faster, would reduce bundle size (all schema generation logic and dependencies can be removed), and would result in a working schema that is not impacted by bundling and minification.

Thanks

**Comment by MichalLytek** [comment]
> I have considered extracting the resolver metadata at design time, and store in a json. Then using makeExecutableSchema at runtime to quickly create the schema. This should be faster, 

That's the current design of TypeGraphQL schema building. Decorators are collecting metadata and register it in metadata storage (in memory). Then `buildSchema` is reading that metadata and calling `new GraphQLSchema()` to create an instance of an executable GraphQL schema.

So writing that metadata to JSON won't speed this process at all, only slow down because of reading from disk.

> minification results in issues with the schema generation (classes and functions get renamed and the schema that is generated is incorrect)

You can overcome that by specifying the name in the decorators:
```ts
@ObjectType({ name: "Foo" })
class Foo {
  @Field({ name: "Bar" })
  bar!: string;
}
```

Or you can find a way to stop mangling the names for selected files/patterns with the TypeGraphQL stuff.

**Comment by mdesousa** [comment]
Thanks for your response! You are right... I tested it out and the `buildSchema` seems to be fast enough, and performance equivalent to reading from a file. It may however reduce the number of dependencies needed at runtime? For example, libraries like `reflect-metadata` and other code wouldn't be required.
Thanks for the tip on using the @ObjectType({name})... we are currently genering our code with `typegraphql-prisma`, i'll see if there is a way to generate that decorator there.

**Comment by mdesousa** [comment]
just realized that you are also the author of `typegraphql-prisma` 🥇 
do you know if we can get it to add names to the object types to avoid the bundling issues?
thanks

**Comment by MichalLytek** [comment]
Please create an issue on `typegraphql-prisma` repo, I think we can simply add a configuration option to emit original names in decorator options 😉

**Comment by MichalLytek** [comment]
Closing for a housekeeping purposes 🔒
