### ISSUE TITLE
Get the parent field in a nested document field resolver

### ISSUE THREAD

**Issue by nivo33** [MichalLytek/type-graphql#971]
### Discussed in https://github.com/MichalLytek/type-graphql/discussions/967

<div type='discussions-op-text'>

<sup>Originally posted by **nivo33** August  1, 2021</sup>
Hi, I need to access the fields of the parent in a field resolver. @Root() used to contain a `$parent` field, but I just updated from mongoose ~5.10 to ~5.13 and its gone. Any ideas?

Here is my classes (simplified):

```
ObjectType()
class Entity { 
@Field()
name: string

@Field()
data: Data
}

ObjectType()
class Data{
@Field()
type: string
}

@Resolver(() => Data)
class BResolvers {
   @FieldResolver(() => string)
   metadata(@Root() root, @Ctx() ctx) {
    // I need to access the parents Entity.name field here, but I can't. `root` contains only the Data  fields.
   // used to be that root.$parent contained the fields of the parent Entity - its now gone, and root is just an instance of Data
   }
 
}
```

I have a simple resolver that returns an instance of Entity.

Thanks!</div>

**Comment by MichalLytek** [comment]
Please do not repost your questions as GitHub issues 🔒
