### ISSUE TITLE
Generated Fragments

### ISSUE THREAD

**Issue by Huge-Puppy** [MichalLytek/type-graphql#980]
**Is your feature request related to a problem? Please describe.**
Querying object fields gets tedious without fragments defined in the schema.

**Describe the solution you'd like**
I would like fragments automatically generated for the objects I define. Perhaps add a decorator or parameter that will tell type-graphql which fields to add to the fragment.

**Describe alternatives you've considered**
I've considered defining fragments myself and just having long client side queries

**Comment by MichalLytek** [comment]
Fragments are client side GraphQL thing. I can't do anything about it.
