### ISSUE TITLE
Performance slowdown with field argument validation and yarn2

### ISSUE THREAD

**Issue by jonnydgreen** [MichalLytek/type-graphql#982]
**Describe the Bug**

Hi! :) We are using `type-graphql` with `yarn2` and have uncovered a slow down when activating validation on field arguments.

**To Reproduce**

* Install `type-graphql` using `yarn2`
* Define an argument on a GraphQL field with validation enabled

```ts
@Resolver()
export class ExampleResolver {
  constructor() {...}

  @Query(() => [Example], {
    description: "Example.",
  })
  public async getExamples(
    @Args({ validate: true }) queryArguments: GetExamplesArguments
  ): Promise<Example[]> {
    return this.exampleService.getExamples(context, queryArguments);
  }
}
```

* Run a load of requests that include the protected field

**Expected Behaviour**

No or negligible performance impact.

**Logs**

Partial flame graph of request profile:

<img width="1053" alt="Screenshot 2021-08-11 at 16 54 31" src="https://user-images.githubusercontent.com/31290910/129062404-d5429048-d7a6-4e26-8014-f0a9d64ea5ea.png">

**Environment (please complete the following information):**

- OS: Linux, MacOS
- Node 14.17.4
- Package version 1.1.1
- TypeScript version 4.3.5

**Additional Context**

When turning off the validation (i.e. setting it to `false`) in the `type-graphql` options, the performance decrease goes away and everything is back to normal.

I looked into it a bit and I believe the issue is with this `await import(...)` line here: https://github.com/MichalLytek/type-graphql/blob/master/src/resolvers/validate-arg.ts#L32. Because `yarn2` uses a synchronous function under the hood to import packages at runtime, this causes a significant slow down under heavy load.

I did a bit of digging and found this commit https://github.com/MichalLytek/type-graphql/commit/f122fdb855207e0907564ced2242a66e73dcc44c that makes this a virtual peer dependency, so I'm guessing this isn't feasible to undo?

**Comment by MichalLytek** [comment]
> When turning off the validation (i.e. setting it to false) in the type-graphql options, the performance decrease goes away and everything is back to normal.

I can't do nothing about it, `class-validator` is really heavy, bloated, the whole validation and middlewares pipeline is async, etc. You can try with other libs, as e.g. shown in examples with joi.

>  Because yarn2 uses a synchronous function under the hood to import packages at runtime, this causes a significant slow down under heavy load.

Yarn 2 has so many flaws that I don't want to tune anything specially for Yarn 2.

You can try to make a fork, "undo" the `await import` change and see if that fixes your issue.

**Comment by jonnydgreen** [comment]
Thank you for the tips - I managed to resolve the issue by providing a new custom global validator function which resolved the performance issue. I'll close this issue unless you'd like me to submit a PR for reverting the `await import` change for the default function? :)

**Comment by MichalLytek** [comment]
You can post here your solution (code) so any other users can benefit from this thread 😉

**Comment by jonnydgreen** [comment]
For sure! Here's my solution for anyone reading :)

```ts
const schema = await buildSchema({
  ...options,
  async validate(argumentValue: unknown): Promise<void> {
    if (typeof argumentValue !== "object" || argumentValue === null) {
      return undefined;
    }

    try {
      const validateOptions: ValidatorOptions = { skipMissingProperties: true };
      if (Array.isArray(argumentValue)) {
        await Promise.all(argumentValue.map((argumentItem) => validateOrReject(argumentItem, validateOptions)));
      } else {
        await validateOrReject(argumentValue, validateOptions);
      }
      return undefined;
    } catch (error) {
      throw new ArgumentValidationError(error);
    }
  },
});
```
