### ISSUE TITLE
Support for apollo federation annotations

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [MichalLytek/type-graphql#985]
Hi, 

I have built one server using your library and I really like it. 
I am going to start building admin server and would like to take advantage of using previously built api adding new admin features on top. For this I planned to use apollo federation. 
Apollo federation uses specific annotations like 'extend' and similar. It would be good if this library supports them because at the end of the day it is just how schema is generated.

**Comment by MichalLytek** [comment]
There is a whole documentation about directives. If you read Apollo Federation docs, you know you need to use directives, so I think there's nothing else to describe, the example says 10 time more.

**Comment by vytautas-pranskunas-** [comment]
And yes and no. Simple menu item called Apollo Federation with url to github code example would prevent creating issues like this. But it is up to you of course :)

**Comment by MichalLytek** [comment]
There's a whole tab "examples" on the docs page, with Apollo Federation listed.
https://typegraphql.com/docs/examples.html

Same goes to search capabilities:
![image](https://user-images.githubusercontent.com/10618781/129174502-4eee4625-e097-42b8-8596-8a50550ecfd7.png)

**Comment by vytautas-pranskunas-** [comment]
Perfect
